### PR TITLE
Update last written LSN after walloging all createdb stuff

### PR DESCRIPTION
**Pull request by knizhnik**
## Problem

See https://neondb.slack.com/archives/C033RQ5SPDH/p1694595347598249

## Summary of changes

Update last written LSN after walloging all createdb stuff

## Checklist before requesting a review

- [ ] I have performed a self-review of my code.
- [ ] If it is a core feature, I have added thorough tests.
- [ ] Do we need to implement analytics? if so did you add the relevant metrics to the dashboard?
- [ ] If this PR requires public announcement, mark it with /release-notes label and add several sentences in this section.

## Checklist before merging

- [ ] Do not forget to reformat commit message to not include the above checklist

### CODE REVIEW

**Review by tristan957 — APPROVED** [review]
Confirmed that these are the correct shas.

**Comment by tristan957** [comment]
Test failure seems unrelated.

**Comment by tristan957** [comment]
Have we come up with any way to test the changes to make sure this doesn't happen again?

**Comment by knizhnik** [comment]
PG14 has different implementation of `CREATE DATABSE`: it doesn't have `CreateDatabaseUsing*` functions and writing `XLOG_DBASE_CREATE` is done at the end of database creation - when all tables are already created.

**Pull request merged**
