### PR TITLE
Fix typos

### PR DESCRIPTION
**Pull request by kianmeng**

### CODE REVIEW

**Review by hlinnaka — APPROVED** [review]

**Comment by hlinnaka** [comment]
Merged, thank you!

**Comment by kianmeng** [comment]
:partying_face: :partying_face: :partying_face: :partying_face: :partying_face:

**Comment by kelvich** [comment]
I also wonder were these typos caught by some tool? Would be good to integrate something and have `make grammar-check`

**Comment by kianmeng** [comment]
@kelvich FYI.
Using https://github.com/codespell-project/codespell.
You can create a GitHub Action for it, based on https://github.com/codespell-project/actions-codespell

**Pull request merged**
