### PR TITLE
fixup(#6893): report_size() still used pageserver_created_persistent_* metrics

### PR DESCRIPTION
**Pull request by problame**
Use the remote_timeline_client metrics instead, they work for layer file uploads and are reasonable close to what the `pageserver_created_persistent_*` metrics were.

Should we wait for empty upload queue before calling `report_size()`?

part of https://github.com/neondatabase/neon/issues/6737

### CODE REVIEW

**Comment by problame** [comment]
> Should we wait for empty upload queue before calling report_size()?

Hm, we can avoid that by using the `_started` metrics instead (?)

**Review by koivunej — APPROVED** [review]
Looking good, I was not expecting this since no one had been using the collected benchmark data to notice how pg16 inflates the layer sizes before #5392. It seems you were even asking for a regression test there :)

**Comment by koivunej** [comment]
> > Should we wait for empty upload queue before calling report_size()?
> 
> Hm, we can avoid that by using the `_started` metrics instead (?)

In general the benchmarks which I've seen haven't used flushing, but your idea makes sense.

**Comment by problame** [comment]
I don't aim to add a regression test here.

Regarding `_finished` vs `_started`: what I mean is that the metrics removed in https://github.com/neondatabase/neon/pull/6893 were incremented when we wrote the layer to local disk, whereas the `_finished` metrics that I'm proposing as a substitute in this PR are only incremented after the layers have been uploaded.

Hence, if the benchmark doesn't wait for upload queue to be empty, then it will record lower numbers with this PR than it did earlier.

**Comment by koivunej** [comment]
> Hence, if the benchmark doesn't wait for upload queue to be empty, then it will record lower numbers with this PR than it did earlier.

Yes, for this reason what you were suggesting earlier would make sense:

> Hm, we can avoid that by using the _started metrics instead (?)

**Pull request merged**
