### PR TITLE
Merge release into main

### PR DESCRIPTION
**Pull request by vadim2404**
## Describe your changes
In order to avoid future conflicts

## Checklist before requesting a review
- [ ] I have performed a self-review of my code.
- [ ] If it is a core feature, I have added thorough tests.
- [ ] Do we need to implement analytics? if so did you add the relevant metrics to the dashboard?
- [ ] If this PR requires public announcement, mark it with /release-notes label and add several sentences in this section.

### CODE REVIEW

**Review by shanyp — APPROVED** [review]

**Review by koivunej — CHANGES_REQUESTED** [review]
Why is this needed?

**Comment by vadim2404** [comment]
> Why is this needed?

There is a diff between these two branches in commits. The primary purpose was to make them identical.

**Review by koivunej — COMMENTED** [review]
Ok.. Not a huge fan of this but I guess somehow this line got changed. Let's hope it's the only one. Ok to squash, no merge commit right?

**Comment by vadim2404** [comment]
> Ok.. Not a huge fan of this but I guess somehow this line got changed. Let's hope it's the only one. Ok to squash, no merge commit right?

Hope I will not brake backward merges!

**Comment by koivunej** [comment]
Oops, thought a review comment would had cleared my status. Fine with squash commit :)

**Review by koivunej — APPROVED** [review]
Ok the review status cannot be cleared except for approving this. I didn't want to approve this but approving it only for squashing.

**Comment by hlinnaka** [comment]
I still don't understand, what is this all about?

**Comment by vadim2404** [comment]
closed because of #3580

**Pull request closed without merging**
