### PR TITLE
Introduce TimelineRef and TimelineGuard wrappers

### PR DESCRIPTION
**Pull request by SomeoneToIgnore**
https://github.com/neondatabase/neon/pull/3252 review feedback changes become big, extracted for better visibility and different CI runs.

### CODE REVIEW

**Comment by hlinnaka** [comment]
Hmm, the point of the TimelineGuard is that you have a mechanism to wait for all accesses to the Timeline to have finished, when deleting a timeline. But I don't see a such a wait-until-all-guards-are-gone function here. Or is there some other purpose for this, am I missing something?

**Comment by hlinnaka** [comment]
> Hmm, the point of the TimelineGuard is that you have a mechanism to wait for all accesses to the Timeline to have finished, when deleting a timeline. But I don't see a such a wait-until-all-guards-are-gone function here. Or is there some other purpose for this, am I missing something?

PR #3228 introduces a mechanism like that, the idea being that you can wait until all RequestContexts associated with a Timeline are gone (implemented by just polling in that PR). However, it's pretty incomplete, because there is mechanism to enforce that you must hold a particular RequestContext when accessing the Timeline; you could pass a completely unrelated RequestContext. But I think that would be pretty straightforward to fix, by introducing a TimelineRequestContext object that is just a wrapper around RequestContext but is always associated with a particular Timeline, and changing all the functions in Timeline to take a `&TimelineRequestContext` as parameter instead of plain `&RequestContext`. What do you think?

**Comment by SomeoneToIgnore** [comment]
I would imagine we want to do that in the end, but so far I want to finish the initial task https://github.com/neondatabase/neon/pull/3252 (that's now used as a PR base) and have to scope my PR somehow.

I want to have an API that allows us to improve later, including the waiting (if needed, maybe part of the `cxt` management would do that instead?).
For now, my main goal was to remove `Arc<Timeline>` to prepare myself for creating some `Walreceiver` struct/enum that would be able to collect its node statistics (to print in `wait_lsn` error log later)

**Comment by SomeoneToIgnore** [comment]
Yes, I think that at least currently, my wrapper is mainly about forbidding the `Arc` spread, not about any kind of waits.
Your approach, on the contrary, has first steps in that direction, so, with the new ideas, might make sense to continue there meanwhile: both entities are somewhere around the timeline and tenant wrapper will also follow, so we can unite them later, if needed.

**Comment by hlinnaka** [comment]
> I would imagine we want to do that in the end, but so far I want to finish the initial task #3252 (that's now used as a PR base) and have to scope my PR somehow.
> 
> I want to have an API that allows us to improve later, including the waiting (if needed, maybe part of the `cxt` management would do that instead?). For now, my main goal was to remove `Arc<Timeline>` to prepare myself for creating some `Walreceiver` struct/enum that would be able to collect its node statistics (to print in `wait_lsn` error log later)

Ok. I don't quite see the big picture of where these changes are leading, but incremental development is good, and I don't have any objections to these changes.

**Pull request closed without merging**
