### PR TITLE
Ignore key not found error when mapping timestamp to LSN

### PR DESCRIPTION
**Pull request by knizhnik**
refer #2539

### CODE REVIEW

**Review by SomeoneToIgnore — COMMENTED** [review]
The fix looks good to me, but it appears that it's relatively easy to create a unit test on this?
It's a `pub fn find_lsn_for_timestamp` and inside all we need is a bunch of dates to compare to, so we can add a very good explanation on what happens here with that test.

If I'm mistaken somehow and it's hard to create a test, might be good to add a comment instead at least.

**Comment by knizhnik** [comment]
> The fix looks good to me, but it appears that it's relatively easy to create a unit test on this? It's a `pub fn find_lsn_for_timestamp` and inside all we need is a bunch of dates to compare to, so we can add a very good explanation on what happens here with that test.
> 
> If I'm mistaken somehow and it's hard to create a test, might be good to add a comment instead at least.

It is possible to reproduce the problem in #2539 only if we somehow force restoring `latest_gc_cutoff` from metadata file preceding real cutoff value. It seems to be possible only in case of abnormal pageserver termination or forced replacing local metadata file by older one from S3.

**Comment by SomeoneToIgnore** [comment]
What you've described makes quite a good idea for the e2e test on Python, but IMO that is a bit hard to do and might make no sense in the long run when we change the way mechanisms work.

I was interested to write  a `#[test]` unittest on module's public contract (as `pub fn`), that checks the corner case that the fix was added on.

**Comment by hlinnaka** [comment]
-1, I don't think this is the right approach. This will silently swallow *any* error. Let's fix the GC routine so that it doesn't try to call this function with an already-removed LSN in the first place.

**Comment by hlinnaka** [comment]
https://github.com/neondatabase/neon/pull/2558 has been merged, so find_lsn_for_timestamp() should no longer try to probe already-removed LSNs. Closing.

**Pull request closed without merging**
