### PR TITLE
use hnsw from submodule

### PR DESCRIPTION
**Pull request by skyzh**
## Checklist before requesting a review

- [x] I have performed a self-review of my code.
- [ ] If it is a core feature, I have added thorough tests.
- [ ] Do we need to implement analytics? if so did you add the relevant metrics to the dashboard?
- [ ] If this PR requires public announcement, mark it with /release-notes label and add several sentences in this section.

## Checklist before merging

- [ ] Do not forget to reformat commit message to not include the above checklist

### CODE REVIEW

**Comment by skyzh** [comment]
This PR is causing some problems when I switch between this branch and other branches:

```
error: The following untracked working tree files would be overwritten by checkout:
        pgxn/hnsw/Makefile
        pgxn/hnsw/README.md
        pgxn/hnsw/hnswalg.cpp
        pgxn/hnsw/hnswalg.h
        pgxn/hnsw/test/expected/knn.out
        pgxn/hnsw/test/sql/knn.sql
Please move or remove them before you switch branches.
```

Probably we should give a new name to the hnsw directory so that it won't cause trouble when checkout if this PR gets merged.

**Review by knizhnik — APPROVED** [review]

**Comment by bayandin** [comment]
I'd say that we should deprecate and remove hnsw from the repo and threat it as any other extension (we build pg_embedding for compute-node image already). 
What do you think @vadim2404?

**Comment by vadim2404** [comment]
I agree here. I'm not sure that we need to add one more submodule

**Comment by skyzh** [comment]
Yeah I just realized that it's already in the compute node image so I opened https://github.com/neondatabase/neon/pull/4677 to directly remove it. I'm not sure if there will be any potential conflicts or incompatibility with that PR.

**Pull request closed without merging**
