### PR TITLE
Ignore page header when comparing VM pages in test_vm_bits.py

### PR DESCRIPTION
**Pull request by knizhnik**
## Problem

See #6714, #6967

## Summary of changes

Completely ignore page header when comparing VM pages.

## Checklist before requesting a review

- [ ] I have performed a self-review of my code.
- [ ] If it is a core feature, I have added thorough tests.
- [ ] Do we need to implement analytics? if so did you add the relevant metrics to the dashboard?
- [ ] If this PR requires public announcement, mark it with /release-notes label and add several sentences in this section.

## Checklist before merging

- [ ] Do not forget to reformat commit message to not include the above checklist

### CODE REVIEW

**Comment by hlinnaka** [comment]
>     # Also in neon SMGR we can replace empty heap page with zero (uninitialized) heap page.

This sounds scary. Why does that happen?

**Comment by jcsp** [comment]
Is anything blocking this?  I notice it doesn't have a reviewer assigned.

Chasing because it's the most frequent failure in the suite.

**Comment by knizhnik** [comment]
> Also, this is about a VM page; how is replacing an empty heap page with an all-zeros page related to this?

Sorry, you are right. It is not somehow related to VM.
Looks like the different scenario takes place:
- when  VM is extended using smgr_zeroextend zero page is walloged.
- then page is initialised by `vm_readbuf`. This operation is*NOT* walloged. If page is thrown from shared buffers, then it will be walloged and neon_smgr (special behaviour for VM/FSM forks). But if it is not evicted from shared buffers then it is walloged.
- test compares local VM page image (initialized page) with page received from PS (zero page), which cause assertion failure.

So despite to the fact that my explanation of the source of the problem were not correct, this PR is still relevant.

**Review by skyzh — APPROVED** [review]

**Comment by skyzh** [comment]
I don't know Postgres internals but the explanation of why header is different sounds reasonable. Approving to make test suites more stable.

**Pull request merged**
