### PR TITLE
dump more info in layer map

### PR DESCRIPTION
**Pull request by skyzh**
## Problem

A simple commit extracted from https://github.com/neondatabase/neon/pull/4539

## Summary of changes

This PR adds more info for layer dumps (is_delta, is_incremental, size).

## Checklist before requesting a review

- [x] I have performed a self-review of my code.
- [ ] If it is a core feature, I have added thorough tests.
- [ ] Do we need to implement analytics? if so did you add the relevant metrics to the dashboard?
- [ ] If this PR requires public announcement, mark it with /release-notes label and add several sentences in this section.

## Checklist before merging

- [ ] Do not forget to reformat commit message to not include the above checklist

### CODE REVIEW

**Comment by LizardWizzard** [comment]
> the image layer may only contain part of the images within the key range.

Why not to shrink the key range instead? Or incremental layer can contain images from entire key range?

**Comment by skyzh** [comment]
> Or incremental layer can contain images from entire key range?

Incremental layer contains part of the keys from an entire key range. Previously, we will scan all keys within the range to construct the layer so that we don't need to search more once we hit the image layer. However, it is costly to construct such image layers, because we need to scan *every key* in the range. Therefore, with incremental image layer, an image layer can only contain some keys within the key range, and we can decide whether to generate an image for a key based on some heuristics.

**Comment by skyzh** [comment]
this might cause we miss the delta records == image_lsn, converting to draft.

**Comment by skyzh** [comment]
The true implementation for incremental layer is more complex than I thought and therefore I excluded it from this PR. Now we only have the dump more info thing in this PR and appreciate an easy approval from someone :)

**Review by shanyp — APPROVED** [review]

**Pull request merged**
