### PR TITLE
Implement RemoteStorage trait for GenericRemoteStorage.

### PR DESCRIPTION
**Pull request by hlinnaka**
We had a pattern like this:

    match remote_storage {
        GenericRemoteStorage::Local(local_storage) => {
            let source = local_storage.remote_object_id(&file_path)?;
            ...
            local_storage
                .function(&source, ...)
                .await
       },
       GenericRemoteStorage::S3(local_storage) => {
	    ... exact same code as for the Local case ...
       },

Reduce the code duplication by implementing RemoteStorage trait for
GenericRemoteStorage itself.

My first thought was to make GenericRemoteStorage just an alias for
"dyn RemoteStorage", but that did't work because the trait contains
RemoteStorageId type, which is used by all the functions. I actually
think we should remove the generic RemoteStorageId trait, and just
define RemoteStorageId as String or a newtype over String. That would
allow using "dyn RemoteStorage". But I didn't dare to do it just yet.

### CODE REVIEW

**Comment by hlinnaka** [comment]
WDYT @SomeoneToIgnore? I found it weird and cumbersome that GenericRemoteStorage didn't implement the RemoteStorage trait.

What do you think of replacing RemoteObjectId with something like `struct RemoteObjectId(String)`, so that GenericRemoteStorage could be just `dyn RemoteStorage`?

**Review by SomeoneToIgnore — COMMENTED** [review]
The code itself looks nice to me, I'd consider some macro for the `GenericRemoteStorage` impl, since those methods get quite repetative.

I've actually shared my thoughts in the original discussion: https://github.com/neondatabase/neon/pull/2231#discussion_r950673198 :slightly_smiling_face:

I see that safekeeper uses a static object, hence unable to use generics and bails to `GenericRemoteStorage` with matches around it.

This approach indeed contradicts the whole idea of different associated types for trait impls and some newtype is needed to be used instead.
I would advocate against using `String` directly though, since it's very untyped and `PathBuf` and `S3Path` are very different to be covered by just `String`.


I find odd though, that we will have to maintain various

> `panic!("unexpected remote object id kind");`

lines ourselves, since it's pretty much what the compiler does for us with the associated types exactly.
We also use a lot of almost duplicated code when dealing with the enum impls, due to the similar reason, I assume.

Curious, how this approach will scale with a few more storage flavours added on top, I expect the number of similar `panic!` will grow quite fast.

------------------

Given all that, I'd like to be interested to consider what was so bad with the 

```
where
     P: Debug + Send + Sync + 'static,
     S: RemoteStorage<RemoteObjectId = P> + Send + Sync + 'static,
```

approach, besides its verbosity?

We can create a global object somewhere at the top, then toss it around in `GenericRemoteStorage` and eventually call some `fn` with that `where` defined.
No matches or whatsoever, we define the needed `P` traits on every method separately and able to be flexible over what that `P` as a repo path is.

One good reason to argue against using `GenericRemoteStorage` is unit testing: if I understand it right, current safekeeper code is not able to replace it with the mock test impl, while the generics-based code could do that relatively simply.

------------------

I'm not sure that the generics approach is right though, so if you insist on pushing this, another, less biased in opposite, reviewer is good to have to ensure we're doing things right.

**Comment by hlinnaka** [comment]
> I've actually shared my thoughts in the original discussion: https://github.com/neondatabase/neon/pull/2231#discussion_r950673198 slightly_smiling_face

Ah, thanks! I remembered we talked about this, but didn't remember where :-).

> I would advocate against using String directly though, since it's very untyped and PathBuf and S3Path are very different to be covered by just String.

Agreed that a newtype would be better than plain String. But I don't see why the LocalFS and S3 implementations couldn't use the same newtype. Surely any implementation you can imagine would use similar path-like keys. Or at least something that can be stored in a String.

I can code that up and we'll see what it looks like.

> I find odd though, that we will have to maintain various
> 
>     panic!("unexpected remote object id kind");
> 
> lines ourselves, since it's pretty much what the compiler does for us with the associated types exactly.
> We also use a lot of almost duplicated code when dealing with the enum impls, due to the similar reason, I assume.

So, with this PR, the compiler allows you to do this:
```
let local = GenericRemoteStorage::Local(...);
let s3 = GenericRemoteStorage::S3(...);

// Construct ID using 'local'...
let id = local.remote_object_id("foo");

// ... and use it with the other RemoteStorage implementation!
s3.download(id);
```

You will get a panic at runtime. On 'main', the compiler won't let you do that. I think a runtime-panic is fine for that or we can make it an Err if you'd prefer. It's a highly unlikely mistake to make, and you can always shoot yourself in the foot if you try hard enough. Even on 'main', you can do this:
```
let bucket_a = GenericRemoteStorage::S3(config for bucket A);
let bucket_b = GenericRemoteStorage::S3(config for bucket B);

// Construct ID using bucket_a...
let id = bucket_a.remote_object_id("foo");

// ... and use it with the other bucket!
bucket_b.download(id);
```
That's similarly bogus.

> Curious, how this approach will scale with a few more storage flavours added on top, I expect the number of similar panic! will grow quite fast.

Some macro magic could help with that. But yeah, I'd prefer to make RemoteObjectId a newtype over String, make GenericRemoteStorage an alias over `dyn RemoteStorage`, and get rid of all this "hand-rolled VTable" code.

> Given all that, I'd like to be interested to consider what was so bad with the
> 
> where
>      P: Debug + Send + Sync + 'static,
>      S: RemoteStorage<RemoteObjectId = P> + Send + Sync + 'static,
> 
> approach, besides its verbosity?

Well, it is verbose for starters :-). It proliferates through everything that touches the RemoteStorage. Presumably also increases compilation time as all those functions need to be compiled twice. But my biggest complaint is that somewhere you will *still* need to have that pattern where you check the concrete implementation with `match`, and dispatch to the right implementation. If it's not in GenericRemoteStorage itself, it needs to be somewhere in the code that uses it. Currently on 'main', we have that in the pageserver in `gather_tenant_timelines_index_parts` and `start_local_timeline_sync`, and in safekeeper in `backup_object` and `read_object`.

> We can create a global object somewhere at the top, then toss it around in GenericRemoteStorage and eventually call some fn with that where defined.
No matches or whatsoever, we define the needed P traits on every method separately and able to be flexible over what that P as a repo path is.

Sorry, I didn't understand that.

> One good reason to argue against using GenericRemoteStorage is unit testing: if I understand it right, current safekeeper code is not able to replace it with the mock test impl, while the generics-based code could do that relatively simply.

I don't see why it couldn't use a mock implementation. I guess the main hurdle there is using the `static` to hold the RemoteStorage reference, but that's a separate issue.

> I'm not sure that the generics approach is right though, so if you insist on pushing this, another, less biased in opposite, reviewer is good to have to ensure we're doing things right.

WDYT @LizardWizzard ?

**Comment by SomeoneToIgnore** [comment]
> Sorry, I didn't understand that.

I've decided to demonstrate it on an example and ended up with https://github.com/neondatabase/neon/pull/2360 as something opposed to current PR, applying my "tossing around" suggestions.
One notable difference I personally enjoy is that the amount of matches over the storage generic is not that big, yet has no `panic!` sections as in this PR, retains the typization level we have now, while allowing to write whatever specific code for any of the remote storage types, if needed.

**Comment by LizardWizzard** [comment]
> Surely any implementation you can imagine would use similar path-like keys.

Should be possible to create an implementation that will use integer keys. Probably not something we'll actually do, but possible

> But I don't see why the LocalFS and S3 implementations couldn't use the same newtype

Thats definitely possible, but has some drawbacks though not necessarily immediately noticeable by us. For local storage it means that we will convert PathBuf to String (or newtype around it) back and forth which is a bit inconvenient. Different remote storage implementations can have different meaning for certain aspects. To me it is the responsibility of the RemoteStorage implementation to keep it's Id in specific shape. If we combine them in one type it will be harder to guarantee that certain assumptions stay valid between calls to different storages. It can lead to repetitive checks and adjustments in RemoteStorage implementations because there is no knowledge regarding the way how this id was produced. (After writing this found out that this is almost the same as @SomeoneToIgnore's comment here https://github.com/neondatabase/neon/pull/2368/files#r959398595) Rather synthetical example would be different treatment of ids with and without trailing separator by S3 See this part of `list_prefixes`: https://github.com/neondatabase/neon/blob/a4803233bbf825449c2481aa78bf37c929cc0411/libs/remote_storage/src/s3_bucket.rs#L324. In S3 separator can be arbitrary symbol in contrast with `PathBuf` where it is only the system defined one. Interesting observation is that current [remote_object_id](https://github.com/neondatabase/neon/blob/main/libs/remote_storage/src/s3_bucket.rs#L254) implementation in S3Bucket  should work even with windows style paths because it reassembles remote object id taking segments of local path and using S3_SEPARATOR to join them back. Looking into aws docs, there is [this page](https://docs.aws.amazon.com/AmazonS3/latest/userguide/object-keys.html). The interesting sections are `Characters that might require special handling` and `Characters to avoid`. That puts additional distinctions in requirements for file path and s3 object id. Probably we wont face that as names of our files do not contain these symbols, but with current schema we can easily add checks if we need to. (Though s3 sdk still accepts String) Probably there are other distinctions I didnt know of. Problems I mentioned may look rather synthetical and not applicable to us. Probably having PathBuf everywhere would work in most of the cases, but it can have some surprises and model with separate RemoteStorageId is flexible enough to easily account for them.

> On 'main', the compiler won't let you do that. I think a runtime-panic is fine for that or we can make it an Err if you'd prefer. It's a highly unlikely mistake to make, and you can always shoot yourself in the foot if you try hard enough.

Not having protection in some case doesnt mean that we should throw away working protection mechanisms. IMO if we can prevent some errors in compile time thats a good thing to keep.

> That's similarly bogus.

I do not agree that this is similar. It will be a problem if prefixes for these storage instances do not match (we can check that ). But otherwise it can be a feature. If you're copying file from one bucket to another, or comparing checksums of the RemoteObjectId between different buckets this code is fine. 

Switching to single common RemoteObjectId wont save us from this situation. On main you cant mix paths from one type of remote storage with another If we really have to for some reason, we can chose some middle ground which will probably be PathBuf and conversion to String when needed. Another and to me better option would be sticking with different types and rather implementing conversion between them via From trait. 

> Well, it is verbose for starters :-). It proliferates through everything that touches the RemoteStorage

Had a quick chat with @funbringer about better ergonomics in these aspects and he suggested some promising ideas. Some of the bounds are actually not needed in some cases. Quite often functions can accept just `storage: &impl RemoteStorage`. If we always require additional properties along with implementation of `RemoteStorage` (like Debug impl on RemoteObjectId) we can include these bounds in the trait itself, or make a separate alias for that. We cannot use true alias because this feature is unstable but there is a workaround. Something like that should work:

```rust
pub trait PageserverRemoteStorage: RemoteStorage + Debug + Send + Sync + 'static
where
    Self::RemoteObjectId: Debug,
{
}

impl<T> PageserverRemoteStorage for T
where
    T: RemoteStorage + Debug + Send + Sync + 'static,
    T::RemoteObjectId: Debug,
{
}
```

With this it should be possible to pass remote storage as just `&impl RemoteStorage` everywhere which looks quite clean to me. So personally I'm for keeping generics and rather simplifying their usage to a point where we can avoid using `GenericRemoteStorage`. I started to poke on that, will see how it goes, so now there is a third option :) WDYT?

**Comment by LizardWizzard** [comment]
I tried to implement generic only solution in #2387, it had its pros and cons and downsides did overweight see https://github.com/neondatabase/neon/pull/2387#issuecomment-1237038312

So I think the way forward is #2368

**Comment by SomeoneToIgnore** [comment]
After multiple follow-up PRs and discussions, we've seem to come up with a different approach to try: https://github.com/neondatabase/neon/pull/2368#issuecomment-1240570444

**Pull request closed without merging**
