### PR TITLE
Compare with target image LSN in DeltaLayer::get_value_reconstruct_data

### PR DESCRIPTION
**Pull request by knizhnik**
refer #1521

### CODE REVIEW

**Review by lubennikovaav — COMMENTED** [review]
Looks good to me. Please add a comment to this new code.

**Comment by knizhnik** [comment]
> Looks good to me. Please add a comment to this new code.

Done

**Review by hlinnaka — APPROVED** [review]

**Review by hlinnaka — COMMENTED** [review]
On second thoughts, I think it would be better to do this check in the caller, in `LayeredTimeline::get_reconstruct_data`. `get_value_reconstruct_data` takes an LSN-range as argument. If there is a cached page image at some LSN, the caller should provide that as the floor of the LSN range.

**Comment by knizhnik** [comment]
> On second thoughts, I think it would be better to do this check in the caller, in `LayeredTimeline::get_reconstruct_data`. `get_value_reconstruct_data` takes an LSN-range as argument. If there is a cached page image at some LSN, the caller should provide that as the floor of the LSN range.

Makes sense. Should I change it, or you prefer to do it yourself?

**Comment by knizhnik** [comment]
> > On second thoughts, I think it would be better to do this check in the caller, in `LayeredTimeline::get_reconstruct_data`. `get_value_reconstruct_data` takes an LSN-range as argument. If there is a cached page image at some LSN, the caller should provide that as the floor of the LSN range.
> 
> Makes sense. Should I change it, or you prefer to do it yourself?

Actually it requires much more refectoring. get_value_reconstruct_data is already given LSN range. If we just update low boundary as min(layer.start, cached_image.lsn+1)  then ... inmem_layer will not work, because it can not distinguish situation when wal records a not found at and when cached image LSN equals to LSN of last WAL record.
We can pass cached image LSN as separate parameters. It  allows to move match from `get_value_reconstruct_data` to `get_reconstruct_data`.  But in principle it is just an optimization which I do not think will have any impact on performance.

**Comment by hlinnaka** [comment]
> Actually it requires much more refectoring. get_value_reconstruct_data is already given LSN range. If we just update low boundary as min(layer.start, cached_image.lsn+1) then ... inmem_layer will not work, because it can not distinguish situation when wal records a not found at and when cached image LSN equals to LSN of last WAL record.

Hmm, I'm not sure I understand. Why does `inmem_layer.rs` need to distinguish between those cases? There's a snippet of code currently in `InMemoryLayer::get_value_reconstruct_data` that checks for a cached page, but that should be removed as part of this refactoring.

**Comment by knizhnik** [comment]
> > Actually it requires much more refectoring. get_value_reconstruct_data is already given LSN range. If we just update low boundary as min(layer.start, cached_image.lsn+1) then ... inmem_layer will not work, because it can not distinguish situation when wal records a not found at and when cached image LSN equals to LSN of last WAL record.
> 
> Hmm, I'm not sure I understand. Why does `inmem_layer.rs` need to distinguish between those cases? There's a snippet of code currently in `InMemoryLayer::get_value_reconstruct_data` that checks for a cached page, but that should be removed as part of this refactoring.

Sorry, I do not understand your proposal. Actually after some thinking I do not see any advantages comparing with current fix.
So `get_value_reconstruct_data`is given LSN range. Low boundary is inclusive.
But we need to stop if we found record with image LSN. So this LSN is exclusive.  I do not know how to combine them rather than pass as separate parameter (i.e. cached_image_lsn: Option<Lsn>). But is there any advantage comparing with
`match &reconstruct_state.img` ? So if you do not like my fix, please propose your own.

**Comment by hlinnaka** [comment]
> > > Actually it requires much more refectoring. get_value_reconstruct_data is already given LSN range. If we just update low boundary as min(layer.start, cached_image.lsn+1) then ... inmem_layer will not work, because it can not distinguish situation when wal records a not found at and when cached image LSN equals to LSN of last WAL record.
> > 
> > 
> > Hmm, I'm not sure I understand. Why does `inmem_layer.rs` need to distinguish between those cases? There's a snippet of code currently in `InMemoryLayer::get_value_reconstruct_data` that checks for a cached page, but that should be removed as part of this refactoring.
> 
> Sorry, I do not understand your proposal. Actually after some thinking I do not see any advantages comparing with current fix. So `get_value_reconstruct_data`is given LSN range. Low boundary is inclusive. But we need to stop if we found record with image LSN. So this LSN is exclusive. I do not know how to combine them rather than pass as separate parameter (i.e. cached_image_lsn: Option). But is there any advantage comparing with `match &reconstruct_state.img` ? So if you do not like my fix, please propose your own.

Ok, fair enough. I wrote up what I had in mind here: https://github.com/neondatabase/neon/tree/fix-materialized-page-caching. What do you think?

**Comment by knizhnik** [comment]
Well, you patch seems to be more natural, but also more complex:
instead of checking entry_lsn in two layers, you have to calculate max in three places + add extra  check at top of loop.

The main problem is that it is not working. The patch itself is correct but the problem is most likely related with page cache eviction algorithm. It is certainly separate topic. But...

I changed page cache size to 2Gb and run pgbench -i -s 100. It produce database with size ~1.7Gb. Then I perform `select sum(abalance) from pgbench_accounts`.
Zero page cache hits! Then I set [age cache size to 8Gb, size of pageserver process is increased to 9GB and ...
```
wal_redo_time_count(delta):  148702
materialize_page_cache_hits(delta): 17481
number of pages in pgbench_accounts: 165290
query execution time: 11889,726 ms
```

So despite to more than enough page cache size, ratio of cache hits/misses is very small and as a result time of query execution is twice larger than with sparated caches.

**Comment by hlinnaka** [comment]
> Well, you patch seems to be more natural, but also more complex: instead of checking entry_lsn in two layers, you have to calculate max in three places + add extra check at top of loop.

I created a new PR https://github.com/neondatabase/neon/pull/1545 for this version.

> The main problem is that it is not working. The patch itself is correct but the problem is most likely related with page cache eviction algorithm. It is certainly separate topic. But...
>
> I changed page cache size to 2Gb and run pgbench -i -s 100. It produce database with size ~1.7Gb. Then I perform `select sum(abalance) from pgbench_accounts`. Zero page cache hits! 

That's not very surprising. If you do a seqscan, it will blow away the cached materialized pages before they are used. Even though 2 GB would in theory be enough to hold the dataset in cache, we use the same cache for different things, not just for the materialized pages, so it's not quite large enough.

The cache replacement algorithm is surely not optimal, and we could e.g. detect a sequential scan pattern and avoid "polluting" the cache with pages that are almost certainly not going to be requested again. But at the end of the day, unless the cache is large enough to hold the whole dataset, there's no guarantee that it's useful. I'm all ears for a better cache replacement algorithm. It's tricky to measure though, because if you use the cache more aggressively for one purpose, you might speed up one scenario but slow down others. It's easy to "overfit" for a particular test scenario. I'm sure there's some obvious low-hanging fruit there, though, like putting the pages for a dropped ephemeral file to a free list that you mentioned somewhere.

**Comment by hlinnaka** [comment]
https://github.com/neondatabase/neon/pull/1545 was pushed, this is obsolete, closing.

(The issue with poor cache replacement policy remains, but that's a separate issue)

**Pull request closed without merging**
