### PR TITLE
Do not assign page LSN to new (uninitialized) page in ClearVisibilityMapFlags redo handler

### PR DESCRIPTION
**Pull request by knizhnik**
## Problem

https://neondb.slack.com/archives/C04DGM6SMTM/p1727872045252899

See https://github.com/neondatabase/neon/issues/9240

## Summary of changes

Add `!page_is_new` check before assigning page lsn.

## Checklist before requesting a review

- [ ] I have performed a self-review of my code.
- [ ] If it is a core feature, I have added thorough tests.
- [ ] Do we need to implement analytics? if so did you add the relevant metrics to the dashboard?
- [ ] If this PR requires public announcement, mark it with /release-notes label and add several sentences in this section.

## Checklist before merging

- [ ] Do not forget to reformat commit message to not include the above checklist

### CODE REVIEW

**Comment by hlinnaka** [comment]
Please describe the issue in the PR description, not just a link to slack.

Please add a test case.

**Comment by knizhnik** [comment]
> Please describe the issue in the PR description, not just a link to slack.

Done

> 
> Please add a test case.

The problem is non-deterministically reproduced with test_pg_regress.
I failed to create deterministic repro test for it because it requires several conditions:
1. Relation truncation by vacuum
2. Marking page as all visible
3. Clear all visible flag
4. Swap out VM from shared buffers to force it reload from PS at proper moment.

I know that it is not good to create PR without test, but this PR is doing some obvious fix: do not set LSN for zero page (as it is done in all other places of Postgres. I am not sure that it has to be explicitly tested.

Also pleased notice that original problem is fixed by PR https://github.com/neondatabase/neon/pull/9342

**Comment by hlinnaka** [comment]
> > Please add a test case.
> 
> The problem is non-deterministically reproduced with test_pg_regress. I failed to create deterministic repro test for it because it requires several conditions:
> 
>     1. Relation truncation by vacuum
> 
>     2. Marking page as all visible
> 
>     3. Clear all visible flag
> 
>     4. Swap out VM from shared buffers to force it reload from PS at proper moment.
> 
> 
> I know that it is not good to create PR without test, but this PR is doing some obvious fix: do not set LSN for zero page (as it is done in all other places of Postgres. I am not sure that it has to be explicitly tested.

I would nevertheless really like to see a test case.

**Review by skyzh — APPROVED** [review]

**Comment by skyzh** [comment]
+1 for having a test case :)

**Pull request merged**
