### PR TITLE
safekeeper: use arc for global timelines and config

### PR DESCRIPTION
**Pull request by oldmanfleming**
Hello! I was interested in potentially making some contributions to Neon and looking through the issue backlog I found [8200](https://github.com/neondatabase/neon/issues/8200) which seemed like a good first issue to attempt to tackle. I see it was assigned a while ago so apologies if I'm stepping on any toes with this PR. I also apologize for the size of this PR. I'm not sure if there is a simple way to reduce it given the footprint of the components being changed.

## Problem
This PR is attempting to address part of the problem outlined in issue [8200](https://github.com/neondatabase/neon/issues/8200). Namely to remove global static usage of timeline state in favour of `Arc<GlobalTimelines>` and to replace wasteful clones of `SafeKeeperConf` with `Arc<SafeKeeperConf>`. I did not opt to tackle `RemoteStorage` in this PR to minimize the amount of changes as this PR is already quite large. I also did not opt to introduce an `SafekeeperApp` wrapper struct to similarly minimize changes but I can tackle either or both of these omissions in this PR if folks would like. 

## Summary of changes
- Remove static usage of `GlobalTimelines` in favour of `Arc<GlobalTimelines>`
- Wrap `SafeKeeperConf` in `Arc` to avoid wasteful clones of the underlying struct

## Some additional thoughts
- We seem to currently store `SafeKeeperConf` in `GlobalTimelines` and then expose it through a public`get_global_config` function which requires locking. This seems needlessly wasteful and based on observed usage we could remove this public accessor and force consumers to acquire `SafeKeeperConf` through the new Arc reference.

### CODE REVIEW

**Review by arpad-m — APPROVED** [review]
LGTM, cc @arssher just to make sure

**Comment by arpad-m** [comment]
status: blocked on #10059. @oldmanfleming after it merged, could you merge main? (better not a rebase as we merge with squash anyways)

**Comment by oldmanfleming** [comment]
@arpad-m Thanks for the review! [#10059](https://github.com/neondatabase/neon/pull/10059) is merged and I merged main to this branch. Let me know if I messed something up with the merging

**Comment by arpad-m** [comment]
@oldmanfleming thanks for merging latest main. I will give some time for @arssher and @petuhovskiy to give it a look as they are more familiar with the code than I am, but it looks good from my point of view. Definitely an improvement.

**Review by petuhovskiy — APPROVED** [review]
Very cool, thank you @oldmanfleming!

@arpad-m can you run the CI and merge this?

**Comment by arpad-m** [comment]
Merged, thanks again.

**Comment by oldmanfleming** [comment]
@arpad-m No problemo 😄

**Pull request merged**
