### PR TITLE
Create CHANGELOG.md

### PR DESCRIPTION
**Pull request by danieltprice**
**Proposal for adding a CHANAGELOG.md file**
This PR creates a changelog document for the neon repository. The purpose is to move developer-oriented content out of the [Neon Release Notes](https://neon.tech/docs/release-notes), which will become more user-oriented and focused on benefits and usage of the new features or changes.

The initial changelog content that you see in this PR was moved over from the Neon Release Notes. Expect the changelog content for future releases to differ as it becomes more technical in nature, written for developers as the primary audience.

### CODE REVIEW

**Review by koivunej — COMMENTED** [review]
I am +1 for the changelog but the question of "how are we going to make changes to it" still remain.

What I think works usually is that every PR will change the CHANGELOG.md. However, that does come with the downside of every PR conflicting on the CHANGELOG.md.

I know that there are other solutions, like `ponylang/ponyc` having a sophisticated per PR release notes markdown file, which then get collected to release notes and the changelog part is automated by the use of github releases.

**Comment by danieltprice** [comment]
> I am +1 for the changelog but the question of "how are we going to make changes to it" still remain.

I was looking at Conventional Commits as a possibility for automating the process. It would require applying a convention to commit messages. I'd be interested to know if this is something the team would consider adopting.
https://www.conventionalcommits.org/en/v1.0.0/
https://gist.github.com/mkg0/864e1115d966a2300c555aa73cb9c8bf
https://medium.com/neudesic-innovation/conventional-commits-a-better-way-78d6785c2e08
https://blog.zhanganzhi.com/en/2022/06/ca740262a99f/

**Comment by lubennikovaav** [comment]
maybe we can update it not with every commit, but once a week, when neon release happens? as we do with Release notes now.

It shouldn't be as detailed as git log anyways.

**Comment by danieltprice** [comment]
we're reporting it slack now.

**Pull request closed without merging**
