### PR TITLE
Set application_name for internal connections to computes

### PR DESCRIPTION
**Pull request by tristan957**
This will help when analyzing the origins of connections to a compute like in [0].

[0]: https://github.com/neondatabase/cloud/issues/14247

### CODE REVIEW

**Comment by tristan957** [comment]
Is anyone aware of any other places we might be creating internal connections?

**Comment by tristan957** [comment]
Would it be useful to add a `neon/` prefix for these application names? Could help create better SQL queries.

**Comment by save-buffer** [comment]
We create connections in compute_ctl. We have a monitor that connects every so often

**Comment by sharnoff** [comment]
We should also set the application name for vm-monitor connections:

https://github.com/neondatabase/neon/blob/d25f7e3dd575878df49925bead4c797a61757751/compute_tools/src/bin/compute_ctl.rs#L734-L741

**Review by sharnoff — APPROVED** [review]

**Pull request merged**
