### PR TITLE
pageserver: faster and simpler inmem layer vec read

### PR DESCRIPTION
**Pull request by VladLazar**
## Problem
The in-memory layer vectored read was very slow in some conditions (walingest::test_large_rel) test. Upon profiling, I realised that 80% of the time was spent building up the binary heap of reads. This stage isn't actually needed.

## Summary of changes
Remove the planning stage as we never took advantage of it in order to merge reads. There should be no functional change from this patch.

## Checklist before requesting a review

- [ ] I have performed a self-review of my code.
- [ ] If it is a core feature, I have added thorough tests.
- [ ] Do we need to implement analytics? if so did you add the relevant metrics to the dashboard?
- [ ] If this PR requires public announcement, mark it with /release-notes label and add several sentences in this section.

## Checklist before merging

- [ ] Do not forget to reformat commit message to not include the above checklist

### CODE REVIEW

**Review by skyzh — APPROVED** [review]
LGTM. Actually I'm wondering why in-memory layer does not really reside in the memory (only the index is in memory) and we need `read_blob` to read from WAL.... This could be something to be optimized in the future.

**Comment by skyzh** [comment]
linking this pull request to related epic https://github.com/neondatabase/neon/issues/8452

**Comment by koivunej** [comment]
Does this allow unskipping the `test_bulk_insert`?

**Comment by VladLazar** [comment]
> Does this allow unskipping the `test_bulk_insert`?

We can try. I don't remember what made bulk insert slow in the first place.

**Comment by VladLazar** [comment]
> Actually I'm wondering why in-memory layer does not really reside in the memory (only the index is in memory) and we need `read_blob` to read from WAL.... 

The name is misleading I agree. Keeping the entire layer in memory is not tractable because we'd use up 256MiB * number of tenants. Of course we could flush early in response to memory pressure, but then we get small layers, etc.

**Pull request merged**
