### PR TITLE
wal_craft: wait for pg to start, longer timeouts

### PR DESCRIPTION
**Pull request by koivunej**
It became unclear on #4093 if the test failures were just flaky or caused by the PR. Looked, found a bit strange rust code caused by `use anyhow::*;`, fixed that and added postmaster.pid wait for 10s, then grew the connect timeout from 1s to 10s.

Fixes (hopefully) #3778.

### CODE REVIEW

**Comment by arssher** [comment]
There is already (a bit weird) 1s retry logic there:
https://github.com/neondatabase/neon/blob/fca25edae8aea52c764093d0f7677c11f66a7609/libs/postgres_ffi/wal_craft/src/lib.rs#L124
https://github.com/neondatabase/neon/blob/fca25edae8aea52c764093d0f7677c11f66a7609/libs/postgres_ffi/wal_craft/src/lib.rs#L158

We could increase it, but I'm not immediately sure this is the problem. Would be nice to get pg logs on failure to check.

Also not sure what explicit anyhow:: fixes.

**Comment by arssher** [comment]
So let's try
https://github.com/neondatabase/neon/pull/4102

**Comment by arssher** [comment]
- It is important to have stdout logging as in https://github.com/neondatabase/neon/pull/4102 or we don't have PG logs in CI otherwise.
- I find redundant to have two layers of waiting for connection is this already convoluted code, so I'm fine one line change in my PR.
- I don't mind waiting for pid check, but this also seems redundant to me, just timeout + logs will do.
- I don't mind anyhow or other rusty fixes here, though I still don't understand "because Ok gets shadowed and no one expects that."

So would you finish it here, merging PRs?

**Comment by arssher** [comment]
BTW if you are going read PID file (which is not needed IMV), you have to check for 'ready' status:
https://pgpedia.info/p/postmaster-pid.html

**Comment by koivunej** [comment]
So basically last line? Can add that as well if you think it's necessary. Can also drop the pidfile checking.

**Comment by arssher** [comment]
No, I rather propose to make a PR of 1) logging to stout 2) increasing timeout like in my patch 3) your rusty fixes, and omit the rest.

**Comment by koivunej** [comment]
Oki if we want to do split PRs I guess I'll just approve yours and let this shrink into refactoring PR, maybe we don't really need the postmaster.pid with 10s connection timeout. I can't see why we would get any other startup error there because of domain sockets are being used and so on.

**Comment by koivunej** [comment]
We merged arsenys PR, let's close this to avoid all of the discussion and I'll open a new one for the refactorings in this PR without the postmaster.pid polling.

**Pull request closed without merging**
