### PR TITLE
Compile postgres with ICU support

### PR DESCRIPTION
**Pull request by vadim2404**
I saw requests about this

### CODE REVIEW

**Review by kelvich — APPROVED** [review]
Looks good, thank you!

**Comment by kelvich** [comment]
Yes, it will work, but IIUC won't be default unless explicitly specified. Would be good to make it default too. But that may be a different PR.

**Comment by vadim2404** [comment]
At this moment, after `initdb` `en_US.utf-8` will be used for newly created db (because of env var).

I want to test the whole cycle on staging. Most probably, it requires steps you mentioned:)

**Comment by koivunej** [comment]
> At this moment, after initdb en_US.utf-8 will be used for newly created db (because of env var).

If I understand this comment correctly, this will change how initdb's work. Could this introduce some compatibility issues with timelines created before this PR, given the non-reproducable nature of initdb_lsns #2592?

**Comment by vadim2404** [comment]
> > At this moment, after initdb en_US.utf-8 will be used for newly created db (because of env var).
> 
> If I understand this comment correctly, this will change how initdb's work. Could this introduce some compatibility issues with timelines created before this PR, given the non-reproducable nature of initdb_lsns #2592?

Therefore I want to merge this PR after the next release to test these cases. 

Even at this moment, our databases have UTF-8

```
neondb=> select datname, pg_encoding_to_char(encoding) from pg_database;
  datname  | pg_encoding_to_char
-----------+---------------------
 postgres  | UTF8
 template1 | UTF8
 template0 | UTF8
 neondb    | UTF8
```

**Pull request merged**
