### PR TITLE
Refactor LayerMap::search to also search open and frozen layers.

### PR DESCRIPTION
**Pull request by hlinnaka**
Builds on top of https://github.com/neondatabase/neon/pull/3259

---

This allows refactoring in get_reconstruct_data() which is needed by PR #3228. That PR turns some functions async, and you cannot hold a RwLock over 'await'. And it's enough to "drop(guard)" the lock guard, it has to actually go out-of-scope to placate the compiler. This refactoring allows dropping the lock on 'layers' at end of scope.

### CODE REVIEW

**Comment by hlinnaka** [comment]
I wish we didn't need to introduce the InMemoryOrHistoricLayer struct for this. I wish it could be just Arc<dyn Layer>. But I couldn't make the compiler happy with that. If some a Rust expert can make that work, I would be very happy.

**Comment by SomeoneToIgnore** [comment]
> I wish we didn't need to introduce the InMemoryOrHistoricLayer struct for this. I wish it could be just Arc. 

Why? Rust will hurt you if you simultaneously
* try to use traits as interfaces
* change and refactor your code a lot
More elaborated version could be found https://neondb.slack.com/archives/C0277TKAJCA/p1672305471016349?thread_ts=1672245908.989789&cid=C0277TKAJCA

Here's the PR that makes first steps along the static dispatch idea https://github.com/neondatabase/neon/pull/3261 wdyt?

**Comment by problame** [comment]
I don't get why this PR, or @SomeoneToIgnore 's alternative, is necessary for `RequestContext`.
IIUC, what the RequestContext needs is to do .await the download, and we can't hold the layer map lock while doing that. Why?
1. Can't hold sync mutex guard across .await
2. Download modifies the layer map, so, if we hold it while downloading, we'll deadlock.

But, we know that we don't have to issue a download for Open & InMemory layer.
Only the historic layers can be RemoteLayer.
So, why don't we leave LayerMap::search as is (search just historic layers) and do what needs to be done in timeline.rs to drop the mutex before the download?

---

This is not a vote against #3261 . But I think we don't need it for RequestContext either.

**Comment by SomeoneToIgnore** [comment]
I don't think it's necessary either, I tried to object against the general direction here.

**Review by SomeoneToIgnore — APPROVED** [review]
Meanwhile, we would want to merge the big PR, so let's continue?
Apart from "odd approach" (that will be handled by https://github.com/neondatabase/neon/pull/3263) , LGTM.

**Comment by hlinnaka** [comment]
> I don't get why this PR, or @SomeoneToIgnore 's alternative #3261 , is necessary for `RequestContext`. IIUC, what the RequestContext needs is to do .await the download, and we can't hold the layer map lock while doing that. Why?
> 
>     1. Can't hold sync mutex guard across .await
> 
>     2. Download modifies the layer map, so, if we hold it while downloading, we'll deadlock.
> 
> 
> But, we know that we don't have to issue a download for Open & InMemory layer. Only the historic layers can be RemoteLayer. So, why don't we leave LayerMap::search as is (search just historic layers) and do what needs to be done in timeline.rs to drop the mutex before the download?
> 
> This is not a vote against #3261 . But I think we don't need it for RequestContext either.

Yeah, I'm sure you could do it differently. Introducing a new InMemoryOrHistoricLayer enum felt like the simplest way, however. And that led to these bigger changes.

**Comment by problame** [comment]
I'd prefer if we implement RequestContext without introducing `InMemoryOrHistoricLayer`. It clutters the history and is really an orthogonal change.
If it's easy to take out here, please do so.

I won't die on that hill, though.

**Comment by LizardWizzard** [comment]
As discussed moving to draft

**Comment by LizardWizzard** [comment]
Removing myself as a reviewer for now. Feel free to re request when this is ready

**Pull request closed without merging**
