### PR TITLE
Fix ancestor layer traversal (#1484)

### PR DESCRIPTION
**Pull request by dhammika**
Signed-off-by: Dhammika Pathirana <dhammika@gmail.com>

### CODE REVIEW

**Review by hlinnaka — COMMENTED** [review]
Thanks, looks good to me. I broke this in commit 07342f751902b06b253847065f24ddca735e00b3.

Could you write a test case for this, please? I'm a bit surprised this wasn't caught by existing tests. You need a branch of a branch to trigger it, I guess.

**Comment by dhammika** [comment]
> Thanks, looks good to me. I broke this in commit [07342f7](https://github.com/neondatabase/neon/commit/07342f751902b06b253847065f24ddca735e00b3).
> 
> Could you write a test case for this, please? I'm a bit surprised this wasn't caught by existing tests. You need a branch of a branch to trigger it, I guess.

This was tripping #1484 and that test includes compaction splits. Probably don't see this in regular tests because of default compaction_distance and gc interval.

**Comment by hlinnaka** [comment]
> > Thanks, looks good to me. I broke this in commit [07342f7](https://github.com/neondatabase/neon/commit/07342f751902b06b253847065f24ddca735e00b3).
> > Could you write a test case for this, please? I'm a bit surprised this wasn't caught by existing tests. You need a branch of a branch to trigger it, I guess.
> 
> This was tripping #1484 and that test includes compaction splits. Probably don't see this in regular tests because of default compaction_distance and gc interval.

Hmm, I don't think compaction & GC should affect this. Maybe I'm missing something. And I'm a bit surprised that test triggered this, AFAICS you would need to have a branch of a branch to be affected. I guess many of our tests actually do create a branch of a branch, as they first create 'empty' branch, and then the test branch from the empty branch. So the hierarchy is 'main <- empty <- [test branch]'. I think it'd be good to have a more explicit test case for a branch of a branch.

**Comment by dhammika** [comment]
> 
> Hmm, I don't think compaction & GC should affect this. Maybe I'm missing something. And I'm a bit surprised that test triggered this, AFAICS you would need to have a branch of a branch to be affected. I guess many of our tests actually do create a branch of a branch, as they first create 'empty' branch, and then the test branch from the empty branch. So the hierarchy is 'main <- empty <- [test branch]'. I think it'd be good to have a more explicit test case for a branch of a branch.

Sure, I'll add a test to instrument this case. There are some tests that create grand-parent branches but I'm not quite sure why we don't hit this.

**Review by lubennikovaav — APPROVED** [review]
Thank you for fixing this.

It seems that my [test](https://app.circleci.com/pipelines/github/neondatabase/neon/5722/workflows/449fd0c5-9490-4c05-b2dc-801b689d2ee4/jobs/55817/tests) caught this error too

I wonder, if this bug is a core reason of the #1433 issue ?

**Comment by dhammika** [comment]
> Thank you for fixing this.
> 
> It seems that my [test](https://app.circleci.com/pipelines/github/neondatabase/neon/5722/workflows/449fd0c5-9490-4c05-b2dc-801b689d2ee4/jobs/55817/tests) caught this error too
> 
> I wonder, if this bug is a core reason of the #1433 issue ?

:+1: Does look like it's same issue. It's subtle and hard to repro.

**Comment by dhammika** [comment]
> > Thank you for fixing this.
> > It seems that my [test](https://app.circleci.com/pipelines/github/neondatabase/neon/5722/workflows/449fd0c5-9490-4c05-b2dc-801b689d2ee4/jobs/55817/tests) caught this error too
> > I wonder, if this bug is a core reason of the #1433 issue ?
> 
> +1 Does look like it's same issue. It's subtle and hard to repro.

Actually on second look I think it's a different issue. This is from 3 levels or more branching and page lookup getting _stuck_ in immediate ancestor branch.

**Comment by hlinnaka** [comment]
Both new tests - the unit test and the python test - are passing even without the code change.

**Comment by dhammika** [comment]
> Both new tests - the unit test and the python test - are passing even without the code change.

Ya, that's correct. 
This is because without compaction layer map search always return a image layer match here, 
https://github.com/neondatabase/neon/blob/867aede71516756ff0ec1dba540fe7fc23bb7113/pageserver/src/layered_repository.rs#L1458
but with compaction, key-range mismatch trigger layer map search failures. I haven't figured out a layer setup just right to trip it in tests :)

**Comment by dhammika** [comment]
@hlinnaka fixed pytest to reproduce it. What do you think?

**Pull request merged**
