### PR TITLE
Remove dead code from walproposer_utils.c

### PR DESCRIPTION
**Pull request by petuhovskiy**
This code occupies space in `walproposer_utils.c` without providing any benefit for neon compute.

### CODE REVIEW

**Comment by save-buffer** [comment]
I don't have much context into this, but what changed that made this code obsolete?

**Comment by petuhovskiy** [comment]
Nothing has changed, that code was left after refactoring neon extension code out of postgres repo. This code was mostly copied from walsender.c and AFAIU the main idea was that in theory it will be used in the future. But right now I see that deleting it doesn't break anything, so it's better to remove unused parts.

**Comment by hlinnaka** [comment]
I think the idea was to keep it similar to walsender.c, so that we can easily copy-paste future upstream changes to walsender.c to waproposer_utils.c, too. I agree that if we can rid of this much code, it's probably better to remove it even if it makes it look more different from walsender.c.

**Review by save-buffer — APPROVED** [review]
Well if CI passes and Heikki agrees, I see no reason not to approve and merge

**Review by hlinnaka — APPROVED** [review]

**Pull request merged**
