### PR TITLE
Add a new benchmark data series for prefetching.

### PR DESCRIPTION
**Pull request by hlinnaka**
Also run benchmarks with the seqscan prefetching (commit f44afbaf62) enabled.

### CODE REVIEW

**Comment by hlinnaka** [comment]
@bayandin does this look sane to you? I also wanted to rename the 'neon-captest' benchmark to 'neon-captest-old', but I was afraid that would break the continuity of the data series.

**Comment by hlinnaka** [comment]
Is there a way to manually trigger the workflow manually, or do we  need to wait for the cron schedule to trigger it? Could we run the benchmarks more frequently?

**Comment by bayandin** [comment]
> Is there a way to manually trigger the workflow manually, or do we need to wait for the cron schedule to trigger it? Could we run the benchmarks more frequently?

- open an action workflow page: https://github.com/neondatabase/neon/actions/workflows/benchmarking.yml
- Click "Run workflow"
- In a popup, you can choose your branch

**Comment by bayandin** [comment]
> @bayandin does this look sane to you?

Yep, it makes sense!

> I also wanted to rename the 'neon-captest' benchmark to 'neon-captest-old', but I was afraid that would break the continuity of the data series.

No problem, you can rename it, and I'll update the data in the DB.

**Review by bayandin — APPROVED** [review]

**Comment by bayandin** [comment]
> Is there a way to manually trigger the workflow manually

I forgot to mention that these results won't be published (i.e. won't be visible in Grafana). I created a PR to fix it some time ago: https://github.com/neondatabase/neon/pull/2440 (but didn't get a chance to come back to it and answer a question)

**Pull request merged**
