### PR TITLE
task_mgr::spawn: require a `TenantId`

### PR DESCRIPTION
**Pull request by problame**
… to dis-incentivize global tasks via task_mgr in the future

(As of https://github.com/neondatabase/neon/pull/8339 all remaining task_mgr usage is tenant or timeline scoped.)

### CODE REVIEW

**Review by koivunej — COMMENTED** [review]
Let's merge this *after* merging https://github.com/neondatabase/neon/pull/8706 but yeah this seems sensible.

**Review by koivunej — APPROVED** [review]
Whatever, I'll handle the conflict, I got some new more interesting test failures.

**Comment by problame** [comment]
Test failure due to https://github.com/neondatabase/neon/issues/8710

**Comment by problame** [comment]
Test flakiness https://github.com/neondatabase/neon/issues/8766

**Pull request merged**
