### PR TITLE
fix superuser permission check for extensions

### PR DESCRIPTION
**Pull request by skyzh**
## Summary of changes

close https://github.com/neondatabase/neon/issues/6236

This pull request bumps neon postgres dependencies. The corresponding postgres commits fix the checks for superuser permission when creating an extension. Also, for creating native functinos, it now allows neon_superuser only in the extension creation process.

## Checklist before requesting a review

- [x] I have performed a self-review of my code.
- [ ] If it is a core feature, I have added thorough tests.
- [ ] Do we need to implement analytics? if so did you add the relevant metrics to the dashboard?
- [ ] If this PR requires public announcement, mark it with /release-notes label and add several sentences in this section.

## Checklist before merging

- [ ] Do not forget to reformat commit message to not include the above checklist

### CODE REVIEW

**Review by save-buffer — APPROVED** [review]

**Review by knizhnik — COMMENTED** [review]
I wonder if you were able to build this PR:
`is_neon_superuser()` function is defined only for PG16.

As far as I remember it is not the first time `is_neon_superuser()` function is used.
So I expect that there will be multiple places when we allow something not only for true superuser, but also to `neon_cloud_admin`. May be then have just one function for it?
It can be `is_neon_superuser()` function itself which will return true also in case of user with admin role (superuser).

**Comment by save-buffer** [comment]
We have `is_neon_superuser` in all versions of PG

**Comment by knizhnik** [comment]
> We have `is_neon_superuser` in all versions of PG

File diff of this PR adds definition of `is_neon_superuser` in src/backend/utils/adt/acl.c for PG16.
So either it should be added to all PG version, either this definition is not needed here.
But it is very suspicious that PG16 requires more changes than other versions of Postgres.

**Comment by save-buffer** [comment]
is_neon_superuser was added at the same time to all versions for publications. Then it was moved in PG14 and PG15 because those versions needed a similar check in subscriptions, but PG16 didn't. So this file diff moves the definition in PG16 to the same place as in 14 and 15.

**Comment by skyzh** [comment]
I did a global search yesterday on where `is_superuser` is used and I saw there are only a few of them. I can revisit all places that Postgres uses `is_superuser` and see if we need to add `is_neon_superuser` along with them later to avoid future problems. For now, I'd merge this pull request first so that the extension issue gets resolved. Thanks for the reviews!

**Comment by skyzh** [comment]
the pull request does not work for native extensions...

```
psql:tests/sql/neon_pg_stat_statements.sql:2: NOTICE:  extension "pg_stat_statements" does not exist, skipping
psql:tests/sql/neon_pg_stat_statements.sql:4: ERROR:  permission denied for language c
psql:tests/sql/neon_pg_stat_statements.sql:7: ERROR:  relation "pg_stat_statements" does not exist
LINE 1: select count(*) from pg_stat_statements where query = 'selec...
                             ^
psql:tests/sql/neon_pg_stat_statements.sql:8: ERROR:  function pg_stat_statements_reset() does not exist
LINE 1: select pg_stat_statements_reset();
               ^
HINT:  No function matches the given name and argument types. You might need to add explicit type casts.
psql:tests/sql/neon_pg_stat_statements.sql:10: ERROR:  relation "pg_stat_statements" does not exist
LINE 1: select count(*) from pg_stat_statements where query = 'selec...
                             ^
psql:tests/sql/neon_pg_stat_statements.sql:14: ERROR:  relation "pg_stat_statements" does not exist
LINE 1: select count(*) from pg_stat_statements where query = 'selec...
                             ^
psql:tests/sql/neon_pg_stat_statements.sql:16: ERROR:  relation "pg_stat_statements" does not exist
LINE 1: ...LECT pg_stat_statements_reset(0,0,s.queryid) FROM pg_stat_st...
                                                             ^
psql:tests/sql/neon_pg_stat_statements.sql:18: ERROR:  relation "pg_stat_statements" does not exist
LINE 1: select count(*) from pg_stat_statements where query = 'selec...
                             ^
psql:tests/sql/neon_pg_stat_statements.sql:24: ERROR:  extension "pg_stat_statements" does not exist
psql:tests/sql/neon_pg_stat_statements.sql:26: ERROR:  permission denied for language c
psql:tests/sql/neon_pg_stat_statements.sql:29: ERROR:  function pg_stat_statements_reset() does not exist
LINE 1: select pg_stat_statements_reset();
               ^
HINT:  No function matches the given name and argument types. You might need to add explicit type casts.
psql:tests/sql/neon_pg_stat_statements.sql:31: ERROR:  relation "pg_stat_statements" does not exist
LINE 1: select count(*) from pg_stat_statements where query = 'selec...
                             ^
psql:tests/sql/neon_pg_stat_statements.sql:32: ERROR:  extension "pg_stat_statements" does not exist
psql:tests/sql/neon_pg_stat_statements.sql:33: ERROR:  permission denied for language c
psql:tests/sql/neon_pg_stat_statements.sql:36: ERROR:  function pg_stat_statements_reset() does not exist
LINE 1: select pg_stat_statements_reset();
               ^
HINT:  No function matches the given name and argument types. You might need to add explicit type casts.
psql:tests/sql/neon_pg_stat_statements.sql:38: ERROR:  relation "pg_stat_statements" does not exist
LINE 1: select count(*) from pg_stat_statements where query = 'selec...
                             ^
psql:tests/sql/neon_pg_stat_statements.sql:39: ERROR:  extension "pg_stat_statements" does not exist
psql:tests/sql/neon_pg_stat_statements.sql:40: ERROR:  permission denied for language c
psql:tests/sql/neon_pg_stat_statements.sql:43: ERROR:  function pg_stat_statements_reset() does not exist
LINE 1: select pg_stat_statements_reset();
               ^
HINT:  No function matches the given name and argument types. You might need to add explicit type casts.
psql:tests/sql/neon_pg_stat_statements.sql:45: ERROR:  relation "pg_stat_statements" does not exist
LINE 1: select count(*) from pg_stat_statements where query = 'selec...
                             ^
psql:tests/sql/neon_pg_stat_statements.sql:46: ERROR:  extension "pg_stat_statements" does not exist
psql:tests/sql/neon_pg_stat_statements.sql:47: ERROR:  permission denied for language c
psql:tests/sql/neon_pg_stat_statements.sql:50: ERROR:  function pg_stat_statements_reset() does not exist
LINE 1: select pg_stat_statements_reset();
               ^
HINT:  No function matches the given name and argument types. You might need to add explicit type casts.
psql:tests/sql/neon_pg_stat_statements.sql:52: ERROR:  relation "pg_stat_statements" does not exist
LINE 1: select count(*) from pg_stat_statements where query = 'selec...
                             ^
psql:tests/sql/neon_pg_stat_statements.sql:53: ERROR:  extension "pg_stat_statements" does not exist
psql:tests/sql/neon_pg_stat_statements.sql:54: ERROR:  permission denied for language c
psql:tests/sql/neon_pg_stat_statements.sql:57: ERROR:  function pg_stat_statements_reset() does not exist
LINE 1: select pg_stat_statements_reset();
               ^
HINT:  No function matches the given name and argument types. You might need to add explicit type casts.
psql:tests/sql/neon_pg_stat_statements.sql:59: ERROR:  relation "pg_stat_statements" does not exist
LINE 1: select count(*) from pg_stat_statements where query = 'selec...
                             ^
psql:tests/sql/neon_pg_stat_statements.sql:60: ERROR:  extension "pg_stat_statements" does not exist
psql:tests/sql/neon_pg_stat_statements.sql:61: ERROR:  permission denied for language c
psql:tests/sql/neon_pg_stat_statements.sql:64: ERROR:  function pg_stat_statements_reset() does not exist
LINE 1: select pg_stat_statements_reset();
               ^
HINT:  No function matches the given name and argument types. You might need to add explicit type casts.
psql:tests/sql/neon_pg_stat_statements.sql:66: ERROR:  relation "pg_stat_statements" does not exist
LINE 1: select count(*) from pg_stat_statements where query = 'selec...
                             ^
psql:tests/sql/neon_pg_stat_statements.sql:67: ERROR:  extension "pg_stat_statements" does not exist
psql:tests/sql/neon_pg_stat_statements.sql:69: ERROR:  permission denied for language c
psql:tests/sql/neon_pg_stat_statements.sql:71: ERROR:  function pg_stat_statements_reset() does not exist
LINE 1: select pg_stat_statements_reset();
               ^
HINT:  No function matches the given name and argument types. You might need to add explicit type casts.
psql:tests/sql/neon_pg_stat_statements.sql:73: ERROR:  relation "pg_stat_statements" does not exist
LINE 1: select count(*) from pg_stat_statements where query = 'selec...
                             ^
psql:tests/sql/neon_pg_stat_statements.sql:74: ERROR:  extension "pg_stat_statements" does not exist
psql:tests/sql/neon_pg_stat_statements.sql:77: ERROR:  function pg_stat_statements_reset() does not exist
LINE 1: select pg_stat_statements_reset();
               ^
HINT:  No function matches the given name and argument types. You might need to add explicit type casts.
psql:tests/sql/neon_pg_stat_statements.sql:79: ERROR:  relation "pg_stat_statements" does not exist
LINE 1: select count(*) from pg_stat_statements where query = 'selec...
                             ^
psql:tests/sql/neon_pg_stat_statements.sql:80: ERROR:  extension "pg_stat_statements" does not exist
psql:tests/sql/neon_pg_stat_statements.sql:83: ERROR:  function pg_stat_statements_reset() does not exist
LINE 1: select pg_stat_statements_reset();
               ^
HINT:  No function matches the given name and argument types. You might need to add explicit type casts.
psql:tests/sql/neon_pg_stat_statements.sql:85: ERROR:  relation "pg_stat_statements" does not exist
LINE 1: select count(*) from pg_stat_statements where query = 'selec...
                             ^
psql:tests/sql/neon_pg_stat_statements.sql:86: ERROR:  extension "pg_stat_statements" does not exist
psql:tests/sql/neon_pg_stat_statements.sql:89: ERROR:  function pg_stat_statements_reset() does not exist
LINE 1: select pg_stat_statements_reset();
               ^
HINT:  No function matches the given name and argument types. You might need to add explicit type casts.
psql:tests/sql/neon_pg_stat_statements.sql:91: ERROR:  relation "pg_stat_statements" does not exist
LINE 1: select count(*) from pg_stat_statements where query = 'selec...
                             ^
psql:tests/sql/neon_pg_stat_statements.sql:92: ERROR:  extension "pg_stat_statements" does not exist
psql:tests/sql/neon_pg_stat_statements.sql:95: ERROR:  function pg_stat_statements_reset() does not exist
LINE 1: select pg_stat_statements_reset();
               ^
HINT:  No function matches the given name and argument types. You might need to add explicit type casts.
psql:tests/sql/neon_pg_stat_statements.sql:97: ERROR:  relation "pg_stat_statements" does not exist
LINE 1: select count(*) from pg_stat_statements where query = 'selec...
                             ^
psql:tests/sql/neon_pg_stat_statements.sql:98: ERROR:  extension "pg_stat_statements" does not exist
psql:tests/sql/neon_pg_stat_statements.sql:101: ERROR:  function pg_stat_statements_reset() does not exist
LINE 1: select pg_stat_statements_reset();
               ^
HINT:  No function matches the given name and argument types. You might need to add explicit type casts.
psql:tests/sql/neon_pg_stat_statements.sql:103: ERROR:  relation "pg_stat_statements" does not exist
LINE 1: select count(*) from pg_stat_statements where query = 'selec...
                             ^
psql:tests/sql/neon_pg_stat_statements.sql:104: ERROR:  extension "pg_stat_statements" does not exist
```

guess there are more permission checks we need to fix

**Comment by hlinnaka** [comment]
> Conflict on [a97b54e](https://github.com/neondatabase/neon/commit/a97b54e3b9e692532962d65b89b7e5f67a9c28a4) and the commit Heikki added is not on the REL_XX branch. I could directly add Heikki's commits to the Postgres repo later if it's okay.

Sorry, I forgot to update the REL_XX_STABLE_neon branches. I merged your PRs now to cherry-pick that commit.

**Comment by hlinnaka** [comment]
This broke installation of trusted extensions:

```
neondb=> create extension vector;
ERROR:  must be superuser to create a base type
```

**Comment by save-buffer** [comment]
That's interesting, why did it work before?

**Comment by hlinnaka** [comment]
Let's take a look at `execute_extension_script()`:
```
	/*
	 * Enforce superuser-ness if appropriate.  We postpone these checks until
	 * here so that the control flags are correctly associated with the right
	 * script(s) if they happen to be set in secondary control files.
	 */
	if (control->superuser && !superuser() && !is_neon_superuser())
	{
		if (extension_is_trusted(control))
			switch_to_superuser = true;
		else if (from_version == NULL)
			ereport(ERROR,
					(errcode(ERRCODE_INSUFFICIENT_PRIVILEGE),
					 errmsg("permission denied to create extension \"%s\"",
							control->name),
					 control->trusted
					 ? errhint("Must have CREATE privilege on current database to create this extension.")
					 : errhint("Must be superuser to create this extension.")));
		else
			ereport(ERROR,
					(errcode(ERRCODE_INSUFFICIENT_PRIVILEGE),
					 errmsg("permission denied to update extension \"%s\"",
							control->name),
					 control->trusted
					 ? errhint("Must have CREATE privilege on current database to update this extension.")
					 : errhint("Must be superuser to update this extension.")));
	}
```
This PR added the ` !is_neon_superuser()` condition. That changed things so that if you run this as neon-superuser, switch_to_superuser is not changed to 'true'. Because of that, if the install script performs any actions that require superuser access, it fails. In this case, 'pgvector' tries to create a new base type, which now fails.

**Comment by save-buffer** [comment]
Ohhhhh I missed the switch_to_superuser thing. So perhaps a better way is to change the switch_to_superuser check to 
```
		if (extension_is_trusted(control) || is_neon_superuser())
			switch_to_superuser = true;
```

**Comment by skyzh** [comment]
The reason why us_addr_standarizer fails before is that it hits the `switch_to_superuser` path while it shouldn't? I would suggest still keeping the current condition and allow neon_superuser to create a base type?

**Comment by skyzh** [comment]
My assumptions for neon_superuser is that we created that role to replicate what superuser is and to avoid dangerous permissions allowed by superuser. Creating base type seems like a thing that we should allow for both normal user operations and extensions, so I think I will proceed with allow neon_superuser for creating base type.

**Comment by skyzh** [comment]
Meanwhile I think it would still be useful to switch to superuser (instead of neon_superuser) for all extensions to avoid further issues with all these permission stuff. I probably will need to look into why the permission table entries were not updated if we switch to superuser instead of neon_superuser.

**Comment by hlinnaka** [comment]
> My assumptions for neon_superuser is that we created that role to replicate what superuser is and to avoid dangerous permissions allowed by superuser. Creating base type seems like a thing that we should allow for both normal user operations and extensions, so I think I will proceed with allow neon_superuser for creating base type.

No, it is not secure to allow a regular user to create a new base: If you get the type parameters wrong, you can call a C function with wrong parameter types. Like passing an arbitrary integer as a pointer to a string. That's the reason that you need to be superuser to create base types.

**Comment by skyzh** [comment]
So I guess to fully resolve https://github.com/neondatabase/neon/issues/6236, I should still look into the reason why the permission rows are not created for tables created by the extensions, instead of working around the superuser types 🤦‍♂️ I think I'm close enough to the ultimate solution but need to take one or two days resolving it next week.

**Pull request merged**
