### PR TITLE
NeonEnv.from_repo_dir: use storage_controller_db instead of `attachments.json`

### PR DESCRIPTION
**Pull request by problame**
When `NeonEnv.from_repo_dir` was introduced, storage controller stored its
state exclusively `attachments.json`.
Since then, it has moved to using Postgres, which stores its state in
`storage_controller_db`.

But `NeonEnv.from_repo_dir` wasn't adjusted to do this.
This PR rectifies the situation.

Context for this is failures in `test_pageserver_characterize_throughput_with_n_tenants`
CF: https://neondb.slack.com/archives/C033RQ5SPDH/p1721035799502239?thread_ts=1720901332.293769&cid=C033RQ5SPDH

Notably, `from_repo_dir` is also used by the backwards- and forwards-compatibility.
Thus, the changes in this PR affect those tests as well.
However, it turns out that the compatibility snapshot already contains the `storage_controller_db`.
Thus, it should just work and in fact we can remove hacks like `fixup_storage_controller`.

Follow-ups created as part of this work:
* https://github.com/neondatabase/neon/issues/8399
* https://github.com/neondatabase/neon/issues/8400

### CODE REVIEW

**Review by problame — COMMENTED** [review]
Do we need to patch the `nodes` table in the `storage_controller_db` because the pageserver nodes come up with a different port number?

**Comment by problame** [comment]
The regress tests hit timeouts because `test_backward_compatibility` is marked as a flaky test and gets rerun forever.

It fails because storcon doesn't accept the re-registration requests from the pageserver

```
2024-07-15T17:41:35.803471Z  INFO request{method=POST path=/upcall/v1/re-attach request_id=1e6ea5cd-8b7e-4b84-8b8d-187c8554e857}: Error processing HTTP request: Conflict: Node is already registered with different address
```

I.e., pageserver has the same node id (yay, that's what we want) but the obviously it has different port numbers now (= different metadata.json).

The new metadata.json is the right one.

The storcon db has the wrong one in its `nodes` table.

**Comment by problame** [comment]
Basically we have the following neon_local bug/missing feature, even outside this PR:

`metadata.json` changes will cause re-attach to fail with `Node is already registered with different address`

This is a TODO in the current code: https://github.com/neondatabase/neon/blob/411a130675363bd2e06be937926803390d748319/storage_controller/src/service.rs#L4389-L4391

**Comment by problame** [comment]
And we have another neon_local bug: the `metadata.json` is only written once during `neon_local init` and can becomes tale afterwards if listening port number is changed in `pageserver.toml`.

`NeonEnv.from_repo_dir` does not hit that bug though (because it does `init_configs()` which does `neon_local init` under the hood, and only selectively copies in state from the snapshot dir).

**Review by jcsp — APPROVED** [review]

**Comment by problame** [comment]
Awaiting testing from @Bodobolero , then I'll merge this.

**Pull request merged**
