### PR TITLE
Properly shutdown test mock S3 server

### PR DESCRIPTION
**Pull request by SomeoneToIgnore**
Closes https://github.com/neondatabase/neon/issues/1774

Also, while testing on an arm64 Debian, I've encountered this issue:
image

could be something we should be concerned of?

### CODE REVIEW

**Comment by hlinnaka** [comment]
> Also, while testing on an arm64 Debian, I've encountered this issue: image
> 
> could be something we should be concerned of?

Hmm, maybe? Did you grab the pageserver.log?

**Review by hlinnaka — APPROVED** [review]

**Comment by SomeoneToIgnore** [comment]
[pageserver.log](https://github.com/neondatabase/neon/files/8764358/pageserver.log)
[safekeeper.log](https://github.com/neondatabase/neon/files/8764359/safekeeper.log)
[pg.log](https://github.com/neondatabase/neon/files/8764366/pg.log)

**Comment by hlinnaka** [comment]
pageserver.log contained this:
```
2022-05-24T15:11:00.451116Z ERROR pagestream{timeline=2dc7a79d485fec5fc0844235399821d7 tenant=3c0d2183402941f88cd83b86c7f3f6ae}:get_page{rel=1663/12974/2704 blkno=4 req_lsn=0/16D6340}: wal-redo-postgres: 2022-05-24 18:11:00.451 EEST [67096] FATAL:  seccomp: failed to open a test file

2022-05-24T15:11:00.451628Z ERROR pagestream{timeline=2dc7a79d485fec5fc0844235399821d7 tenant=3c0d2183402941f88cd83b86c7f3f6ae}:get_page{rel=1663/12974/2704 blkno=4 req_lsn=0/16D6340}: error applying 1 WAL records to reconstruct page image at LSN 0/16D6340
2022-05-24T15:11:00.451659Z ERROR pagestream{timeline=2dc7a79d485fec5fc0844235399821d7 tenant=3c0d2183402941f88cd83b86c7f3f6ae}:get_page{rel=1663/12974/2704 blkno=4 req_lsn=0/16D6340}: wal-redo-postgres exited with code exit status: 1
2022-05-24T15:11:00.451810Z ERROR pagestream{timeline=2dc7a79d485fec5fc0844235399821d7 tenant=3c0d2183402941f88cd83b86c7f3f6ae}: error reading relation or page version: WAL redo process closed its stderr unexpectedly
```
That "seccomp: failed to open a test file" is interesting, will need to investigate that..

**Comment by hlinnaka** [comment]
That comes from here:
```

	/*
	 * First, check that open of a well-known file works.
	 * XXX: We use raw syscall() to call the very open().
	 */
	fd = syscall(SCMP_SYS(open), "/dev/null", O_RDONLY, 0);
	if (fd < 0 || seccomp_test_sighandler_done)
		raise_error("failed to open a test file");
	close((int)fd);
```
It failed to open /dev/null? Huh, weird.

**Comment by SomeoneToIgnore** [comment]
```
parallels@parallels:~/Desktop$ ls -lah /dev/|grep null
crw-rw-rw-   1 root root      1,   3 May 24 19:04 null

parallels@parallels:~/Desktop$ file /dev/null
/dev/null: character special (1/3)

parallels@parallels:~/Desktop$ cat /dev/null

parallels@parallels:~/Desktop$ echo "zzz" > /dev/null
```

Not sure what's wong, could be some parallels tricks, I can check it at some time later.
Does not look bad though?

**Pull request merged**
