### PR TITLE
Update rust version in toolchain

### LINKED ISSUE #3205: Switch to current stable (1.66)
While measuring build time several people observed significant improvement (10-15%). So it makes sense to upgrade. 

Makes sense to try to avoid strict version pinning. Maybe we can implement MSRV policy with `cargo check` verifying it in CI.

Version change needs to be applied to build repo. Example: https://github.com/neondatabase/build/pull/25

### PR DESCRIPTION
**Pull request by vadim2404**
Related to neondatabase/build#38
Closes #3205

### CODE REVIEW

**Review by SomeoneToIgnore — APPROVED** [review]

**Review by hlinnaka — CHANGES_REQUESTED** [review]
Our usual policy is to stick to a version that's available as a Debian package, at least in 'experimental'. 1.64 is the latest available there

**Comment by vadim2404** [comment]
@hlinnaka, Why do we have such limitations? In our images, we didn't rely on the system `rust` while building binaries. 

As I understood, updating was to decrease the compilation time, not only update the version because a new one was shipped.

**Comment by hlinnaka** [comment]
> @hlinnaka, Why do we have such limitations? In our images, we didn't rely on the system `rust` while building binaries.

1. Because I use the debian binaries :-).

2. More generally, when someone wants to try out neon and compile it, they don't need to install a new toolchain but can use whatever version they already  have installed. One less hurdle. Granted, not many people are running debian experimental either, we would need to be on an even older version for this benefit, really. The idea has been that we only update to latest debian experimental version if there's a concrete reason to do so. So most of the time, we would depend on something that's available on stable testing or stable. Rust compiler has been moving so fast, however, that in practice we've been tracking debian experimental pretty closely.

**Comment by arssher** [comment]
FWIW I want to use https://doc.rust-lang.org/beta/core/future/fn.poll_fn.html which stabilized in 1.64.0.

**Comment by vadim2404** [comment]
I can update to 1.64 because @hlinnaka insisted on being tightened to the Debian version. Heikki, what's the exact version of Rust in Debian?

**Comment by arssher** [comment]
1.64.0, see https://tracker.debian.org/pkg/rustc
It is mentioned in `rust-toolchain.toml`.

**Comment by arssher** [comment]
BTW rust-toolchain.toml points to 'unstable', which is only 1.63, not 'experimental'; I see above agreement to experimental though.

**Review by SomeoneToIgnore — COMMENTED** [review]
Let's clean the comments around too: we're no longer on Debian model with this commit.

**Review by SomeoneToIgnore — APPROVED** [review]

**Review by hlinnaka — APPROVED** [review]
Per discussion offline, I'm the only one who wants to stick to an older version. I'm withdrawing my objection because I'm overwhelmingly outvoted on this.

**Pull request merged**
