### PR TITLE
build: back to opt-level=0 in debug builds, for faster compile times

### PR DESCRIPTION
**Pull request by problame**
This change brings down incremental compilation for me
from > 1min to 10s (and this is a pretty old Ryzen 1700X).

More details: "incremental compilation" here means to change one character
in the `failed to read value from offset` string in `image_layer.rs`.
The command for incremental compilation is `cargo build_testing`.
The system on which I got these numbers uses `mold` via
`~/.cargo/config.toml`.

As a bonus, `rust-gdb` is now at least a little fun again.

Some tests are timing out in debug builds due to these changes.
This PR makes them skip for debug builds.
We run both with debug and release build, so, the loss of coverage is marginal.

### CODE REVIEW

**Comment by problame** [comment]
Comparing to past 3 builds of `main` , I don't see a regression in terms of `cargo build` or `cargo test` performance.

https://github.com/neondatabase/neon/actions/runs/6710322853/job/18235242119
https://github.com/neondatabase/neon/actions/runs/6709936648/job/18234078430
https://github.com/neondatabase/neon/actions/runs/6709701253/job/18233311087


Will update this message once we have regress-test numbers.

**Review by koivunej — APPROVED** [review]
Approving, I was wondering if this could have an effect re incr build times. I've often working with these disabled when using a debugger.

**Comment by koivunej** [comment]
I wonder if we could get rid of testing with debug builds completely if we were to enable debug assertions in regress test (release) builds. It does not feel like a valid reason to keep compilation times longer to pass our regress tests, though if the regress tests would not pass even locally then that would be a problem.

**Comment by problame** [comment]
I don’t have time to make those CI YAML changes in this PR.

**Comment by koivunej** [comment]
> The above could perhaps be juggled with opt-level=1 but does that already kill the compilation time for you?

Tried this:

with opt-level=1 changing the image_layer.rs string is 30s. (clean rebuild was more than 3 minutes). same magnitude change with opt-level=0 is 9s. (clean rebuild was 2m 15s). did this by: `cargo clean && cargo build_testing` + edit + `cargo build_testing` so there wasn't many layers of incr compilation, also I hopefully had zero rust-analyzers working near the workdir.

**Review by koivunej — APPROVED** [review]
I think it's valid to skip these long tests, and skipping produces output that no one should waste time trying to reproduce some failure in debug mode because of this change.

**Comment by problame** [comment]
There was [some discussion on Slack](https://neondb.slack.com/archives/C0277TKAJCA/p1698921788106589?thread_ts=1698779896.239249&cid=C0277TKAJCA) about [the code coverage report](https://neon-github-public-dev.s3.amazonaws.com/code-coverage/c264b2aed1ff3d26d8f6b775480e1b8a231a1ffc/lcov/index.html)  on Slack, specifically about the LBC (lost baseline coverage).

During the discussion we discovered that the baseline coverage commit is wrong:
it's `3737fe` whereas it should be `726c8e6`.


image


I think the reason is that GH Actions checks out a merge commit, i.e.,  for each action run, it checks out whathever the current  tip of the base branch is, and merges into it the PR branch.

We'll merge this PR without fixing this wrong baseline first.
I'll turn this comment into a new issue for @bayandin

**Comment by problame** [comment]
Waiting for https://github.com/neondatabase/neon/pull/5769

**Comment by problame** [comment]
Correct coverage report, including LBC (lost ... count) metric: https://neon-github-public-dev.s3.amazonaws.com/code-coverage/16222274fc3c211c849357ad274a6e5cd3400de3/lcov/index.html

We are losing coverage of some very obvious "bail on error branches".

And we don't have coverage for "remove layers that are from the future" anymore.

I think this is fine. Let's merge this. @koivunej  last chance to reject!

**Review by koivunej — APPROVED** [review]
Unchanged: I think we should prioritize development experience because that will otherwise cost us a lot of time, like flaky tests.

**Pull request merged**
