### PR TITLE
Update `rust-postgres` project-wide

### PR DESCRIPTION
**Pull request by funbringer**
This commit points to https://github.com/neondatabase/rust-postgres/commits/neon in order to test our patches on top of the latest version of this crate.

### CODE REVIEW

**Comment by kelvich** [comment]
Seems that tests are fine? I'm +1 on merging this

**Comment by funbringer** [comment]
There's one more patch I'd like to add before merging this.

**Review by kelvich — APPROVED** [review]

**Review by LizardWizzard — APPROVED** [review]

**Comment by SomeoneToIgnore** [comment]
Hm, looks like this changed something in `main` for us: https://app.circleci.com/pipelines/github/neondatabase/neon?branch=main&filter=all

image

Now sure what's going on yet, seems unrelated to the changes.

**Comment by funbringer** [comment]
изображение

**Comment by SomeoneToIgnore** [comment]
More discussion: https://neondb.slack.com/archives/C036U0GRMRB/p1650666256623109

it's rather flaky which and odd in general.

**Pull request merged**
