### PR TITLE
 Add support of extensions for v17 (pgrx) (#9430)

### PR DESCRIPTION
**Pull request by lubennikovaav**
- pg_jsonschema 0.3.3
- pg_graphql 1.5.9

update support of extensions for v14-v16:
- pg_session_jwt 0.1.1 (cc @davidgomes)

### CODE REVIEW

**Comment by davidgomes** [comment]
FYI @lubennikovaav we have just bumped `pg_session_jwt`:
- https://github.com/neondatabase/pg_session_jwt/commit/e1310b08ba51377a19e0559e4d1194883b9b2ba2
- https://github.com/neondatabase/neon/pull/9474

**Comment by conradludgate** [comment]
I'm trying to think how we should handle the versions for now.
Currently, local_proxy hard codes a single version string for the pg-session-jwt extension.

I think for now I will make a separate branch in the project dedicated to updated pgrx, and we'll make to implement any changes to both.

**Comment by conradludgate** [comment]
I merged this PR with main and added the changes from https://github.com/neondatabase/pg_session_jwt/commit/b55d757d6d485b91a3b52b1abaabdd7f033dd584 as a pg17 version. For now it has the same extension version number (as it is required by local_proxy), but the behaviour is identical so I don't think that should matter.

**Comment by lubennikovaav** [comment]
Closed in favor of https://github.com/neondatabase/neon/pull/9568
@conradludgate , let's create separate PR for pg_session_jwt on top of #9568, because we also need to handle dependencies.

**Pull request closed without merging**
