### PR TITLE
Rename zenith crate to neon_local

### PR DESCRIPTION
**Pull request by bojanserafimov**
Last time we talked consensus was that neon_local would be better than just neon.

### CODE REVIEW

**Review by hlinnaka — APPROVED** [review]

**Review by SomeoneToIgnore — APPROVED** [review]
`neon_cli` might be a bit more simple to grasp?

**Comment by hlinnaka** [comment]
> `neon_cli` might be a bit more simple to grasp?

Agreed, `neon_cli` would be nicer. Or just `neon`. However, we might have a different CLI in the future, to act as the client for the cloud service. That's different from the current CLI, which controls a local test installation.

Maybe `neon_ctl`, as in "control local neon installation". And the other CLI could then be just `neon`.

**Comment by hlinnaka** [comment]
Umm, actually, we already have a `zenith_ctl` binary, in `compute_tools`. That will presumably be renamed to `neon_ctl`.

I guess we're back to `neon_local` for this binary...

**Comment by bojanserafimov** [comment]
`neon_local` is better than staying with `zenith`, and it's easy to change.

**Comment by hlinnaka** [comment]
Please also update the top-level README for the new name of the binary

**Pull request merged**
