### PR TITLE
refactor: to pattern of await after timeout

### PR DESCRIPTION
**Pull request by koivunej**
Refactor the `!completed` to be about `Option<_>` instead, side-stepping any boolean true/false or false/true. As discussed on https://github.com/neondatabase/neon/pull/4399#discussion_r1219321848

### CODE REVIEW

**Review by skyzh — APPROVED** [review]

**Review by problame — APPROVED** [review]

**Review by awestover — APPROVED** [review]
looks good

**Review by awestover — APPROVED** [review]
looks good

**Comment by koivunej** [comment]
Oh, this is still open. Re-triggering e2e tests..

**Comment by skyzh** [comment]
cloud e2e test seems not be able to find an image (due to PR not updated for a while?), so I pushed a new commit to trigger CI

**Pull request merged**
