### PR TITLE
Don't upload index file when GC doesn't remove anything.

### PR DESCRIPTION
**Pull request by hlinnaka**
See commit messages. I plan to push this as two separate commits. I recommend reviewing them separately, too.

### CODE REVIEW

**Review by koivunej — COMMENTED** [review]
Overall this looks good, happy to see `checkpoint_before_gc` go away. I think you missed some unit tests related to gc, given the style check failing.

**Comment by hlinnaka** [comment]
Fixed the unit tests, formatting and a couple of typos in the test changes. The CI is now green.

**Review by koivunej — COMMENTED** [review]
I don't see many changes from my last review round.

**Review by koivunej — APPROVED** [review]
Ah, also missed the explanation comment :) Aah yes the test fixes are oneliners.

**Pull request merged**
