### PR TITLE
storcon: automatically clear Pause/Stop scheduling policies to enable detaches

### PR DESCRIPTION
**Pull request by jcsp**
## Problem

We saw a tenant get stuck when it had been put into Pause scheduling mode to pin it to a pageserver, then it was left idle for a while and the control plane tried to detach it.

Close: https://github.com/neondatabase/neon/issues/9957

## Summary of changes

- When changing policy to Detached or Secondary, set the scheduling policy to Active.
- Add a test that exercises this
- When persisting tenant shards, set their `generation_pageserver` to null if the placement policy is not Attached (this enables consistency checks to work, and avoids leaving state in the DB that could be confusing/misleading in future)

### CODE REVIEW

**Review by VladLazar — COMMENTED** [review]
Code itself look fine.

---

Is this the behaviour we want though? We lose the shard scheduling policy whenever cplane detaches (e.g. idle tenant detach). This is also confusing.

Would this alternative work?
When detaching or downgrading to secondary due to external location conf, the storage controller proxies it to the pageserver irrespective of the shard policy.
Pageserver handles it and we preserved the policy on the storcon.

**Comment by jcsp** [comment]
> Is this the behaviour we want though? We lose the shard scheduling policy whenever cplane detaches (e.g. idle tenant detach). This is also confusing.

This is perhaps a symptom of the scheduling policies being a bit over-general as a concept.  What we're using them for in practice is to use Pause to pin a tenant to a pageserver, and once we are detached, it usually makes sense to forget that pin.

>When detaching or downgrading to secondary due to external location conf, the storage controller proxies it to the pageserver irrespective of the shard policy. Pageserver handles it and we preserved the policy on the storcon.

This could be fragile: it's okay if the pageserver is available, or if the pageserver is marked offline (because when it becomes available it'll get true'd up), but if the pageserver is unavailable but not yet marked offline, then it would prevent us changing the configuration of a tenant.  That's arguably tolerable, but it sort of breaks the model that we can change configs in the foreground and reconcile in the background.

I do generally agree that there's a bit of "code smell" here... but fudging the scheduling policy is probably a less bad smell than changing the config functions to do pageserver work in the foreground instead of going via reconciliation.

**Comment by jcsp** [comment]
Added comment about usage of ShardSchedulingPolicy in 294a941f03c4b7675dae764b3065443a2d563bcb

>>but if the pageserver is unavailable but not yet marked offline, then it would prevent us changing the configuration of a tenant

>I don't see it. We update the db and in-memory state and will reconcile when the pageserver comes back online.

But the reconcile wouldn't do anything if scheduling mode was still set to Pause (i.e. for that to work we'd have to also have the change in this PR), thinking specifically of the case of a brief unavailability where we don't do a whole-node reconcile.

**Comment by VladLazar** [comment]
> Added comment about usage of ShardSchedulingPolicy in [294a941](https://github.com/neondatabase/neon/commit/294a941f03c4b7675dae764b3065443a2d563bcb)
> 
> > > but if the pageserver is unavailable but not yet marked offline, then it would prevent us changing the configuration of a tenant
> 
> > I don't see it. We update the db and in-memory state and will reconcile when the pageserver comes back online.
> 
> But the reconcile wouldn't do anything if scheduling mode was still set to Pause (i.e. for that to work we'd have to also have the change in this PR), thinking specifically of the case of a brief unavailability where we don't do a whole-node reconcile.

Right, special casing it was implied it for detach and downgrade to secondary was implied in my proposal.

**Review by VladLazar — APPROVED** [review]
I'm fine with this. I was trying to explore alternatives in the PR thread, but we don't have to block this PR.

**Pull request merged**
