### PR TITLE
Add support for ip4r extension

### PR DESCRIPTION
**Pull request by vadim2404**
## Describe your changes
To execute CI properly (#3993)

## Checklist before requesting a review

- [x] I have performed a self-review of my code.
- [ ] If it is a core feature, I have added thorough tests.
- [ ] Do we need to implement analytics? if so did you add the relevant metrics to the dashboard?
- [x] If this PR requires public announcement, mark it with /release-notes label and add several sentences in this section.

## Checklist before merging

- [ ] Do not forget to reformat commit message to not include the above checklist

### CODE REVIEW

**Comment by vadim2404** [comment]
@samgaw I've created a new PR with your changes in order to pass CI checks related to docker images

**Comment by bayandin** [comment]
> To execute CI properly (https://github.com/neondatabase/neon/pull/3993)

You can close and reopen that PR; this will trigger CI on your behalf with all required access to secrets

**Comment by vadim2404** [comment]
@bayandin it wasn't a problem to open new PR, because I've tested it in parallel :)

**Review by bayandin — APPROVED** [review]
I have a general comment (regarding all extensions we install).

I think we should either use checksum for what we download or switch to downloading a particular git commit (like https://github.com/RhodiumToad/ip4r/archive/cfa021f160925ff4cdb73c7efb89d5f6a75f3096.tar.gz if we download sources from GitHub). I prefer checksums since not all extensions are downloaded from GitHub.
Otherwise, git allows retagging, which could silently give us some minor changes in sources or contain malicious code in a worst case.

Let me know what you think. I can create a PR for this.

**Pull request merged**
