### PR TITLE
fix: no more ansi colored logs

### PR DESCRIPTION
**Pull request by koivunej**
## Problem

Allure does not support ansi colored logs, yet `compute_ctl` has them.

## Summary of changes

Upgrade criterion to get rid of atty dependency, disable ansi colors, remove atty dependency and disable ansi feature of tracing-subscriber.

This is a heavy-handed approach. I am not aware of a workflow where you'd want to connect a terminal directly to for example `compute_ctl`, usually you find the logs in a file. If someone had been using colors, they will now need to:
- turn the `tracing-subscriber.default-features` to `true`
- edit their wanted project to have colors

I decided to explicitly disable ansi colors in case we would have in future a dependency accidentally enabling the feature on `tracing-subscriber`, which would be quite surprising but not unimagineable.

By getting rid of `atty` from dependencies we get rid of <https://github.com/advisories/GHSA-g98v-hv3f-hcfr>.

## Checklist before requesting a review

- [ ] I have performed a self-review of my code.
- [ ] If it is a core feature, I have added thorough tests.
- [ ] Do we need to implement analytics? if so did you add the relevant metrics to the dashboard?
- [ ] If this PR requires public announcement, mark it with /release-notes label and add several sentences in this section.

## Checklist before merging

- [ ] Do not forget to reformat commit message to not include the above checklist

### CODE REVIEW

**Review by conradludgate — APPROVED** [review]
Happy from my end, but I'd wait for other reviews to incase it breaks workflows

**Review by arpad-m — APPROVED** [review]
Implementation wise this looks good, although I am missing context on whether color support was wanted in the first place or if auto-detection is desired.

**Comment by bayandin** [comment]
Here's an example of a [compute.log](https://neon-github-public-dev.s3.amazonaws.com/reports/pr-4613/5443780343/index.html#suites/0fbaeb107ef328d03993d44a1fb15690/5fd847ce6df2d7ec/?attachment=25bc57f9646113d5), looks much more clean now, thanks @koivunej 👍 

I wonder if we can unify the log format between C and Rust parts:
```
2023-07-03T11:19:01.168515Z  INFO configurator_main_loop: woken up for compute status: Running, sleeping
2023-07-03T11:19:01.222254Z  INFO http request{otel.name=/status http.method=GET}: serving /status GET request
2023-07-03 11:19:01.232 GMT [85050] LOG:  [NEON_SMGR] libpagestore: connected to 'postgresql://no_user@localhost:25020'
2023-07-03 11:19:01.247 GMT [85062] LOG:  [NEON_SMGR] libpagestore: connected to 'postgresql://no_user@localhost:25020'
```

**Comment by koivunej** [comment]
> Implementation wise this looks good, although I am missing context on whether color support was wanted in the first place or if auto-detection is desired.

There has been a bit of head scratching as to why some logs have ansi colors, and most don't. With some browsers it's possible to copy paste ansi escaped sequences from our log search to slack for example, which is highly unpleasant to read. With allure reports (our "regress" or integration test reporting) as linked by @bayandin in https://github.com/neondatabase/neon/pull/4613#issuecomment-1618026137 there is no ansi => html conversion.

So at least with compute_ctl, it was never explicitly enabled it was just true because of `default-features = true`. For other binaries... I don't understand in which case you'd run them directly but maybe there's a workflow I don't know. Usually binaries are ran through `cargo neon` or `cargo run -bin neon_local` (`control_plane/src/bin/neon_local.rs`).

> I wonder if we can unify the log format between C and Rust parts (not required for this PR):

We don't define postgres `log_line_prefix` in this repo, maybe it comes from control plane database directly? Though, couldn't find it right away. Could be it is currently the default `%m [%p] ` which is timestamp + process id which our logs seem to have as well, though would not have suspected timezone to be there by default.

**Comment by koivunej** [comment]
The colors do not seem to be a popular topic anyone else would care deeply for. I'll just merge it to have people come complaining. The PR removes duplicate dependencies so at least our build will be faster.

**Pull request merged**
