### PR TITLE
Fix slru_segment_key_range function: segno was assigned to incorrect Key field

### PR DESCRIPTION
**Pull request by knizhnik**

### CODE REVIEW

**Comment by hlinnaka** [comment]
A regression test would be nice

**Review by LizardWizzard — COMMENTED** [review]
I'm not sure I'm the right person for the review. Feel free to pick someone else. Plus one for having a test

**Comment by knizhnik** [comment]
> A regression test would be nice

I wonder what kind of test do you expect?
Unit test which  checks that this function produce correct interval?
Or test for deletion of SRU segments?
I do not know how to force Postgres to truncate for example CLOG segment in some reasonable amount of time.
I run pgbench during 1000 seconds and then try to get status of transaction preceded this pgbench iteration (using `txid_satus`)
and it still reports correct status.

**Comment by knizhnik** [comment]
According to the problems with forcing CLOG truncation (see https://neondb.slack.com/archives/C033RQ5SPDH/p1674037379794899) I failed to create some meaningful test for this fix.
But frankly speaking I consider this bug just as mistyping and do not think that we need some separate test exactly for  `srlu_segment_key_range` function.

Moreover I wonder do we need this `Key` structure with this obscure `fieldN` fields at all?
May be just replace it with i128?
We in any case are using i128 representation of key in layer map.
I expect that replacing struct with scalar type will save some memory allocations and memcpys...

**Comment by lubennikovaav** [comment]
@knizhnik 
do we need to add some handling around `slru_segment_key_range` calls` for already existing incorrect keys ? 
What will happen, if we mix both "old-format" and "new-format" keys in one call? Or it is an impossible situation?

**Comment by knizhnik** [comment]
This function is used only by delete when SLRU is truncated. So there are no bad keys stored in the storage.
Truncation of CLOG happens only after 200M transactions and this is why nobody of  our customers still suffer from this bug.
But sooner or latter it will definitely happen. And it can happen that all CLOG segments will be deleted as result of such truncation.  In this case all user database will be lost because accessing it without CLOG is problematic.

**Review by lubennikovaav — APPROVED** [review]
Thank you for clarification!
+1 from me, but let's wait for @hlinnaka review before merging

**Review by hlinnaka — APPROVED** [review]
Let's merge this now, it's easy to see from the code that this is a bug, and the fix is correct. 

However, I'd still like to see a test case for this, after this is merged.

> This function is used only by delete when SLRU is truncated. So there are no bad keys stored in the storage.
Truncation of CLOG happens only after 200M transactions and this is why nobody of our customers still suffer from this bug.
But sooner or latter it will definitely happen. And it can happen that all CLOG segments will be deleted as result of such truncation. In this case all user database will be lost because accessing it without CLOG is problematic.

Sounds like that would be easily reproducible. Can we add a test like that to the test suite?

**Comment by knizhnik** [comment]
> Sounds like that would be easily reproducible. Can we add a test like that to the test suite?
 
Do you know fsater way to perform 200M transactions than our `test_runner/sql_regress/sql/neon-clog.sql`:
```
create or replace procedure do_commits() as $$
declare
    xid xid8;
	i integer;
begin
    for i in 1..200000000 loop
	    xid = txid_current();
		commit;
		if (pg_xact_status(xid) <> 'committed') then
		   raise exception 'CLOG corruption';
		end if;
	end loop;
end;
$$ language plpgsql;

call do_commits();
```

But it takes about half an hour for this test to perform 200M transactions.
And yes, I can confirm that after i CLOG is lost.

**Comment by LizardWizzard** [comment]
Should we have an issue for the test? Otherwise we can easily lose it (cc @vadim2404)

**Pull request merged**
