### PR TITLE
Make get_lsn_by_timestamp available in mgmt API (#2536)

### PR DESCRIPTION
**Pull request by andresrsanchez**
refer #2536

### CODE REVIEW

**Review by SomeoneToIgnore — APPROVED** [review]
Looks good, thank you!

**Comment by SomeoneToIgnore** [comment]
Looks like CI complains about some misformatted code, use `cargo fmt` and `poetry run black` (you would need to run `./scripts/pysync` to actually install it first) to fix the issues.

**Comment by andresrsanchez** [comment]
oops do i need to change anything? the failing tests does not seem to be related

**Comment by SomeoneToIgnore** [comment]
No, unfortunately, our tests might fail sometimes to unrelated reasons, the current one seems to be related to AWS S3 (the main one, that failed the tests) and docker connectivity (that failed other jobs later, but it does not matter much at this point).
Rerunning usually helps, I'll do it.

**Comment by SomeoneToIgnore** [comment]
Oh, now I see: our CI has many external services called, due to different tests we run.
Contributors' CI runs do not contain certain credentials, hence not able to trigger certain events or access certain resources that we use for testing.

I'll push a test branch from my account and test it. 
We have an issue from the past: https://github.com/neondatabase/neon/issues/2222 might be a good time to revive the initiative, thank you.

**Comment by SomeoneToIgnore** [comment]
Tests passed and since I've pushed the same commits, your PR had to the status update, nice.
We're sure fixing the CI properly eventually, sorry about that experience and thanks for the PR.

**Pull request merged**
