### PR TITLE
fix macOS build using conditional compilation

### PR DESCRIPTION
**Pull request by problame**
Depends on https://github.com/neondatabase/tokio-epoll-uring/pull/32

### CODE REVIEW

**Review by koivunej — APPROVED** [review]

**Comment by problame** [comment]
Hm, debug build is hanging: 
image

Will try to SSH into the runner and coredump / investigate this

**Comment by problame** [comment]
```
root@large-03 ~ # ps aux | grep pageserver
nonroot   403635  0.2  0.3 3667628 491848 ?      SLl  15:51   0:11 /__w/neon/neon/target/debug/deps/pageserver-c0c5212b92ba45c9 --exact tenant::remote_timeline_client::tests::index_part_download_ordering --nocapture
nonroot   403656  0.2  0.3 3667628 484536 ?      SLl  15:51   0:11 /__w/neon/neon/target/debug/deps/pageserver-c0c5212b92ba45c9 --exact tenant::tests::test_images --nocapture
nonroot   403712  0.2  0.3 3667628 486256 ?      SLl  15:51   0:11 /__w/neon/neon/target/debug/deps/pageserver-c0c5212b92ba45c9 --exact tenant::timeline::walreceiver::connection_manager::tests::connection_no_candidate --nocapture
root      404768  0.0  0.0   8240   704 pts/0    S+   17:08   0:00 grep pageserver
```

stracing them, they all look like this

```

[pid 403636] epoll_wait(3, [{EPOLLIN, {u32=0, u64=0}}], 1024, 75) = 1
[pid 403636] epoll_wait(3, [], 1024, 75) = 0
[pid 403636] epoll_wait(3, [], 1024, 25) = 0
[pid 403636] write(4, "\1\0\0\0\0\0\0\0", 8) = 8
[pid 403636] epoll_wait(3, [{EPOLLIN, {u32=0, u64=0}}], 1024, 38) = 1
[pid 403636] epoll_wait(3, [], 1024, 38) = 0
[pid 403636] epoll_wait(3, [], 1024, 63) = 0
[pid 403636] write(4, "\1\0\0\0\0\0\0\0", 8) = 8
[pid 403636] epoll_wait(3, [{EPOLLIN, {u32=0, u64=0}}], 1024, 64) = 1
[pid 403636] epoll_wait(3, [], 1024, 64) = 0
[pid 403636] epoll_wait(3, [], 1024, 37) = 0
[pid 403636] write(4, "\1\0\0\0\0\0\0\0", 8) = 8
[pid 403636] epoll_wait(3, [{EPOLLIN, {u32=0, u64=0}}], 1024, 90) = 1
[pid 403636] epoll_wait(3, [], 1024, 90) = 0
[pid 403636] epoll_wait(3, [], 1024, 11) = 0
[pid 403636] write(4, "\1\0\0\0\0\0\0\0", 8) = 8
[pid 403636] epoll_wait(3, [{EPOLLIN, {u32=0, u64=0}}], 1024, 52) = 1
[pid 403636] epoll_wait(3, [], 1024, 52) = 0
```

**Comment by problame** [comment]
An hour or so later, it's still the same processes.

<details>

```
root@large-03 ~ # gcore -o 403656.core 403656
[New LWP 403666]
[New LWP 403741]
[New LWP 403742]
[New LWP 403744]
[New LWP 403745]
[New LWP 403747]
[New LWP 403748]
[New LWP 403749]
[New LWP 403750]
[New LWP 403751]
[New LWP 403752]
[New LWP 403753]
[New LWP 403754]
[New LWP 403757]
[New LWP 403762]
[New LWP 403764]
[New LWP 403766]
[New LWP 403767]
[New LWP 403769]
[New LWP 403774]
[New LWP 403775]
[New LWP 403776]
[New LWP 403777]
[New LWP 403778]
[New LWP 403779]
[New LWP 403780]
[New LWP 403781]
[New LWP 403782]
[New LWP 403783]
[New LWP 403784]
[New LWP 403785]
[New LWP 403786]
[New LWP 403787]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
warning: Target and debugger are in different PID namespaces; thread lists and other data are likely unreliable.  Connect to gdbserver inside the container.
0x00007f036aae9f29 in syscall () from target:/lib/x86_64-linux-gnu/libc.so.6
warning: target file /proc/403656/cmdline contained unexpected null characters
Saved corefile 403656.core.403656
[Inferior 1 (process 403656) detached]
```

```
 278026   /usr/bin/containerd-shim-runc-v2 -namespace moby -id ccfbcaf1fe273fb13cca48d0eabe34eeeaa2b0df25fb39143ac4f0d23eae2f1d -address /run/containerd/containerd.sock
 278046     /sbin/docker-init -- tail -f /dev/null
 278077       tail -f /dev/null
 399924     bash -euxo pipefail /__w/_temp/fd57d9cf-7756-45a3-9da5-cda9cd886b7e.sh
 403240       /home/nonroot/.pyenv/versions/3.9.2/bin/python3 scripts/coverage --profraw-prefix=build-neon --dir=/tmp/coverage run cargo nextest run --locked --features testing
 403288         /home/nonroot/.cargo/bin/cargo-nextest nextest run --locked --features testing
 403635           /__w/neon/neon/target/debug/deps/pageserver-c0c5212b92ba45c9 --exact tenant::remote_timeline_client::tests::index_part_download_ordering --nocapture
 403656           /__w/neon/neon/target/debug/deps/pageserver-c0c5212b92ba45c9 --exact tenant::tests::test_images --nocapture
 403712           /__w/neon/neon/target/debug/deps/pageserver-c0c5212b92ba45c9 --exact tenant::timeline::walreceiver::connection_manager::tests::connection_no_candidate --nocapture
```

```
root@large-03 ~ # docker inspect ccfbcaf1fe273fb13cca48d0eabe34eeeaa2b0df25fb39143ac4f0d23eae2f1d
[
    {
        "Id": "ccfbcaf1fe273fb13cca48d0eabe34eeeaa2b0df25fb39143ac4f0d23eae2f1d",
        "Created": "2024-01-15T14:47:23.473752824Z",
        "Path": "tail",
        "Args": [
            "-f",
            "/dev/null"
        ],
        "State": {
            "Status": "running",
            "Running": true,
            "Paused": false,
            "Restarting": false,
            "OOMKilled": false,
            "Dead": false,
            "Pid": 278046,
            "ExitCode": 0,
            "Error": "",
            "StartedAt": "2024-01-15T14:47:23.692594262Z",
            "FinishedAt": "0001-01-01T00:00:00Z"
        },
        "Image": "sha256:6ecdea7ee8f6b4d753cff6bd90e1b070ee974318aea7b51d0d40f62f2f5f07f3",
        "ResolvConfPath": "/var/lib/docker/containers/ccfbcaf1fe273fb13cca48d0eabe34eeeaa2b0df25fb39143ac4f0d23eae2f1d/resolv.conf",
        "HostnamePath": "/var/lib/docker/containers/ccfbcaf1fe273fb13cca48d0eabe34eeeaa2b0df25fb39143ac4f0d23eae2f1d/hostname",
        "HostsPath": "/var/lib/docker/containers/ccfbcaf1fe273fb13cca48d0eabe34eeeaa2b0df25fb39143ac4f0d23eae2f1d/hosts",
        "LogPath": "/var/lib/docker/containers/ccfbcaf1fe273fb13cca48d0eabe34eeeaa2b0df25fb39143ac4f0d23eae2f1d/ccfbcaf1fe273fb13cca48d0eabe34eeeaa2b0df25fb39143ac4f0d23eae2f1d-json.log",
        "Name": "/14919a4097e14d128a9b0d61c77c71f8_dkrecreucentral1amazonawscombuildtoolspinned_6aa826",
        "RestartCount": 0,
        "Driver": "overlay2",
        "Platform": "linux",
        "MountLabel": "",
        "ProcessLabel": "",
        "AppArmorProfile": "docker-default",
        "ExecIDs": [
            "0c7b9b7d142ae2f258cfa8b778686f58ae1df882f2936dbb98c289f41e771c8a"
        ],
        "HostConfig": {
            "Binds": [
                "/nvme/actions-runner/_work/_temp/_github_home:/github/home",
                "/nvme/actions-runner/_work/_temp/_github_workflow:/github/workflow",
                "/var/run/docker.sock:/var/run/docker.sock",
                "/nvme/actions-runner/_work:/__w",
                "/nvme/actions-runner/externals:/__e:ro",
                "/nvme/actions-runner/_work/_temp:/__w/_temp",
                "/nvme/actions-runner/_work/_actions:/__w/_actions",
                "/nvme/actions-runner/_work/_tool:/__w/_tool"
            ],
            "ContainerIDFile": "",
            "LogConfig": {
                "Type": "json-file",
                "Config": {}
            },
            "NetworkMode": "github_network_00b20236af194781ae90e7e9b29a2db8",
            "PortBindings": {},
            "RestartPolicy": {
                "Name": "no",
                "MaximumRetryCount": 0
            },
            "AutoRemove": false,
            "VolumeDriver": "",
            "VolumesFrom": null,
            "ConsoleSize": [
                0,
                0
            ],
            "CapAdd": null,
            "CapDrop": null,
            "CgroupnsMode": "private",
            "Dns": [],
            "DnsOptions": [],
            "DnsSearch": [],
            "ExtraHosts": null,
            "GroupAdd": null,
            "IpcMode": "private",
            "Cgroup": "",
            "Links": null,
            "OomScoreAdj": 0,
            "PidMode": "",
            "Privileged": false,
            "PublishAllPorts": false,
            "ReadonlyRootfs": false,
            "SecurityOpt": null,
            "UTSMode": "",
            "UsernsMode": "",
            "ShmSize": 67108864,
            "Runtime": "runc",
            "Isolation": "",
            "CpuShares": 0,
            "Memory": 0,
            "NanoCpus": 0,
            "CgroupParent": "",
            "BlkioWeight": 0,
            "BlkioWeightDevice": [],
            "BlkioDeviceReadBps": null,
            "BlkioDeviceWriteBps": null,
            "BlkioDeviceReadIOps": null,
            "BlkioDeviceWriteIOps": null,
            "CpuPeriod": 0,
            "CpuQuota": 0,
            "CpuRealtimePeriod": 0,
            "CpuRealtimeRuntime": 0,
            "CpusetCpus": "",
            "CpusetMems": "",
            "Devices": [],
            "DeviceCgroupRules": null,
            "DeviceRequests": null,
            "MemoryReservation": 0,
            "MemorySwap": 0,
            "MemorySwappiness": null,
            "OomKillDisable": null,
            "PidsLimit": null,
            "Ulimits": null,
            "CpuCount": 0,
            "CpuPercent": 0,
            "IOMaximumIOps": 0,
            "IOMaximumBandwidth": 0,
            "MaskedPaths": [
                "/proc/asound",
                "/proc/acpi",
                "/proc/kcore",
                "/proc/keys",
                "/proc/latency_stats",
                "/proc/timer_list",
                "/proc/timer_stats",
                "/proc/sched_debug",
                "/proc/scsi",
                "/sys/firmware",
                "/sys/devices/virtual/powercap"
            ],
            "ReadonlyPaths": [
                "/proc/bus",
                "/proc/fs",
                "/proc/irq",
                "/proc/sys",
                "/proc/sysrq-trigger"
            ],
            "Init": true
        },
        "GraphDriver": {
            "Data": {
                "LowerDir": "/var/lib/docker/overlay2/66f86d4f35afa2bd89c404671d66972ef9b6d21c5059a00883ad114aa8ee4f58-init/diff:/var/lib/docker/overlay2/3f3d49cf684751ee6064f87267a71c91053e2e18baed6e022beb9a9c0294ef22/diff:/var/lib/docker/overlay2/26df34e200f5c2cfccbff767dff74858a07bf5789137e39fc7d3b9c7a24ae19a/diff:/var/lib/docker/overlay2/a23e433a159eb479790e89d672b7f3fdb40a853aee8736d732cf233e51641db6/diff:/var/lib/docker/overlay2/5fa5179aedb65f81c655a425c7a388c901b4ee397cbf1eca048d02ba0abadf35/diff:/var/lib/docker/overlay2/ffeb092d39af9e862dde93aeb2d9966087b373abda4c3daf6aafbdf8e220fe00/diff:/var/lib/docker/overlay2/9b2533e92fc8820dd7f2a292677a4fb5440d0e45fdde834c8ee5eafba27a363e/diff:/var/lib/docker/overlay2/394f207d93703788c7c8263225ba4e6330432ea5e3d1fa693b546d8c58eb98ee/diff:/var/lib/docker/overlay2/cfaca45da7380446335a34d6b28129a395961fead71d25f3ccf3b92202435546/diff:/var/lib/docker/overlay2/55b0dbdc4db50af7bd960d5fbc5fdcfe264e4aa2963d0e24f24b9608c347ff63/diff:/var/lib/docker/overlay2/fef93e2d552d7714e164370de982ab8bb3baa8965f053166654a90aa033d0b72/diff:/var/lib/docker/overlay2/8b21312627b0037e53bc0e9a19f07a7141ffa537f07ff6b0288308e4d6939ea1/diff",
                "MergedDir": "/var/lib/docker/overlay2/66f86d4f35afa2bd89c404671d66972ef9b6d21c5059a00883ad114aa8ee4f58/merged",
                "UpperDir": "/var/lib/docker/overlay2/66f86d4f35afa2bd89c404671d66972ef9b6d21c5059a00883ad114aa8ee4f58/diff",
                "WorkDir": "/var/lib/docker/overlay2/66f86d4f35afa2bd89c404671d66972ef9b6d21c5059a00883ad114aa8ee4f58/work"
            },
            "Name": "overlay2"
        },
        "Mounts": [
            {
                "Type": "bind",
                "Source": "/nvme/actions-runner/_work/_actions",
                "Destination": "/__w/_actions",
                "Mode": "",
                "RW": true,
                "Propagation": "rprivate"
            },
            {
                "Type": "bind",
                "Source": "/nvme/actions-runner/_work/_tool",
                "Destination": "/__w/_tool",
                "Mode": "",
                "RW": true,
                "Propagation": "rprivate"
            },
            {
                "Type": "bind",
                "Source": "/nvme/actions-runner/_work/_temp/_github_home",
                "Destination": "/github/home",
                "Mode": "",
                "RW": true,
                "Propagation": "rprivate"
            },
            {
                "Type": "bind",
                "Source": "/nvme/actions-runner/_work/_temp/_github_workflow",
                "Destination": "/github/workflow",
                "Mode": "",
                "RW": true,
                "Propagation": "rprivate"
            },
            {
                "Type": "bind",
                "Source": "/var/run/docker.sock",
                "Destination": "/var/run/docker.sock",
                "Mode": "",
                "RW": true,
                "Propagation": "rprivate"
            },
            {
                "Type": "bind",
                "Source": "/nvme/actions-runner/_work",
                "Destination": "/__w",
                "Mode": "",
                "RW": true,
                "Propagation": "rprivate"
            },
            {
                "Type": "bind",
                "Source": "/nvme/actions-runner/externals",
                "Destination": "/__e",
                "Mode": "ro",
                "RW": false,
                "Propagation": "rprivate"
            },
            {
                "Type": "bind",
                "Source": "/nvme/actions-runner/_work/_temp",
                "Destination": "/__w/_temp",
                "Mode": "",
                "RW": true,
                "Propagation": "rprivate"
            }
        ],
        "Config": {
            "Hostname": "ccfbcaf1fe27",
            "Domainname": "",
            "User": "nonroot:nonroot",
            "AttachStdin": false,
            "AttachStdout": true,
            "AttachStderr": true,
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "HOME=/github/home",
                "GITHUB_ACTIONS=true",
                "CI=true",
                "PATH=/home/nonroot/.cargo/bin:/home/nonroot/.pyenv/shims:/home/nonroot/.pyenv/bin:/home/nonroot/.poetry/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
                "PROTOC_VERSION=25.1",
                "LLVM_VERSION=17",
                "MOLD_VERSION=v2.4.0",
                "PYTHON_VERSION=3.9.2",
                "PYENV_ROOT=/home/nonroot/.pyenv",
                "RUSTC_VERSION=1.75.0",
                "RUSTUP_HOME=/home/nonroot/.rustup",
                "RUSTC_WRAPPER=cachepot"
            ],
            "Cmd": [
                "-f",
                "/dev/null"
            ],
            "Image": "369495373322.dkr.ecr.eu-central-1.amazonaws.com/build-tools:pinned",
            "Volumes": null,
            "WorkingDir": "/__w/neon/neon",
            "Entrypoint": [
                "tail"
            ],
            "OnBuild": null,
            "Labels": {
                "a4c698": ""
            }
        },
        "NetworkSettings": {
            "Bridge": "",
            "SandboxID": "92129d5bc07ff3b789e10bde93da10aed1b7eff78c27d34b82dedddcd2941a1e",
            "HairpinMode": false,
            "LinkLocalIPv6Address": "",
            "LinkLocalIPv6PrefixLen": 0,
            "Ports": {},
            "SandboxKey": "/var/run/docker/netns/92129d5bc07f",
            "SecondaryIPAddresses": null,
            "SecondaryIPv6Addresses": null,
            "EndpointID": "",
            "Gateway": "",
            "GlobalIPv6Address": "",
            "GlobalIPv6PrefixLen": 0,
            "IPAddress": "",
            "IPPrefixLen": 0,
            "IPv6Gateway": "",
            "MacAddress": "",
            "Networks": {
                "github_network_00b20236af194781ae90e7e9b29a2db8": {
                    "IPAMConfig": null,
                    "Links": null,
                    "Aliases": [
                        "ccfbcaf1fe27"
                    ],
                    "NetworkID": "c636e6dd055824f26c8dfdea40538dedd3b3e7537daa1768cd2e6905d9f414a8",
                    "EndpointID": "a79fa3902f3411392968a65fda780da98423b283e89c0ff65ddc7133dd378ce4",
                    "Gateway": "192.168.192.1",
                    "IPAddress": "192.168.192.2",
                    "IPPrefixLen": 20,
                    "IPv6Gateway": "",
                    "GlobalIPv6Address": "",
                    "GlobalIPv6PrefixLen": 0,
                    "MacAddress": "02:42:c0:a8:c0:02",
                    "DriverOpts": null
                }
            }
        }
    }
]
```

```
root@large-03 ~ # du -hs /nvme/actions-runner/_work/neon/neon
53G	/nvme/actions-runner/_work/neon/neon
root@large-03 ~ # du -hs /nvme/actions-runner/_work/neon/neon/target
48G	/nvme/actions-runner/_work/neon/neon/target
root@large-03 ~ # du -hs /nvme/actions-runner/_work/neon/neon/target^C
root@large-03 ~ # df -h
Filesystem      Size  Used Avail Use% Mounted on
udev             63G     0   63G   0% /dev
tmpfs            13G  1.2M   13G   1% /run
/dev/md2        2.0T  161G  1.7T   9% /
tmpfs            63G  8.0K   63G   1% /dev/shm
tmpfs           5.0M     0  5.0M   0% /run/lock
/dev/md1        989M   60M  879M   7% /boot
/dev/md3        1.5T  2.0G  1.5T   1% /home
overlay         2.0T  161G  1.7T   9% /var/lib/docker/overlay2/66f86d4f35afa2bd89c404671d66972ef9b6d21c5059a00883ad114aa8ee4f58/merged
```

</details>


```
root@large-03 ~ # tar -acf target.tar.zstd /nvme/actions-runner/_work/neon/neon
```

Creating additional coredumps, then uploading all that stuff to my devbox for further analysis.

**Comment by problame** [comment]
These coredumps had the problem

```
  47   Thread 0x7fb3f1088700 (LWP 125096)           warning: Couldn't find general-purpose registers in core file.
```

Getting them from inside the CI container again


```
root@large-03 ~ # docker exec -it --user root ccfbcaf1fe27 bash

root@ccfbcaf1fe27:/__w/neon/neon# apt update

root@ccfbcaf1fe27:/__w/neon/neon# apt install gdb

root@ccfbcaf1fe27:/__w/neon/neon# ps aux
USER         PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
nonroot        1  0.0  0.0   1048     0 ?        Ss   14:47   0:00 /sbin/docker-init -- tail -f /dev/null
nonroot        7  0.0  0.0   2424   460 ?        S    14:47   0:00 tail -f /dev/null
nonroot   121254  0.0  0.0   3896  2648 ?        Ss   14:50   0:00 bash -euxo pipefail /__w/_temp/fd57d9cf-7756-45a3-9da5-cda9cd886b7e.sh
nonroot   124551  0.0  0.0  19700 15752 ?        S    14:51   0:00 /home/nonroot/.pyenv/versions/3.9.2/bin/python3 scripts/coverage --profraw-prefix=build-neon --dir=/tmp/coverage
nonroot   124599  0.0  0.0 2198068 31440 ?       Sl   14:51   0:00 /home/nonroot/.cargo/bin/cargo-nextest nextest run --locked --features testing
nonroot   124929  0.2  1.0 3667628 1356088 ?     SLl  14:51   0:31 /__w/neon/neon/target/debug/deps/pageserver-c0c5212b92ba45c9 --exact tenant::remote_timeline_client::tests::inde
nonroot   124950  0.2  1.0 3667628 1355336 ?     SLl  14:51   0:31 /__w/neon/neon/target/debug/deps/pageserver-c0c5212b92ba45c9 --exact tenant::tests::test_images --nocapture
nonroot   125006  0.2  1.0 3667628 1357260 ?     SLl  14:51   0:31 /__w/neon/neon/target/debug/deps/pageserver-c0c5212b92ba45c9 --exact tenant::timeline::walreceiver::connection_m
root      125133  0.0  0.0   4160  3388 pts/1    Ss   18:35   0:00 bash
root      125699  0.0  0.0   6756  2836 pts/1    R+   18:35   0:00 ps aux

root@ccfbcaf1fe27:/__w/neon/neon# gcore 124929
ptrace: Operation not permitted.
You can't do that without a process to debug.
The program is not being run.
gcore: failed to create core.124929
```

😢

**Comment by problame** [comment]
https://yoheimuta.medium.com/debugging-gke-unprivileged-containers-with-gdb-and-nsenter-3760b50eb03a


```
root      278026  0.0  0.0 712456 16156 ?        Sl   15:47   0:01 /usr/bin/containerd-shim-runc-v2 -namespace moby -id ccfbcaf1fe273fb13cca48d0eabe34eeeaa2b0df25fb39143ac4f0d23ea
nonroot   278046  0.0  0.0   1048     0 ?        Ss   15:47   0:00  \_ /sbin/docker-init -- tail -f /dev/null
nonroot   278077  0.0  0.0   2424   460 ?        S    15:47   0:00  |   \_ tail -f /dev/null
nonroot   399924  0.0  0.0   3896  2648 ?        Ss   15:50   0:00  \_ bash -euxo pipefail /__w/_temp/fd57d9cf-7756-45a3-9da5-cda9cd886b7e.sh
nonroot   403240  0.0  0.0  19700 15752 ?        S    15:51   0:00      \_ /home/nonroot/.pyenv/versions/3.9.2/bin/python3 scripts/coverage --profraw-prefix=build-neon --dir=/tmp/
nonroot   403288  0.0  0.0 2198068 31440 ?       Sl   15:51   0:00          \_ /home/nonroot/.cargo/bin/cargo-nextest nextest run --locked --features testing
nonroot   403635  0.2  1.0 3667628 1356088 ?     SLl  15:51   0:31              \_ /__w/neon/neon/target/debug/deps/pageserver-c0c5212b92ba45c9 --exact tenant::remote_timeline_cli
nonroot   403656  0.2  1.0 3667628 1355336 ?     SLl  15:51   0:31              \_ /__w/neon/neon/target/debug/deps/pageserver-c0c5212b92ba45c9 --exact tenant::tests::test_images
nonroot   403712  0.2  1.0 3667628 1357260 ?     SLl  15:51   0:31              \_ /__w/neon/neon/target/debug/deps/pageserver-c0c5212b92ba45c9 --exact tenant::timeline::walreceiv
```

```
root@large-03 ~ # nsenter --mount --net --pid --target 403635 bash
```


```
    6  cd /__w/neon/neon/
    7  ls
    8  ps aux
    9  gcore 124929
   10  ps aux
   11  gcore 124950
   12  gcore 125006
```

```
exit
```

```
root@large-03 ~ # ls /nvme/actions-runner/_work/neon/neon/
.cargo/                   CODEOWNERS                Makefile                  deny.toml                 proxy/                    target/
.config/                  CONTRIBUTING.md           NOTICE                    docker-compose/           pyproject.toml            test_output/
.dockerignore             Cargo.lock                README.md                 docs/                     pytest.ini                test_runner/
.git/                     Cargo.toml                clippy.toml               libs/                     run_clippy.sh             tmp_check/
.git-blame-ignore-revs    Dockerfile                compute_tools/            pageserver/               rust-toolchain.toml       trace/
.github/                  Dockerfile.buildtools     control_plane/            pg_install/               s3_scrubber/              vendor/
.gitignore                Dockerfile.compute-node   core.124929               pgxn/                     safekeeper/               vm-image-spec.yaml
.gitmodules               Dockerfile.compute-tools  core.124950               poetry.lock               scripts/                  workspace_hack/
.neon_clippy_args         LICENSE                   core.125006               pre-commit.py             storage_broker/
root@large-03 ~ # tar -cf newcores.tar.zstd /nvme/actions-runner/_work/neon/neon/core.*
```

Extract tarball on devbox.

These mysterious threads don't exist there, I guess that's a good sign.

Will debug tomorrow.

**Comment by problame** [comment]
Cancelled the runner to free it up for others.

**Comment by problame** [comment]
Tried to gather information from the coredumps together with @koivunej 

Looking at coredump


```
root@1ae3ef446dcd:/__w/neon/neon# rust-gdb target/debug/deps/pageserver-c0c5212b92ba45c9 /pwd/newcores/nvme/actions-runner/_work/neon/neon/core.124950
(gdb) info threads
  Id   Target Id                          Frame
  1    Thread 0x7f036a9f0e00 (LWP 124950) syscall () at ../sysdeps/unix/sysv/linux/x86_64/syscall.S:38
  2    Thread 0x7f036a9ef700 (LWP 124960) 0x00007f036aaf0d56 in epoll_wait (epfd=3, events=0x7f0364000c40, maxevents=1024, timeout=80) at ../sysdeps/unix/sysv/linux/epoll_wait.c:30
  3    Thread 0x7f036a5e6700 (LWP 125031) 0x00007f036aaf0d56 in epoll_wait (epfd=11, events=0x7f0364095cd0, maxevents=1024, timeout=-1) at ../sysdeps/unix/sysv/linux/epoll_wait.c:30
* 4    Thread 0x7f036a3e2700 (LWP 125032) syscall () at ../sysdeps/unix/sysv/linux/x86_64/syscall.S:38
...
  34   Thread 0x7f031a5f2700 (LWP 125075) syscall () at ../sysdeps/unix/sysv/linux/x86_64/syscall.S:38
```

We don't understand why there are two threads that do `epoll_wait` in this test, which is a [tokio::test] that uses the current_thread_runtime.

The other threads are from the blocking pool, attaching the output of 

```
root@1ae3ef446dcd:/__w/neon/neon# rust-gdb -ex 'thread apply all bt full' -ex quit target/debug/deps/pageserver-c0c5212b92ba45c9 /pwd/newcores/nvme/actions-runner/_work/neon/neon/core.124950  > /pwd/backtraces.txt
```

to this message.


There's no reasonably feasible way to get to the tokio state for not-runnable tasks; presumably we'd be able to get the `mio` state from the epoll_event's data field, then go from the `mio` state to some pointer to tokio's representation of the task.

(Essentially we need Go's `dlv` but for tokio here)


As an alternative to the coredumps, having log files on disk for the in-progress tests would have been helpful; we do log, and I think we do setup the `util::logging::...` stuff for all the tests that use `TenantHarness`. The log messages would have helped us reconstruct in what state the task was.
=> https://github.com/neondatabase/neon/issues/6368

**Comment by problame** [comment]
Above investigation was inconclusive, but, not related to this PR, so merging it into the integration branch.

**Comment by problame** [comment]
For posterity, further investigation efforts will be tracked in https://github.com/neondatabase/neon/issues/6373

**Pull request merged**
