### PR TITLE
Bump Postgres  version

### PR DESCRIPTION
**Pull request by knizhnik**

### CODE REVIEW

**Comment by hlinnaka** [comment]
Is this ready to be merged? This brings in the revert of the last-written-lsn cache patch, right?

**Comment by knizhnik** [comment]
> Is this ready to be merged? This brings in the revert of the last-written-lsn cache patch, right?

I can not merge it without review.

**Comment by hlinnaka** [comment]
> -Subproject commit 9c99008445dbccd8204f188e0933def507058eac
> +Subproject commit 4e3c69e25813633279e798e4a206f0094e7228ba

The new commit hash doesn't match with the current HEAD of `postgres` repository's `main` branch. Please update it.

**Comment by hlinnaka** [comment]
> > -Subproject commit 9c99008445dbccd8204f188e0933def507058eac
> > +Subproject commit 4e3c69e25813633279e798e4a206f0094e7228ba
> 
> The new commit hash doesn't match with the current HEAD of `postgres` repository's `main` branch. Please update it.

Never mind, I just did that myself. Let's wait for the CI to finish, and assuming it's green, let's push.

**Review by hlinnaka — APPROVED** [review]

**Pull request merged**
