### PR TITLE
Upload Postgres Extensions to S3

### PR DESCRIPTION
**Pull request by bayandin**
## Problem

We want to store Postgres Extensions in S3 (resolves https://github.com/neondatabase/neon/issues/4493).

Proposed solution:
- Create a separate docker image (from scratch) that contains only extensions
- Do not include extensions into compute-node (except for neon extensions)*
- For release and main builds upload extract extension from the image and upload to S3 (`s3://<bucket>/<release version>/<postgres_version>/...`)**

An example of S3 layout: https://s3.console.aws.amazon.com/s3/buckets/neon-dev-extensions?region=eu-central-1&prefix=5314225671/&showversions=false

*) We're not doing it until the feature is not fully implemented
**) This differs from the initial proposal in https://github.com/neondatabase/neon/issues/4493 of putting extensions straight into `s3://<bucket>/<postgres_version>/...`, because we can't upload directory atomicly. A drawback of this is that we end up with unnecessary copies of files ~2.1 GB per release (i.e. +2.1 GB for each commit in main also). We don't really need to update extensions for each release if there're no relevant changes, but this requires extra work.

## Summary of changes
- Created a separate stage in Dockerfile.compute-node `postgres-extensions` that contains only extensions
- Added a separate step in a workflow that builds `postgres-extensions` image (because of a bug in kaniko this step is commented out because it takes way too long to get built)
- Extract extensions from the image and upload files to S3 for release and main builds
- Upload extenstions only for staging (for now)

## Checklist before requesting a review

- [x] I have performed a self-review of my code.
- [ ] If it is a core feature, I have added thorough tests.
- [ ] Do we need to implement analytics? if so did you add the relevant metrics to the dashboard?
- [ ] If this PR requires public announcement, mark it with /release-notes label and add several sentences in this section.

## Checklist before merging

- [ ] Do not forget to reformat commit message to not include the above checklist

### CODE REVIEW

**Review by lubennikovaav — APPROVED** [review]
looks good to me,
except for the lack of a cleanup

**Comment by lubennikovaav** [comment]
>Remove uploading to s3 for each commit (uncomment if's in a workflow)

How will we version them? 
Current logic is for each build there is a build_tag and compute_ctl searches for respective ext "subdir".  Should we introduce some new `ext_build_tag` env variable and pass it to `compute_ctl` ?

Or we can add a fallback to earlier versions, if `build_tag` version is not found.

**Comment by bayandin** [comment]
> > Remove uploading to s3 for each commit (uncomment if's in a workflow)
>
> How will we version them?

They're versioned by `build-tag` (staging builds for each commit, production builds for each release). My comment is rather about testing in this PR.

> Should we introduce some new ext_build_tag env variable and pass it to compute_ctl ?

I think it's not required and everything is covered by https://github.com/neondatabase/neon/pull/4541

> Or we can add a fallback to earlier versions, if build_tag version is not found

The proposed implementation always uploads extensions, so it's not possible (in regular circumstances) that we need exact extensions in S3 for a new version.

**Comment by lubennikovaav** [comment]
>The proposed implementation always uploads extensions, so it's not possible (in regular circumstances) that we need exact extensions in S3 for a new version.

Yep, I meant some future optimizations, when we won't upload them for every commit.

**Pull request merged**
