### PR TITLE
Add HNSW extension

### PR DESCRIPTION
**Pull request by knizhnik**
## Describe your changes

Port HNSW implementation for ANN search top Postgres 

## Issue ticket number and link

https://www.pinecone.io/learn/hnsw

## Checklist before requesting a review

- [ ] I have performed a self-review of my code.
- [ ] If it is a core feature, I have added thorough tests.
- [ ] Do we need to implement analytics? if so did you add the relevant metrics to the dashboard?
- [ ] If this PR requires public announcement, mark it with /release-notes label and add several sentences in this section.

## Checklist before merging

- [ ] Do not forget to reformat commit message to not include the above checklist

### CODE REVIEW

**Comment by vadim2404** [comment]
To allow installation of this extension, you need to compile in the compute docker image and mark it as trusted

**Comment by knizhnik** [comment]
> To allow installation of this extension, you need to compile in the compute docker image and mark it as trusted

Is is marked as trusted in control file.
Concerning buildig docker image - I do not understand: it is part of postgres, we are not building docker image for example for `neon` extension, are we?

**Comment by vadim2404** [comment]
> > To allow installation of this extension, you need to compile in the compute docker image and mark it as trusted
> 
> Is is marked as trusted in control file. Concerning buildig docker image - I do not understand: it is part of postgres, we are not building docker image for example for `neon` extension, are we?

We are. https://github.com/neondatabase/neon/blob/main/Dockerfile.compute-node#L534

**Review by save-buffer — APPROVED** [review]
Overall looks good to me. Couple questions:
- Why does this need to be inside of `neon/pgxn` instead of having Dockerfile download a tarball and installing it that way?
- Assuming it does need to be inside of `pgxn`, would it make sense to add this library as a git submodule so we can easily update it?

**Comment by knizhnik** [comment]
> Why does this need to be inside of neon/pgxn instead of having Dockerfile download a tarball and installing it that way?

Just because it's simpler:) What do we win by moving this extension to separate docker file? Save few kilobytes of code? But it is shared library which is loaded on demand... Increase build time? 99% of build time we spent in building Rust code...

> Assuming it does need to be inside of pgxn, would it make sense to add this library as a git submodule so we can easily update it?

Once again - why? We use submodules for code which is taken or is based on the code taken from other sources. Here all the code is written by us...

So may be I am missing something but I do not see any reasons of why do we need to exclude this code from `neon` project. Definitely most of Neon users do  not need this extension. But as far as there is almost no overhead whats wrong with having it here?

**Comment by save-buffer** [comment]
Ah what I was missing was that we wrote this code ourselves - I thought this was an external library. In that case I'm happy merging it here.

**Pull request merged**
