### PR TITLE
Run real Azure tests on CI

### LINKED ISSUE #5565: test test_real_azure.rs in CI
PR #5546 has added support for azure blob storage, including a `test_real_azure.rs` file with various tests, similar to the `test_real_s3.rs` file. These tests can be run locally but should also be ran in CI.

Part of #5567.

### PR DESCRIPTION
**Pull request by bayandin**
## Problem
We do not run real Azure related tests on CI 

Closes #5565

## Summary of changes
- Set required env variables to run real Azure blob storage tests on CI

## Checklist before requesting a review

- [x] I have performed a self-review of my code.
- [ ] If it is a core feature, I have added thorough tests.
- [ ] Do we need to implement analytics? if so did you add the relevant metrics to the dashboard?
- [ ] If this PR requires public announcement, mark it with /release-notes label and add several sentences in this section.

## Checklist before merging

- [ ] Do not forget to reformat commit message to not include the above checklist

### CODE REVIEW

**Comment by bayandin** [comment]
Hmm, despite setting env vars, tests didn't run. [The coverage report](https://neon-github-public-dev.s3.amazonaws.com/code-coverage/232ac50792968f469674077b383f58765df7ba47/lcov/libs/remote_storage/src/azure_blob.rs.gcov.html) also shows that no lines from `azure_blob.rs` were run. 

The only difference from suggested in https://github.com/neondatabase/neon/pull/5546 way of running tests is that instead of `cargo test -p remote_storage azure` I use `cargo test -p remote_storage --test test_real_azure` (to make it inline with s3 remove tests)

**Review by arpad-m — APPROVED** [review]

**Review by shanyp — APPROVED** [review]

**Comment by arpad-m** [comment]
> test azure_pagination_should_work ... ok


These tests will be shown as ignored if `ENABLE_REAL_AZURE_REMOTE_STORAGE` is set or not, as we just return if the env var is not set. *however* I see that there is activity in the `neon-github-sandbox` container, so the tests do work.

**Comment by bayandin** [comment]
> > test azure_pagination_should_work ... ok
> 
> These tests will be shown as ignored if `ENABLE_REAL_AZURE_REMOTE_STORAGE` is set or not, as we just return if the env var is not set. _however_ I see that there is activity in the `neon-github-sandbox` container, so the tests do work.

I see unignored azure tests in the main (when we don't have `ENABLE_REAL_AZURE_REMOTE_STORAGE` set yet)

```
     Running tests/test_real_azure.rs (target/release/deps/test_real_azure-1f7a157224e0b2cf)

running 5 tests
test azure_pagination_should_work ... ok
test azure_delete_objects_works ... ok
test azure_list_files_works ... ok
test azure_upload_download_works ... ok
test azure_delete_non_exising_works ... ok

test result: ok. 5 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s
```

https://github.com/neondatabase/neon/actions/runs/6617252454/job/17973190041#step:19:428

**Comment by arpad-m** [comment]
Sorry I meant to write "the test will be shown as *unignored* if `ENABLE_REAL_AZURE_REMOTE_STORAGE` is set or not".

**Pull request merged**
