### PR TITLE
test_runner: add visibility map test

### PR DESCRIPTION
**Pull request by erikgrinaker**
Verifies that visibility map pages are correctly maintained across shards.

Touches #9914.

### CODE REVIEW

**Comment by erikgrinaker** [comment]
@arssher Mind having a quick look at this?

**Review by arssher — APPROVED** [review]
Do IIUC that the test worked before and after https://github.com/neondatabase/neon/pull/9895 ?
i.e. it doesn't reveal any real problem?

Also note existence of test_vm_bits.py, I think the test should go there.

**Comment by arssher** [comment]
> Mind having a quick look at this?

missed it earlier, sorry

**Comment by erikgrinaker** [comment]
>Do IIUC that the test worked before and after https://github.com/neondatabase/neon/pull/9895 ?

That's right, #9895 was not a correctness problem.

>Also note existence of test_vm_bits.py, I think the test should go there.

Good call, done.

**Pull request merged**
