### PR TITLE
Use valid type hints for Python 3.9

### PR DESCRIPTION
**Pull request by tristan957**
I have no idea how this made it past the linters.

### CODE REVIEW

**Review by bayandin — COMMENTED** [review]
We have one more `| None`:
```
test_runner/fixtures/pageserver/http.py:        batch_size: int | None = None,
```

**Comment by bayandin** [comment]
I am not sure why neither `mypy` nor the Python parser complain about it.

```
bayandin@mbp neon % poetry run python3 --version
Python 3.9.20
bayandin@mbp neon % poetry run mypy --python-version 3.9 test_runner/fixtures/pageserver/http.py
Success: no issues found in 1 source file
```

**Comment by tristan957** [comment]
I had `ruff check` finding these issues, so I'm pretty confused, and I had rebased on main since my ruff changes PR went in.

**Review by bayandin — APPROVED** [review]

**Comment by bayandin** [comment]
> Note that a stub file can [sometimes make use of a typing feature](https://typing.readthedocs.io/en/latest/spec/distributing.html#syntax) before it is available at runtime, as long as the stub does not make use of new syntax. For example, a type checker will understand `int | str` in a stub as being a `Union` type annotation, even if the type checker is run using Python 3.9, despite the fact that the `|` operator can only be used to create union types at runtime on Python 3.10+. As such, Ruff will often recommend newer features in a stub file than it would for an equivalent runtime file with the same target version.

from https://docs.astral.sh/ruff/settings/#target-version

**Comment by tristan957** [comment]
hmm, but these are not stub files.

**Pull request merged**
