### PR TITLE
Bump werkzeug from 2.1.2 to 2.2.3

### PR DESCRIPTION
**Pull request by bayandin**
## Describe your changes

```
$ poetry add werkzeug@latest "moto[server]@latest"
Using version ^2.2.3 for werkzeug
Using version ^4.1.2 for moto

Updating dependencies
Resolving dependencies... (1.6s)

Writing lock file

Package operations: 0 installs, 2 updates, 1 removal

  • Removing pytz (2022.1)
  • Updating werkzeug (2.1.2 -> 2.2.3)
  • Updating moto (3.1.18 -> 4.1.2)
```

Resolves:
- https://github.com/neondatabase/neon/security/dependabot/14
- https://github.com/neondatabase/neon/security/dependabot/13

`@dependabot` failed to create a PR for some reason (I guess because it also needed to handle `moto` dependency)

## Issue ticket number and link
N/A

## Checklist before requesting a review
- [x] I have performed a self-review of my code.
- [x] If it is a core feature, I have added thorough tests.
- [x] Do we need to implement analytics? if so did you add the relevant metrics to the dashboard?
- [x] If this PR requires public announcement, mark it with /release-notes label and add several sentences in this section.

### CODE REVIEW

**Comment by koivunej** [comment]
Fixing test_runner/regress/test_ondemand_download.py::test_compaction_downloads_on_demand_without_image_creation in #3629, it should be transient, but there were surpsingly many failures.

**Comment by koivunej** [comment]
mock_s3 related possibly?
```
2023-02-16T18:09:04.345371Z  WARN remote_upload{tenant=7167364c73ffa4337c1bb0d20dfa2d65 timeline=374e52edfd5ee3d57462cbbed12d7491 upload_task_id=1}: failed to perform remote task UploadLayer(000000000000000000000000000000000000-FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF__0000000001696070-00000000016960E9, size=Some(25575424)), will retry (attempt 3): Failed to upload a layer from local path '/tmp/test_output/test_pageserver_metrics_removed_after_detach[mock_s3]/repo/tenants/7167364c73ffa4337c1bb0d20dfa2d65/timelines/374e52edfd5ee3d57462cbbed12d7491/000000000000000000000000000000000000-FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF__0000000001696070-00000000016960E9'

Caused by:
    0: Error parsing XML: no root element
    1: Error parsing XML: no root element
    2: Error parsing XML: no root element
```

All failures are mock_s3, none real_s3.

**Comment by bayandin** [comment]
> mock_s3 related possibly?
> 
> ```
> 2023-02-16T18:09:04.345371Z  WARN remote_upload{tenant=7167364c73ffa4337c1bb0d20dfa2d65 timeline=374e52edfd5ee3d57462cbbed12d7491 upload_task_id=1}: failed to perform remote task UploadLayer(000000000000000000000000000000000000-FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF__0000000001696070-00000000016960E9, size=Some(25575424)), will retry (attempt 3): Failed to upload a layer from local path '/tmp/test_output/test_pageserver_metrics_removed_after_detach[mock_s3]/repo/tenants/7167364c73ffa4337c1bb0d20dfa2d65/timelines/374e52edfd5ee3d57462cbbed12d7491/000000000000000000000000000000000000-FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF__0000000001696070-00000000016960E9'
> 
> Caused by:
>     0: Error parsing XML: no root element
>     1: Error parsing XML: no root element
>     2: Error parsing XML: no root element
> ```
> 
> All failures are mock_s3, none real_s3.

Yep, looks like it was caused by downgrading `moto`, I'll have a look, thanks!

**Comment by bayandin** [comment]
Updated `moto` to the latest version as well. It fixed `mock_s3` tests for me, let's see the CI

**Review by koivunej — APPROVED** [review]
Thanks for this, getting rid of the security warning is great (on push) and green/blue ci sounds good enough. Checked moto 3 -> 4 was because of removing stuff mostly: https://github.com/getmoto/moto/blob/master/CHANGELOG.md

**Pull request merged**
