### PR TITLE
Do not hold timelines lock while calling update_gc_info to avoid recu…

### PR DESCRIPTION
**Pull request by knizhnik**
…srive mutex lock and so deadlock

### CODE REVIEW

**Comment by hlinnaka** [comment]
Not safe, there's a race condition with branch creation. A new branch might be created, after you have collected the list of all branch points, but before you update gc info. You might then garbage collect away data that is needed by the new branch.

See discussion at https://github.com/neondatabase/neon/pull/2101

**Comment by hlinnaka** [comment]
> Not safe, there's a race condition with branch creation. A new branch might be created, after you have collected the list of all branch points, but before you update gc info. You might then garbage collect away data that is needed by the new branch.
> 
> See discussion at #2101

Hmm, we do hold the `gc_cs` lock, though. I'm confused, I thought we would no longer. So maybe it's OK? WDYT @aome510 ?

**Review by aome510 — APPROVED** [review]
> Hmm, we do hold the gc_cs lock, though. So maybe it's OK?

GC lock should prevent the branch creation between. Changes LGTM. Thanks for noticing this. 

Recursive lock is tricky and I got bitten by it sometimes, so it's still better to avoid if possible.

**Comment by hlinnaka** [comment]
https://github.com/neondatabase/neon/pull/2154 actually allows getting rid of the `tenant_mgr::get_local_timeline_with_load` call, so that also fixes the deadlock-hazard. But if this PR is safe, it makes sense to commit it in any case, to avoid holding locks longer than necessary.

**Pull request merged**
