### PR TITLE
Release 2023-08-31

### PR DESCRIPTION
**Pull request by lubennikovaav**

### CODE REVIEW

**Comment by lubennikovaav** [comment]
`build-and-upload-extensions` failed with

```
Error response from daemon: Conflict. The container name "/postgres-extensions" is already in use by container "5e2a5b8714d22fc42486d3b719ebe637fa20114ddd7c7cacf5be1ac686e11e95". You have to remove (or rename) that container to be able to reuse that name.
```

@bayandin, can you take a look?

**Comment by bayandin** [comment]
> `build-and-upload-extensions` failed with
> 
> ```
> Error response from daemon: Conflict. The container name "/postgres-extensions" is already in use by container "5e2a5b8714d22fc42486d3b719ebe637fa20114ddd7c7cacf5be1ac686e11e95". You have to remove (or rename) that container to be able to reuse that name.
> ```
> 
> @bayandin, can you take a look?

A container `postgres-extensions` wasn't deleted in a previous run. I've deleted it manually (`sudo docker rm postgres-extensions`) and have restarted the job.

Will create a PR to prevent such cases in the future

**Review by awestover — APPROVED** [review]
looks good

**Comment by danieltprice** [comment]
Noted the password workaround enhancement here:
https://neon.tech/docs/release-notes/2023-08-31-storage-and-compute

Support for custom-built extensions is mentioned in this release note:
https://neon.tech/docs/release-notes/2023-09-05-storage-and-compute

I don't see any other items in this release to document in the external release notes. Please let me know if I missed something.

**Pull request merged**
