### PR TITLE
Release 22-12-08

### PR DESCRIPTION
**Pull request by MMeent**
## Release 2022-12-08

**NB: this PR must be merged only by 'Create a merge commit'!**

### Checklist when preparing for release
- [x] Read or refresh [the release flow guide](https://github.com/neondatabase/cloud/wiki/Release:-general-flow)
- [x] Ask in the [cloud Slack channel](https://neondb.slack.com/archives/C033A2WE6BZ) that you are going to rollout the release. Any blockers?
    - [x] https://github.com/neondatabase/neon/pull/3034
    - [x] https://github.com/neondatabase/neon/pull/3037
    - [x] Staging deployment is broken, so lets wait until it gets healthy again
- [x] Does this release contain any db migrations? Destructive ones? What is the rollback plan?

### Checklist after release
- [ ] Based on the merged commits write release notes and open a PR into `website` repo ([example](https://github.com/neondatabase/website/pull/219/files))
- [ ] Check [#dev-production-stream](https://neondb.slack.com/archives/C03F5SM1N02) Slack channel
- [ ] Check [stuck projects page](https://console.neon.tech/admin/projects?sort=last_active&order=desc&stuck=true)
- [ ] Check [recent operation failures](https://console.neon.tech/admin/operations?action=create_timeline%2Cstart_compute%2Cstop_compute%2Csuspend_compute%2Capply_config%2Cdelete_timeline%2Cdelete_tenant%2Ccreate_branch%2Ccheck_availability&sort=updated_at&order=desc&had_retries=some)
- [ ] Check [cloud SLO dashboard](https://observer.zenith.tech/d/_oWcBMJ7k/cloud-slos?orgId=1)
- [ ] Check [compute startup metrics dashboard](https://observer.zenith.tech/d/5OkYJEmVz/compute-startup-time)

### CODE REVIEW

**Comment by SomeoneToIgnore** [comment]
Staging has a broken storage-broker release: https://github.com/neondatabase/neon/actions/runs/3649564321
AFAIK it's not used yet, but will affect the general deploy status. Might be good to amend those bits before the release though?

**Comment by LizardWizzard** [comment]
Because of the failed deploys cannot verify the fix on staging. Should do that before release

**Comment by LizardWizzard** [comment]
FYI @MMeent I added a point regarding broken deployment to the list of blockers

**Comment by SomeoneToIgnore** [comment]
2 new blockers, related to the CI failures: https://neondb.slack.com/archives/C033RQ5SPDH/p1670887791271759

**Comment by LizardWizzard** [comment]
Deployment is fixed. I've verified that #3034 resolved the problem as expected. So there are no blockers from my side

**Review by vadim2404 — APPROVED** [review]

**Pull request merged**
