### PR TITLE
fix(ci): Allow github-action-script to post reports

### PR DESCRIPTION
**Pull request by rahulinux**
Allow github-action-script to post reports.

Failed CI: https://github.com/neondatabase/neon/actions/runs/12304655364/job/34342554049#step:13:514

### CODE REVIEW

**Review by Bodobolero — APPROVED** [review]
lgtm, let's test it in branch

**Review by bayandin — COMMENTED** [review]
I also noticed that [`benchmarks`](https://github.com/neondatabase/neon/blob/59ef70192591c0fc2a5c2a69eea0d47f7bd8e033/.github/workflows/build_and_test.yml#L303-L304) job in the main fails, let's fix it in this PR as well?

https://github.com/neondatabase/neon/actions/runs/12306697520/job/34352429197

**Comment by rahulinux** [comment]
> I also noticed that [`benchmarks`](https://github.com/neondatabase/neon/blob/59ef70192591c0fc2a5c2a69eea0d47f7bd8e033/.github/workflows/build_and_test.yml#L303-L304) job in the main fails, let's fix it in this PR as well?
> 
> [neondatabase/neon/actions/runs/12306697520/job/34352429197](https://github.com/neondatabase/neon/actions/runs/12306697520/job/34352429197)

Updated.

**Review by bayandin — APPROVED** [review]

**Comment by Bodobolero** [comment]
test run for periodic pagebench from this branch was good https://github.com/neondatabase/neon/actions/runs/12313725891/job/34368363569

**Pull request merged**
