### PR TITLE
Fix bogus at character context in log messages

### PR DESCRIPTION
**Pull request by rmodpur**
## Describe your changes
Fix bogus at character context in log messages

## Issue ticket number and link
#4186

### CODE REVIEW

**Comment by rmodpur** [comment]
@MMeent github actions are failing due to incorrect/absence of credentials
For eg.
`error checking push permissions -- make sure you entered the correct tag name, and that you are authenticated correctly, and try again: checking push permission for "369495373322.dkr.ecr.eu-central-1.amazonaws.com/compute-node-v14:4938923186": resolving authorization for 369495373322.dkr.ecr.eu-central-1.amazonaws.com failed: /kaniko/.docker/config.json: Invalid auth configuration file`

I suspect it may be due to pull request from a fork not having access to secrets in the workflows. Could you pls help ?
Thanks

**Comment by bayandin** [comment]
> I suspect it may be due to pull request from a fork not having access to secrets in the workflows. Could you pls help ?
> Thanks

Yep, that's correct. Our CI is not very friendly 😞 
I will close and reopen the PR to trigger workflows on my behalf.

**Comment by bayandin** [comment]
For some reason, close-reopen didn't help this time, sorry @rmodpur. 
I've created a new PR with your changes https://github.com/neondatabase/neon/pull/4210

**Comment by rmodpur** [comment]
> For some reason, close-reopen didn't help this time, sorry @rmodpur. I've created a new PR with your changes #4210

No worries @bayandin thank you for your effort but even that won't work because the issue is action will assume fork context(thus no access to secrets) when triggering on `pull_request` event. Github has another type of event named `pull_request_target` which assumes the context of main repo even if the PR is from a fork but github doesn't recommend checking out fork code when using that event because it's insecure. I found this article https://dev.to/petrsvihlik/using-environment-protection-rules-to-secure-secrets-when-building-external-forks-with-pullrequesttarget-hci which provides a way to run CI steps with secrets for pull requests from fork repos with some precautions to prevent it's misuse.

**Comment by bayandin** [comment]
The PR has been merged; thanks for your contribution, @rmodpur!
I have a look at the link you shared and will try to make CI more friendly for external contributors.
Meanwhile, feel free to ping me in your PRs, if you have any questions regarding CI.

**Pull request closed without merging**
