### PR TITLE
Fix SLRU download bug, with test

### PR DESCRIPTION
**Pull request by hlinnaka**
While reviewing PR #6416 and wondering why the test could not reproduce the original issue, I spotted this bug with on-demand SLRU download. We used the basebackup's LSN in all the SLRU download requests, but that LSN might get garbage-collected away in the pageserver. We should request the latest LSN, like with GetPage requests, with the LSN just indicating that we know that the page hasn't been changed since the LSN (since the basebackup in this case).

Add test to demonstrate the problem. Without the fix, it fails with "tried to request a page version that was garbage collected" error from the pageserver.

### CODE REVIEW

**Review by knizhnik — APPROVED** [review]
Sorry, I forgot about GC

**Review by knizhnik — CHANGES_REQUESTED** [review]
Sorry, I approved this PR, but then realised that setting `latest=true` will not work for replica. Actually there is no solution of the problem without protocol change (PR #6357)

**Comment by hlinnaka** [comment]
> Sorry, I approved this PR, but then realised that setting `latest=true` will not work for replica. Actually there is no solution of the problem without protocol change (PR #6357)

Why not?

**Comment by hlinnaka** [comment]
> > Sorry, I approved this PR, but then realised that setting `latest=true` will not work for replica. Actually there is no solution of the problem without protocol change (PR #6357)
> 
> Why not?

Oh, for replica, gotcha. Will think some more about this.

**Comment by hlinnaka** [comment]
> > Sorry, I approved this PR, but then realised that setting `latest=true` will not work for replica. Actually there is no solution of the problem without protocol change (PR #6357)
> 
> Why not?

You're right, a replica should indeed not use 'latest'. It should use the current replay LSN like for all other pageeserver requests. I'll fix that.

**Comment by hlinnaka** [comment]
Ok, fixed, and added a test that covers that case too. Please take another look. I refactored the neon_get_request_lsn() function to have a better place for the comments, that refactoring is included as a separate commit.

**Review by knizhnik — APPROVED** [review]

**Comment by hlinnaka** [comment]
This was fixed and the test was added by PR #7377

**Pull request closed without merging**
