### PR TITLE
hyperlink fixes in readme docs

### PR DESCRIPTION
**Pull request by phoenix24**
this pull request fixes few hyperlink in the docs, thereby helping new developers easily navigate the rapidly evolving neon codebase.

the pr also renames a few `readme` files to `readme.md` to enable automatic content recognition by GitHub and allow for beautiful web rendering of the same.

### CODE REVIEW

**Comment by phoenix24** [comment]
ah, looks like [git](https://app.circleci.com/pipelines/github/neondatabase/neon/5873/workflows/14e82ba4-9c07-4294-8175-21a7b0cbf581/jobs/57465) [authorization](https://app.circleci.com/pipelines/github/neondatabase/neon/5873/workflows/14e82ba4-9c07-4294-8175-21a7b0cbf581/jobs/57465) error - I don't think it's anything to do with the commit diff.

CleanShot 2022-04-28 at 23 03 41

**Comment by hlinnaka** [comment]
Hmm, not sure what's going on with that.

I rebased, squashed, and did some copy-editing on the commit message. I force-pushed that to your branch, I hope you don't mind.

If the CI turns green with this, I'll merge this.

**Comment by hlinnaka** [comment]
Pushed, thanks for the fixes!

**Comment by phoenix24** [comment]
thank you!

**Pull request merged**
