### PR TITLE
WIP Image compression

### PR DESCRIPTION
**Pull request by knizhnik**

### CODE REVIEW

**Comment by dhammika** [comment]
Does this affect tests that assume certain layer file sizes from uncompressed storage?

**Comment by knizhnik** [comment]
> Does this affect tests that assume certain layer file sizes from uncompressed storage?

I am not sure that we have such tests now. Especially taken in account that layer format is frequently changed. At least, as you can see - tests are passed.

**Comment by dhammika** [comment]
> > Does this affect tests that assume certain layer file sizes from uncompressed storage?
> 
> I am not sure that we have such tests now. Especially taken in account that layer format is frequently changed. At least, as you can see - tests are passed.

There's `test_timeline_size_quota` test. Guess data set is well over the quota limit even with compression.

**Comment by hlinnaka** [comment]
Two things I'd like to try:

1. zstandard. It's more tunable between fast compression/decompression and compression ratio. 
2. dictionary compression. I think both zstandard and LZ4 can do it, although I'm not sure if the rust APIs expose it. The idea is to do the compression in two passes. First, scan all the blocks and build a dictionary. Then compress each block using the dictionary. Should improve the compression ratio, but I'm very curious to see how much. This could be more important for compressing delta layers than image layers though, as it helps more with small blocks.

We should compress delta layers too, but we can do just image layers first.

**Comment by knizhnik** [comment]
> Two things I'd like to try:
> 
> 1. zstandard. It's more tunable between fast compression/decompression and compression ratio.
> 2. dictionary compression. I think both zstandard and LZ4 can do it, although I'm not sure if the rust APIs expose it. The idea is to do the compression in two passes. First, scan all the blocks and build a dictionary. Then compress each block using the dictionary. Should improve the compression ratio, but I'm very curious to see how much. This could be more important for compressing delta layers than image layers though, as it helps more with small blocks.
> 
> We should compress delta layers too, but we can do just image layers first.

1. This OR includes zstd as one of implementation (I have not add switch between zstd and lz4, just it is necessary to uncomment correspondent lines of of code).
2. It is quite easy to estimate: switch on page-level compression (without dictionary) and compare total size of image layers with total size of image layers produced without compression and then compressed using normal command line compressor (as file). The main problem IMHO is to find representative data set. Because investigating compression on pgbench database (with its dummy populated data) has very relation to real world.

I do not think that dictionary compression is really good idea. You should process each page twice: first to build the dictionary and second to actually compress page. It will almost double time of writing image layer. And each access to the page requires reading two parts: compressed image and dictionary.

**Comment by hlinnaka** [comment]
https://github.com/neondatabase/neon/pull/1595 is more up-to-date than this PR, closing this one

**Pull request closed without merging**
