### PR TITLE
Release 2024-02-27

### PR DESCRIPTION
**Pull request by problame**
(Manually created PR)

Release 2024-02-26 (#6901) was not shipped due to several issues.
Fixes are cherry-picked into this PR.

## Release 2027-02-27

**NB: this PR must be merged only by 'Create a merge commit'!**

### Checklist when preparing for release
- [ ] Read or refresh [the release flow guide](https://www.notion.so/neondatabase/Release-general-flow-61f2e39fd45d4d14a70c7749604bd70b)
- [ ] Ask in the [cloud Slack channel](https://neondb.slack.com/archives/C033A2WE6BZ) that you are going to rollout the release. Any blockers?
- [ ] Does this release contain any db migrations? Destructive ones? What is the rollback plan?

### Checklist after release
- [ ] Make sure instructions from PRs included in this release and labeled `manual_release_instructions` are executed (either by you or by people who wrote them).
- [ ] Based on the merged commits write release notes and open a PR into `website` repo ([example](https://github.com/neondatabase/website/pull/219/files))
- [ ] Check [#dev-production-stream](https://neondb.slack.com/archives/C03F5SM1N02) Slack channel
- [ ] Check [stuck projects page](https://console.neon.tech/admin/projects?sort=last_active&order=desc&stuck=true)
- [ ] Check [recent operation failures](https://console.neon.tech/admin/operations?action=create_timeline%2Cstart_compute%2Cstop_compute%2Csuspend_compute%2Capply_config%2Cdelete_timeline%2Cdelete_tenant%2Ccreate_branch%2Ccheck_availability&sort=updated_at&order=desc&had_retries=some)
- [ ] Check [cloud SLO dashboard](https://neonprod.grafana.net/d/_oWcBMJ7k/cloud-slos?orgId=1)
- [ ] Check [compute startup metrics dashboard](https://neonprod.grafana.net/d/5OkYJEmVz/compute-startup-time)

### CODE REVIEW

**Comment by koivunej** [comment]
I cancelled the test-images after some 3h, created https://github.com/neondatabase/neon/pull/6942

**Review by koivunej — APPROVED** [review]
layer eviction changes are harmless; without this fix the release is much more dangerious.

since the tests pass except compatibility pass, revert must have been good.

**Comment by arpad-m** [comment]
There seems to be a test failure for the forward compat test:

```
AssertionError: assert not [(107, '2024-02-27T22:35:37.448127Z  WARN wal_connection_manager{tenant_id=7b75f8ca0c1003fe679276e1478c1015 shard_id=0000 timeline_id=f7d34518a4d64f67e4fb1498da81b331}:connection{node_id=3}: Flushed oversized open layer with size 268440352\n')]
```

Also, we wanted to cherry-pick some of @skyzh 's fixes, right?

**Comment by problame** [comment]
> There seems to be a test failure for the forward compat test:
> 
> ```
> AssertionError: assert not [(107, '2024-02-27T22:35:37.448127Z  WARN wal_connection_manager{tenant_id=7b75f8ca0c1003fe679276e1478c1015 shard_id=0000 timeline_id=f7d34518a4d64f67e4fb1498da81b331}:connection{node_id=3}: Flushed oversized open layer with size 268440352\n')]
> ```
> 
> Also, we wanted to cherry-pick some of @skyzh 's fixes, right?

Diagnosis: https://github.com/neondatabase/neon/pull/6938#issuecomment-1968529635

Fix already pushed into this branch.

**Review by mattpodraza — APPROVED** [review]

**Comment by problame** [comment]
Obsolete, never happened; we did a new release instead: #6956

**Pull request closed without merging**
