### PR TITLE
tests: update tests that used local_fs&mock_s3 to use one or the other

### PR DESCRIPTION
**Pull request by jcsp**
## Problem

This was wasting resources: if we run a test with mock s3 we don't then need to run it again with local fs.  When we're running in CI, we don't need to run with the mock/local storage as well as real S3.  There is some value in having CI notice/spot issues that might otherwise only happen when running locally, but that doesn't justify the cost of running the tests so many more times on every PR.

## Summary of changes

- For tests that used available_remote_storages or available_s3_storages, update them to either specify no remote storage (therefore inherit the default, which is currently local fs), or to specify s3_storage() for the tests that actually want an S3 API.

## Checklist before requesting a review

- [ ] I have performed a self-review of my code.
- [ ] If it is a core feature, I have added thorough tests.
- [ ] Do we need to implement analytics? if so did you add the relevant metrics to the dashboard?
- [ ] If this PR requires public announcement, mark it with /release-notes label and add several sentences in this section.

## Checklist before merging

- [ ] Do not forget to reformat commit message to not include the above checklist

### CODE REVIEW

**Comment by jcsp** [comment]
Interestingly, test_delete_tenant_exercise_crash_safety_failpoints started failing if run with real S3 and simulate_failures=1.  I've reinstated its previous behavior that in Ci it would run with both mock S3 and AWS S3, but only simulate failures on mock S3.

**Review by koivunej — COMMENTED** [review]
I think this is fine, @bayandin could you give it an approval if you see something?

**Review by bayandin — APPROVED** [review]
I like the idea, that it not it's not necessary to run a test for several storage types if we already run it for `real_s3`. 

I probably would like to keep the ability to run any test with local fs storage, but I'm not sure if it's really required for us

**Comment by koivunej** [comment]
> #### Failures on Postgres 15
> 
> * `test_creating_tenant_conf_after_attach`: [debug](https://neon-github-public-dev.s3.amazonaws.com/reports/pr-6015/7129252902/index.html#suites/4c54991a1bdef2d920f741ae5ea7d1a1/f202313307621fac)

Kind of interesting looking error, not allowed warn:

```
WARN deletion backend: Dropped remote consistent LSN updates for tenant 8d7d51efb08bfb90dfc060e1235f1786 in stale generation 00000001
```

I cannot at least see the connection to the test case name not knowing what it actually does. Solution is probably more allowed errors, though I would not add it before understanding what's up. What is the actionable if we see this in prod?

**Comment by jcsp** [comment]
I looked into that failure.  It's in the "test is doing something weird" category: https://github.com/neondatabase/neon/pull/6074

In production those warnings can be ignored if there was any kind of incident going on at the time (e.g. nodes unexpectedly restarting), but it is unexpected during normal operations.

**Pull request merged**
