### PR TITLE
Store page image for HEAP2_PRUNE with FPI

### PR DESCRIPTION
**Pull request by knizhnik**
I noticed that massive update (i.e. "update t set x=x+1") cause generation of a lot of HEAP2_PRUNE war records with FPI.
And looking at code of `heap_xlog_prune` I noticed that it it does nothing except extracting image when contains FPI.
Well, not exactly true - it also updates FSM. But we in any case ignore this updates.
So HEAP2_PRUNE+FPI can be handled by pageserver itself (as it is done for XLOG_FPI) by storing page image than applying WAL record.

### CODE REVIEW

**Comment by antons-antons** [comment]
is there ever a reason to avoid storing an image every time we see apply_image?

I can see that storing a log record would allow extra checks to be performed while replaying a log record chain, but I wonder if we can introduce a middle ground: log based page images. They would not require base page for replay (as they initialize the page) but would be more compact than a database page (and carry extra debug info)

**Comment by knizhnik** [comment]
> is there ever a reason to avoid storing an image every time we see apply_image?
> 
> I can see that storing a log record would allow extra checks to be performed while replaying a log record chain, but I wonder if we can introduce a middle ground: log based page images. They would not require base page for replay (as they initialize the page) but would be more compact than a database page (and carry extra debug info)

I am not sure that other records with FPI doesn't perform some other actions except just restoring page image.
I will check it.

**Review by hlinnaka — COMMENTED** [review]
Whitelisting individual record types for which we can do this optimization makes sense to me.

I wonder what the performance impact of this really is though. In a bulk update, I presume you HEAP-PRUNE2 immediately followed by an UPDATE record. Is there any measurable benefit in optimizing the PRUNE2 record in that case, if you have to replay the UPDATE record anyway? As for any performance patch, I'd like to see a new test case added that demonstrates the benefit.

I'm inclined to just drop this for now. I doubt this makes much difference. And it can be done any time later without changing the on-disk format.

**Comment by knizhnik** [comment]
> I wonder what the performance impact of this really is though

I make this change because I have noticed that after huge update, WAL mostly consists of HEAP PRUNE. What is the impact?

```
pgbench -h 127.0.0.1 -p 55432 -i -s 100 -U zenith_admin postgres
update pgbench_accounts set abalance=abalance+1;
select sum(abalance) from pgbench_accounts;
```

| Version | Update time |  Select time |
| ---------- | ---------------- | ---------------- |
| main     |        565108 |        333328 |
| patch    |        512341 |        126380 |

So it is more than two times.
And just few lines of code.
Frankly speaking I do not understand why we should "drop this for now"...

**Comment by hlinnaka** [comment]
Oh, ok, I didn't expect such a big difference. Let's get it in then

**Comment by hlinnaka** [comment]
And can you also add that test case to our performance test suite, please? Unless that difference can already be seen by some of our existing tests.

**Comment by knizhnik** [comment]
I have added test. Results with this tests are not so impressive as with pgbench (do not know why), but still there is difference:

```
main:
test_update[vanilla].update: 111.283 s
test_update[vanilla].select: 15.674 s
test_update[zenith].update: 151.852 s
test_update[zenith].select: 106.677 s

prune_fpi:
test_update[vanilla].update: 117.247 s
test_update[vanilla].select: 13.419 s
test_update[zenith].update: 149.896 s
test_update[zenith].select: 85.538 s
```

But the positive result is visible only on 10M rows.
In this case execution of this test takes significant amount of time and is canceled by CI timeout.
Show I parameterize number of rows and make it smaller for CI?

**Comment by knizhnik** [comment]
Sorry, looks like effect is also visible at smaller number of rows:
```
main:
test_update[vanilla-1000000].update: 13.308 s
test_update[vanilla-1000000].select: 1.067 s
test_update[zenith-1000000].update: 8.605 s
test_update[zenith-1000000].select: 3.111 s

prune_fpi:
test_update[vanilla-1000000].update: 7.265 s
test_update[vanilla-1000000].select: 0.398 s
test_update[zenith-1000000].update: 8.744 s
test_update[zenith-1000000].select: 2.679 s
```

**Pull request closed without merging**
