### PR TITLE
Fix UNLOGGED tables.

### PR DESCRIPTION
**Pull request by arssher**
Instead of trying to create missing files on the way, send init fork contents as main fork from pageserver during basebackup. Add test for that.

https://neondb.slack.com/archives/C04DGM6SMTM/p1677234868718509?thread_ts=1676890587.096959&cid=C04DGM6SMTM

### CODE REVIEW

**Comment by arssher** [comment]
Will revert PG changes and bump vendor/ in the same PR soon.

**Review by hlinnaka — APPROVED** [review]

**Review by knizhnik — APPROVED** [review]

**Review by knizhnik — COMMENTED** [review]
May be I missed something, but it seems to be that we need some changes at postgres side, because unlogged relation are reset by `ResetUnloggedRelations`
which is called only during recovery. But when compute is started we do not perform recovery and this functions is not called.

**Comment by hlinnaka** [comment]
> May be I missed something, but it seems to be that we need some changes at postgres side, because unlogged relation are reset by `ResetUnloggedRelations` which is called only during recovery. But when compute is started we do not perform recovery and this functions is not called.

Right. This PR does that "copying" in basebackup.rs itself, so that Postgres doesn't need to do it:

```
                // Send init fork as main fork to provide well formed empty
                // contents of UNLOGGED relations. Postgres copies it in
                // `reinit.c` during recovery.
                if rel.forknum == INIT_FORKNUM {
                    // I doubt we need _init fork itself, but having it at least
                    // serves as a marker relation is unlogged.
                    self.add_rel(rel, rel).await?;
                    self.add_rel(rel, rel.with_forknum(MAIN_FORKNUM)).await?;
                    continue;
                }
```
Note how the init fork is included in the tar file twice: first as the init fork itself, and then as the main fork.

**Comment by arssher** [comment]
I'm trying to understand why `check_restored_datadir_content` after test_pg_regress fails -- compute doesn't have some main and init forks unlike basebackup. But it should create them, and in separate I see that it does. Probably something related to ALTER TABLE SET LOGGED/UNLOGGED...

**Comment by arssher** [comment]
So it appears that after DROP of unlogged table basebackup from pageserver still delivers main and init fork. I'm inclined to suppress error in test and merge the PR if I won't sort this out soon -- to make user happy and fix this later.

**Comment by arssher** [comment]
Confirmed that `put_rel_drop` is not called after unlogged rel drop, but is called after normal rel drop.

**Comment by arssher** [comment]
Ok, that's due to this: https://github.com/neondatabase/neon/blob/main/pageserver/src/walingest.rs#L765

**Comment by arssher** [comment]
So I added removal of init forks. Hopefully previous code wasn't intentional, cc @hlinnaka . This is ready for merge, vendor/postgres also updated.

**Pull request merged**
