### PR TITLE
remove `gc_feedback` mechanism

### PR DESCRIPTION
**Pull request by problame**
It's been dead-code-at-runtime for 9 months, let's remove it.
We can always re-introduce it at a later point.

Came across this while working on #6861, which will touch
`time_for_new_image_layer`. This is an opporunity to make that function
simpler.

### CODE REVIEW

**Review by jcsp — APPROVED** [review]
I'm good with removing this on the basis of it being dead code.

I anticipate that if we re-introduce something similar in future, we'd do it as part of the compaction heuristic for image layer generation: compaction can inspect deltas to identify cases where we have long-idle regions of the keyspace that are still hitting deltas.

**Comment by knizhnik** [comment]
There was the real problem (stairs of layers) first encountered at Kontour project and then reproduced and investigated by Bojan. This feedback mechanism was intended to address this problem used to be efficient (at least there was a test demonstrating effect of this patch). 

I wonder if storage team has proposed some alternative solution of the problem?
Or for some other reasons the problem is not relevant any more?
Removing dead code is certainly ok.
But  I afraid that the problem is still persist and the reason why we do not faced with it in prod is just because we have now very few customers with huge databases and intensive skewed updates.

So may be removing this "dead code" is something like removing airbag from your car just because it was never used:)

**Comment by knizhnik** [comment]
There was actually one more motivation for this feedback mechanism: reduce page reconstruction time by enforcing page image generation.  Once again, it is ok if you can propose something better. But still IMHO slow `get_page` is one of the main Neon drawbacks. Mostly because of network latency and compute-PS roundtrip. But PS overhead for page reconstruction is also noticeable.

**Comment by jcsp** [comment]
@problame I think the `test_gc_feedback` code is worth leaving in the tree -- this test wasn't actually validating the `gc_feedback` feature, but it's a useful reproducer of the original amplification case.

@knizhnik since we have the history of this change, we can always re-introduce this code if it is useful.  As it is, I think it's a danger: if someone switches on the gc_feedback setting they might get quite unexpected results.  I'm particularly concerned about what would happen for a non-root timeline using gc_feedback=true: it might start writing out replacement image layers for a lot of the parent timeline's data.

I've created an issue (https://github.com/neondatabase/neon/issues/6895) which references this and other historical PRs, and lays out what I think we need to solve to have a mechanism that we can enable in production.

**Pull request merged**
