### PR TITLE
SELECT 💣();

### PR DESCRIPTION
**Pull request by bayandin**
## Problem
We want to be able to test how our infrastructure reacts on segfauls in Postgres (for example, we collect core dumps, get some required logs/metrics, etc)

## Summary of changes
- Add `trigger_segfauls` function to `neon_test_utils` to trigger a segfault in Postgres
- Add `trigger_panic` function to `neon_test_utils` to trigger SIGABRT (by using `elog(PANIC, ...))
- Fix cleanup logic in regression tests in endpoint crashed

## Checklist before requesting a review

- [x] I have performed a self-review of my code.
- [ ] If it is a core feature, I have added thorough tests.
- [ ] Do we need to implement analytics? if so did you add the relevant metrics to the dashboard?
- [ ] If this PR requires public announcement, mark it with /release-notes label and add several sentences in this section.

## Checklist before merging

- [ ] Do not forget to reformat commit message to not include the above checklist

### CODE REVIEW

**Review by kelvich — APPROVED** [review]
awesome!

**Comment by kelvich** [comment]
And you, perhaps, need to bump extension version and write migration script.

**Comment by kelvich** [comment]
> Why do we need this? I don't see it.

version bump or function to segfual? If latter then to test crash behavior (e.g. will compute_ctl restart postgres) and test coredump collection / printing

**Comment by bayandin** [comment]
> Why do we need this? I don't see it.

Added it to the description: 
> We want to be able to test how our infrastructure reacts on segfauls in Postgres (for example, we collect core dumps, get some required logs/metrics, etc)

Haven't noticed Stas' answer, but the idea is the same

**Comment by bayandin** [comment]
> And you, perhaps, need to bump extension version and write migration script.

I bumped the version. Don't think the migration script is required for this one (we're pretty chill about it for test extension, for example, the previous changes https://github.com/neondatabase/neon/commit/75c84c846a2517cbbe414ae5f3e0649f4a359036)

**Comment by skyzh** [comment]
Note that this extension can be directly used by our users, so I would avoid putting things that might crash compute in that... There was an attempt to remove user access but autoscaling tests need this extension so it was reverted. https://github.com/neondatabase/neon/pull/7679

**Pull request merged**
