### PR TITLE
Add tests for measuring effect of lsn caching

### PR DESCRIPTION
**Pull request by knizhnik**
See #1949

### CODE REVIEW

**Review by hlinnaka — APPROVED** [review]

**Comment by hlinnaka** [comment]
please fix the typos in commit message before poshing ("measurif" -> "measuring", "effet" -> effect"

**Comment by hlinnaka** [comment]
In the future, please fix the commit message before pushing. The commit message for this was now "Add test for last written lsn cache", but that was very wrong. The test was added in the earlier commit already and this actually included the code changes.

Results from the new performance test from CI:

[Before](https://github.com/neondatabase/neon/runs/8172060005):
```
test_measure_read_latency_heavy_write_workload[neon-1].read_latency_max: 1.469 s
test_measure_read_latency_heavy_write_workload[neon-1].read_latency_avg: 0.454 s
test_measure_read_latency_heavy_write_workload[neon-1].read_latency_stdev: 0.478
```
[After](https://github.com/neondatabase/neon/runs/8178930935):
```
test_measure_read_latency_heavy_write_workload[neon-1].read_latency_max: 1.408 s
test_measure_read_latency_heavy_write_workload[neon-1].read_latency_avg: 0.265 s
test_measure_read_latency_heavy_write_workload[neon-1].read_latency_stdev: 0.439 s
```
That's a bit disappointing, the effect that was reported initially at https://github.com/neondatabase/neon/pull/1949 were much bigger. Did we make some other changes that mostly fixed the problem already?

**Comment by knizhnik** [comment]
> Did we make some other changes that mostly fixed the problem already?

I do not know such optimization.
Only changing `max_replication_write_lag` can significantly affect results.
Right now for tests  `max_replication_write_lag=15MB` is used and looks like this lag is small enough to keep response time small enough even without LSN cache.
The table below contains dependency of `read_latency_max` on `max_replication_write_lsg`:
| max_replication_write_lsg | with cache | without cache |
| ----------------------------------- | ------------- | ------------------- |
| 10 | 1.478  | 4.993 |
| 20 | 1.676  | 5.257 |
| 30 | 2.204 | 16.591 |
| 40 | 2.472  | 20.421 | 
| 50 | 2.938  | 22.3162 |

**Comment by knizhnik** [comment]
Unfortunately I still got one "key not found error" in one CI run:
```
test_runner/regress/test_parallel_copy.py:55: in test_parallel_copy
    asyncio.run(parallel_load_same_table(pg, n_parallel))
/home/nonroot/.pyenv/versions/3.9.2/lib/python3.9/asyncio/runners.py:44: in run
    return loop.run_until_complete(main)
/home/nonroot/.pyenv/versions/3.9.2/lib/python3.9/asyncio/base_events.py:642: in run_until_complete
    return future.result()
test_runner/regress/test_parallel_copy.py:39: in parallel_load_same_table
    await asyncio.gather(*workers)
test_runner/regress/test_parallel_copy.py:29: in copy_test_data_to_table
    await pg_conn.copy_to_table(table_name, source=copy_input)
/github/home/.cache/pypoetry/virtualenvs/zenith-_pxWMzVK-py3.9/lib/python3.9/site-packages/asyncpg/connection.py:877: in copy_to_table
    return await self._copy_in(copy_stmt, source, timeout)
/github/home/.cache/pypoetry/virtualenvs/zenith-_pxWMzVK-py3.9/lib/python3.9/site-packages/asyncpg/connection.py:1081: in _copy_in
    return await self._protocol.copy_in(
asyncpg/protocol/protocol.pyx:529: in copy_in
    ???
E   asyncpg.exceptions.PostgresIOError: could not read block 2 in rel 1663/12972/16384.0 from page server at lsn 0/016960E8
E   DETAIL:  page server returned error: could not find data for key 000000067F000032AC0000400000FFFFFFFF at LSN 0/1696070, for request at LSN 0/16960E8
```
Not sure if it is related with last written LSN cache but it is ost probable candidate.
Any attempts to reproduce it locally still failed.

**Pull request merged**
