### PR TITLE
feat: Task hierarchy

### PR DESCRIPTION
**Pull request by koivunej**
Why not have a an actual task hierarchy starting from shutdown_pageserver by requiring a CancellationToken to `task_mgr::spawn`? Let's see.

Caveats:
- even RemoteTimelineClient gets a cancellation token, which will be cancelled too soon
    - currently such token is never used
- drive-by layer backoff fix (now as #5746) to be removed

Tests fail because:
- flush loop exists too soon => warning

Solution for above I was thinking of:
- have separate cancellation hierarchy for each timeline used by its layer flush task and remote timeline client
  - giving remote timeline client a cancellation token in the first place was quite confusing, and with stop there is a "bad hierarchy" being selected
  - with stop perhaps the timeline deletion needs to *write over* the stop tree with it's operation specific which probably does not exist cancellation at all right now. It's probably fine.

### CODE REVIEW

**Comment by jcsp** [comment]
In https://github.com/neondatabase/neon/pull/6133, we saw that using task-oriented cancellation was problematic, because the scope of a task (in that case, a tenant) might be wider than the scope of the thing being cancelled  (in that case, a timeline).

Rather than extending the per-task cancellation tokens, I think we should go in the direction of using the cancellation tokens we carry on the major objects (Tenant, Timeline, etc).

**Comment by koivunej** [comment]
> In #6133, we saw that using task-oriented cancellation was problematic, because the scope of a task (in that case, a tenant) might be wider than the scope of the thing being cancelled (in that case, a timeline).
> 
> Rather than extending the per-task cancellation tokens, I think we should go in the direction of using the cancellation tokens we carry on the major objects (Tenant, Timeline, etc).

I was hoping that we would be having less cancellation tokens but for gc and compaction they will always need two except that now they can only use the timeline's CancellationToken.

As for the design in general, this will be more correct as we no longer have the bogus `task_mgr::shutdown_token()` -- even if someone were to use it by accident, it would still be the correct in-hierarchy token.

**Comment by koivunej** [comment]
Example of avoided problem: https://github.com/neondatabase/neon/pull/5746#discussion_r1428159294

**Comment by koivunej** [comment]
Closing for #8449

**Pull request closed without merging**
