### PR TITLE
Move path-related fixtures into their own module

### PR DESCRIPTION
**Pull request by tristan957**
neon_fixtures.py has grown into quite a beast.

### CODE REVIEW

**Comment by hlinnaka** [comment]
`test_output_dir` seems like a good candidate for moving to the new file too. And `get_self_dir()` from utils.py. Maybe `shared_snapshot_dir` and `test_overlay_dir` too, although they're a little more tightly coupled with storage.

I think you'll need to add `import`s to many tests that use these fixtures, but the CI will flag those :-)

**Comment by tristan957** [comment]
Hmm, some of these aren't fixtures. Would you like me to make them fixtures?

**Comment by hlinnaka** [comment]
> Hmm, some of these aren't fixtures. Would you like me to make them fixtures?

I was just thinking of moving them as is. No opinion if they should be fixtures.

**Comment by tristan957** [comment]
Just feels like we are overloading a directory called `fixtures`. For now, I'll move them as is, like you suggest. Can defer more re-organization to later.

**Comment by tristan957** [comment]
I'm just gonna get rid of `get_self_dir()`. I'll evaluate the rest after https://github.com/neondatabase/neon/pull/9306 is merged.

**Comment by tristan957** [comment]
Waiting on https://github.com/neondatabase/neon/pull/9303 to merge before pushing up my latest changes. No sense in needlessly spinning the CI.

**Comment by tristan957** [comment]
This PR is ready to go.

**Review by bayandin — APPROVED** [review]

**Pull request merged**
