### PR TITLE
feat(pageserver): use fnv hash for aux file encoding

### PR DESCRIPTION
**Pull request by skyzh**
## Problem

FNV hash is simple, portable, and stable. This pull request vendors the FNV hash implementation from servo and modified it to use the u128 variant.

replaces https://github.com/neondatabase/neon/pull/7644

ref https://github.com/neondatabase/neon/issues/7462

## Checklist before requesting a review

- [x] I have performed a self-review of my code.
- [ ] If it is a core feature, I have added thorough tests.
- [ ] Do we need to implement analytics? if so did you add the relevant metrics to the dashboard?
- [ ] If this PR requires public announcement, mark it with /release-notes label and add several sentences in this section.

## Checklist before merging

- [ ] Do not forget to reformat commit message to not include the above checklist

### CODE REVIEW

**Comment by hlinnaka** [comment]
> We can modify the algorithm to use 128b instead, but I didn't do it in this pull request, as I don't know if using 128b still preserves the properties of the hash algorithm.

128 bit and other length variants exist, see https://en.wikipedia.org/wiki/Fowler%E2%80%93Noll%E2%80%93Vo_hash_function. That particular crate only implements the 64 bit variant but there are others, and it's not hard to roll your own.

I'd assume 64 bits to be enough, though.

**Comment by hlinnaka** [comment]
Do we need to worry about malicious actors creating intentional collisions here? What happens if there's a ton of collisions? Does it only cause trouble for the single tenant, or the whole pageserver?

**Review by hlinnaka — APPROVED** [review]

**Comment by skyzh** [comment]
switched to FNV128 using the prime + offset in the wiki, better to get a review again, or I'll merge it later today.

**Comment by skyzh** [comment]
Okay it still requires a review from code owner 🤣 @koivunej do you have time to take a look? Thanks :)

**Comment by skyzh** [comment]
> Do we need to worry about malicious actors creating intentional collisions here? What happens if there's a ton of collisions? Does it only cause trouble for the single tenant, or the whole pageserver?

Creating intentional collision might cause write amplifications like before John’s one-file-one-delta-record PR, and it will only cause trouble for a single tenant. We can change the encoding of aux file value to delta + image in the future if it indeed becomes a problem.

**Review by koivunej — APPROVED** [review]

**Pull request merged**
