### PR TITLE
Undo walloging replorgin file on checkpoint

### PR DESCRIPTION
**Pull request by knizhnik**
## Problem

See #8620

## Summary of changes

Remove walloping of replorigin file because it is reconstructed by PS

## Checklist before requesting a review

- [ ] I have performed a self-review of my code.
- [ ] If it is a core feature, I have added thorough tests.
- [ ] Do we need to implement analytics? if so did you add the relevant metrics to the dashboard?
- [ ] If this PR requires public announcement, mark it with /release-notes label and add several sentences in this section.

## Checklist before merging

- [ ] Do not forget to reformat commit message to not include the above checklist

### CODE REVIEW

**Comment by hlinnaka** [comment]
Do we have a plan for how to eventually remove those obsolete `pg_logical/replorigin_checkpoint` files from the storage?

**Comment by knizhnik** [comment]
> ```
> ~/git-sandbox/neon/vendor/postgres-v16 (remove_replorigin_checkpoint_v16)$ git diff REL_16_3 src/backend/replication/logical/origin.c
> diff --git a/src/backend/replication/logical/origin.c b/src/backend/replication/logical/origin.c
> index b0255ffd25a..bc540521a96 100644
> --- a/src/backend/replication/logical/origin.c
> +++ b/src/backend/replication/logical/origin.c
> @@ -83,6 +83,7 @@
>  #include "nodes/execnodes.h"
>  #include "pgstat.h"
>  #include "replication/logical.h"
> +#include "replication/message.h"
>  #include "replication/origin.h"
>  #include "storage/condition_variable.h"
>  #include "storage/copydir.h"
> @@ -657,7 +658,6 @@ CheckPointReplicationOrigin(void)
>                                          errmsg("could not write to file \"%s\": %m",
>                                                         tmppath)));
>                 }
> -
>                 COMP_CRC32C(crc, &disk_state, sizeof(disk_state));
>         }
>  
> @@ -1144,6 +1144,7 @@ replorigin_session_setup(RepOriginId node, int acquired_by)
>  
>                 /* ok, found slot */
>                 session_replication_state = curstate;
> +               break;
>         }
>  
>  
> ```
> 
> Why the added `break`? And let's remove those other superfluous changes too.

Sorry, removed unintended changes.

**Comment by knizhnik** [comment]
> Do we have a plan for how to eventually remove those obsolete `pg_logical/replorigin_checkpoint` files from the storage?

Any reason for it? Can extra ~100 bytes somehow compensate efforts needed to remove them?

**Comment by hlinnaka** [comment]
> > Do we have a plan for how to eventually remove those obsolete `pg_logical/replorigin_checkpoint` files from the storage?
> 
> Any reason for it? Can extra ~100 bytes somehow compensate efforts needed to remove them?

It's not urgent, but it might cause surprises later, after everyone has already forgotten about them.

**Comment by hlinnaka** [comment]
>>  Why the added break? And let's remove those other superfluous changes too.
>
> Sorry, removed unintended changes.

I can still see the extra 'break' there.

**Comment by knizhnik** [comment]
> > > Why the added break? And let's remove those other superfluous changes too.
> > 
> > 
> > Sorry, removed unintended changes.
> 
> I can still see the extra 'break' there.

Sorry, looks like I didn't push changes in neon repo.
Fixed.

**Review by hlinnaka — APPROVED** [review]
A few more trivial remnants of this:
```
$ git diff REL_16_4..origin/pr/472  src/backend/replication/logical/origin.c
diff --git a/src/backend/replication/logical/origin.c b/src/backend/replication/logical/origin.c
index b0255ffd25a..739030a87e1 100644
--- a/src/backend/replication/logical/origin.c
+++ b/src/backend/replication/logical/origin.c
@@ -83,6 +83,7 @@
 #include "nodes/execnodes.h"
 #include "pgstat.h"
 #include "replication/logical.h"
+#include "replication/message.h"
 #include "replication/origin.h"
 #include "storage/condition_variable.h"
 #include "storage/copydir.h"
@@ -615,6 +616,7 @@ CheckPointReplicationOrigin(void)
                                 errmsg("could not write to file \"%s\": %m",
                                                tmppath)));
        }
+
        COMP_CRC32C(crc, &magic, sizeof(magic));
 
        /* prevent concurrent creations/drops */
```

Other than that, LGTM

**Pull request merged**
