### PR TITLE
Revert benchmark job runner

### PR DESCRIPTION
**Pull request by zoete**
Regression: https://neondb.slack.com/archives/C04BLQ4LW7K/p1675243980476929

### CODE REVIEW

**Comment by hlinnaka** [comment]
To be clear, I don't have any objections to moving the runner. A one-time change is fine, as long as the run environment doesn't change too often, like every week or month.

If we can have a stable and repeatable environment from one run to another, that's good. Is the new job runner stable enough for running repeatable benchmarks? Or does it share resources with random other stuff, for example?

**Comment by zoete** [comment]
Understood, but do we want to test from inside AWS, or from outside AWS? As it won't be a fair comparison.

**Comment by bayandin** [comment]
> Understood, but do we want to test from inside AWS, or from outside AWS? As it won't be a fair comparison.

Benchmarks in this job start their own computes/pageservers/safekeepers on a runner itself.
Nightly Benchmarks (which uses remote installation) are still on AWS

**Comment by zoete** [comment]
Ah then I misunderstood, the compute strength of gen3 is currently quite ahead of what is available on AWS. I am leaning to keeping benchmark on similar strength, to not cause to much of a divergence.

**Comment by LizardWizzard** [comment]
Is it still relevant?

**Pull request closed without merging**
