### PR TITLE
fix(remote_storage): use cached credentials

### PR DESCRIPTION
**Pull request by koivunej**
IMDSv2 has limits, and if we query it on every s3 interaction we are going to go over those limits. Changes the s3_bucket client configuration to use:
- ChainCredentialsProvider to handle env variables or imds usage
- LazyCachingCredentialsProvider to actually cache any credentials

Related: https://github.com/awslabs/aws-sdk-rust/issues/629
Possibly related: https://github.com/neondatabase/neon/issues/3118

### CODE REVIEW

**Review by LizardWizzard — APPROVED** [review]

**Comment by koivunej** [comment]
I think we still need the LazyCaching whatever per: https://github.com/awslabs/aws-sdk-rust/discussions/627#discussioncomment-3807017

**Review by problame — CHANGES_REQUESTED** [review]
My understanding is that `ImdsCredentialsProvider` doesn't cache internally.
Need something like `LazyCachingCredentialsProvider` ?

**Comment by LizardWizzard** [comment]
> My understanding is that ImdsCredentialsProvider doesn't cache internally.

You're right, I read it wrong

**Review by vadim2404 — APPROVED** [review]

**Comment by koivunej** [comment]
Now without clippy warnigns and the chain + lazy.

**Review by problame — APPROVED** [review]

**Review by LizardWizzard — APPROVED** [review]

**Pull request merged**
