### PR TITLE
refactor(walredo): use heavier_once_cell to store the process handle

### PR DESCRIPTION
**Pull request by problame**
In preceding PR https://github.com/neondatabase/neon/pull/6589 we made `heavier_once_cell` use an RwLock, so, now we can switch walredo to use it without introducing a performance regression.

I want to switch to `heavier_once_cell` because we'll replace the `WalRedoProcess::launch()` call with an `async fn` call when we switch to a pre-spawned pool of walredo processes in PR #6596 .

part of https://github.com/neondatabase/neon/issues/6581

### CODE REVIEW

**Comment by problame** [comment]
This should be ready for merge

**Comment by arpad-m** [comment]
Given #6704 do you still pursue this @problame ?

**Comment by problame** [comment]
Yes, I still need something like this.

If we can't make tokio::sync::RwLock-based heavier_once_cell work, I'll use a tokio::sync::RwLock myself in this PR.

**Comment by problame** [comment]
Note this PR is part of https://github.com/neondatabase/neon/issues/6581 which is currently on hold due to other priorities.

**Comment by problame** [comment]
this is stale and not directly applicable because we had to revert the heavier_once_cell changes: https://github.com/neondatabase/neon/pull/6704

**Pull request closed without merging**
