### PR TITLE
feat: add rough timings for basebackup

### PR DESCRIPTION
**Pull request by koivunej**
just record the time needed for waiting the lsn and then the basebackup in a log message in millis. this is related to ongoing investigations to cold start performance.

this could also be a a counter. it cannot be added next to smgr histograms, because we don't want another histogram per timeline.

the aim is to allow drilling deeper into which timelines were slow, and to understand why some need two basebackups.

### CODE REVIEW

**Review by problame — APPROVED** [review]
I'd prefer a Prometheus metric but don't mind the log message either.

Note that `handle_basebackup_request` is shared between  the fullbackup and basebackup commands.
I don't know if `fullbackup` is used anywhere, though.

Might make sense to push this into the caller, or, add context to the span to distinguish the two cases.

**Comment by koivunej** [comment]
Many test failures seem real_s3 related.

**Comment by koivunej** [comment]
Theoretically the fullbackup is already in the span, as a boolean, so not interested in doing that change in a hurry:

```
INFO handle_basebackup_request{tenant_id=X timeline_id=Y lsn=Some(0/31612E0) prev_lsn=None full_backup=false}
```

**Comment by koivunej** [comment]
Created a separate PR for [42bf5e7](https://github.com/neondatabase/neon/pull/4062/commits/42bf5e785054594de000dcc23e2938055bec2a3e), will drop it from this PR after current builds complete. PR is already done at #4064.

**Pull request merged**
