### PR TITLE
Bypass SENTRY_ENVIRONMENT variable in order to filter panics in sentry by environment.

### PR DESCRIPTION
**Pull request by vadim2404**
Relevant updates in helm charts: neondatabase/helm-charts#20

### CODE REVIEW

**Review by koivunej — APPROVED** [review]
Code changes look good.

**Comment by arssher** [comment]
Only partially related to this, but I'm somewhat embarassed by abundance of env name synonyms:

- dev staging build development
- prod release production

Won't this add one more 'development' word? It seems like I haven't seen it previously.

**Review by arssher — APPROVED** [review]

**Comment by vadim2404** [comment]
> Only partially related to this, but I'm somewhat embarassed by abundance of env name synonyms:
> 
> * dev staging build development
> * prod release production
> 
> Won't this add one more 'development' word? It seems like I haven't seen it previously.

"development" and "production" came from Sentry itself. It will set up one of this value by default if I sent nothing

**Comment by arssher** [comment]
Well, surely that's configurable?

**Comment by vadim2404** [comment]
yes, but if we have some misconfiguration, Sentry puts "production" by itself.

**Pull request merged**
