### PR TITLE
CORS preflight OPTIONS support for /sql (http fetch) endpoint

### PR DESCRIPTION
**Pull request by jawj**
## Problem

HTTP fetch can't be used from browsers because proxy doesn't support [CORS 'preflight' `OPTIONS` requests](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS#preflighted_requests).

## Summary of changes

Added a simple `OPTIONS` endpoint for `/sql`.

## Checklist before requesting a review

- [X] I have performed a self-review of my code.
- [ ] If it is a core feature, I have added thorough tests.
- [ ] Do we need to implement analytics? if so did you add the relevant metrics to the dashboard?
- [ ] If this PR requires public announcement, mark it with /release-notes label and add several sentences in this section.

## Checklist before merging

- [ ] Do not forget to reformat commit message to not include the above checklist

### CODE REVIEW

**Review by conradludgate — APPROVED** [review]
Do websockets need CORS too?

**Review by petuhovskiy — APPROVED** [review]

**Comment by bayandin** [comment]
Rust codestyle check is unhappy:

```diff
r
         })
     } else if request.uri().path() == "/sql" && request.method() == Method::OPTIONS {
-      Response::builder()
-        .header("Allow", "OPTIONS, POST")
-        .header("Access-Control-Allow-Origin", "*")
-        .header("Access-Control-Allow-Headers", "Neon-Connection-String, Neon-Raw-Text-Output, Neon-Array-Mode, Neon-Pool-Opt-In")
-        .header("Access-Control-Max-Age", "86400" /* 24 hours */)
-        .status(StatusCode::OK)  // [20](https://github.com/neondatabase/neon/actions/runs/5536089619/jobs/10103284592?pr=4706#step:8:21)4 is also valid, but see: https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/OPTIONS#status_code
-        .body(Body::empty())
-        .map_err(|e| ApiError::BadRequest(e.into()))
-
+        Response::builder()
+            .header("Allow", "OPTIONS, POST")
+            .header("Access-Control-Allow-Origin", "*")
+            .header(
+                "Access-Control-Allow-Headers",
+                "Neon-Connection-String, Neon-Raw-Text-Output, Neon-Array-Mode, Neon-Pool-Opt-In",
+            )
+            .header("Access-Control-Max-Age", "86400" /* [24](https://github.com/neondatabase/neon/actions/runs/5536089619/jobs/10103284592?pr=4706#step:8:25) hours */)
+            .status(StatusCode::OK) // 204 is also valid, but see: https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/OPTIONS#status_code
+            .body(Body::empty())
+            .map_err(|e| ApiError::BadRequest(e.into()))
     } else {
         json_response(StatusCode::BAD_REQUEST, "query is not supported")
     }
```

**Comment by jawj** [comment]
WebSockets don't need CORS (which my experience with the driver confirms): https://stackoverflow.com/questions/23674199/why-is-there-no-same-origin-policy-for-websockets-why-can-i-connect-to-ws-loc

**Comment by jawj** [comment]
Ah, looks like I need to change my tab settings! I'll update the PR ...

**Comment by bayandin** [comment]
> Ah, looks like I need to change my tab settings! I'll update the PR ...

A bit more than just tabs, you can run `cargo fmt --all` to get this fixed. 

```diff
@@ -225,9 +225,12 @@ async fn ws_handler(
         Response::builder()
             .header("Allow", "OPTIONS, POST")
             .header("Access-Control-Allow-Origin", "*")
-            .header("Access-Control-Allow-Headers", "Neon-Connection-String, Neon-Raw-Text-Output, Neon-Array-Mode, Neon-Pool-Opt-In")
+            .header(
+                "Access-Control-Allow-Headers",
+                "Neon-Connection-String, Neon-Raw-Text-Output, Neon-Array-Mode, Neon-Pool-Opt-In",
+            )
             .header("Access-Control-Max-Age", "86400" /* 24 hours */)
-            .status(StatusCode::OK)  // 204 is also valid, but see: https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/OPTIONS#status_code
+            .status(StatusCode::OK) // 204 is also valid, but see: https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/OPTIONS#status_code
             .body(Body::empty())
             .map_err(|e| ApiError::BadRequest(e.into()))
     } else {
```

**Comment by jawj** [comment]
Ah — thanks @bayandin.

**Comment by jawj** [comment]
Hmm. `cargo fmt --all` gives me: 

```
error: no such command: `fmt`
```

And I don't seem to have either `rustfmt` or `rustup` installed. Could my problem be that I installed Rust with homebrew instead of `rustup`? Have I perhaps missed something else obvious? (I have approximately zero experience with Rust).

**Comment by conradludgate** [comment]
> And I don't seem to have either `rustfmt` or `rustup` installed. Could my problem be that I installed Rust with homebrew instead of `rustup`? Have I perhaps missed something else obvious? (I have approximately zero experience with Rust).

Yeah, rustup is needed to manage the entire suite of rust tooling and versions, including cargo, rustc, rustfmt etc

**Comment by jawj** [comment]
Thanks guys. Having removed the homebrew installation and installed with `rustup`, this all just worked.

**Review by conradludgate — APPROVED** [review]

**Review by vadim2404 — APPROVED** [review]

**Pull request merged**
