### PR TITLE
allow async code inside `Tenant::state.send_modify`

### PR DESCRIPTION
**Pull request by problame**
This is preliminary work for/from #4220 (async `Layer::get_value_reconstruct_data`).

It is a dirty hack to allow using async code inside the closures that we pass to `Tenant::state.send_modify()`.

We'll need this because we want to turn `Tenant::timelines` into a `tokio::sync::Mutex` next.

See #4220 for more rationale.

### CODE REVIEW

**Comment by problame** [comment]
I'll spend an hour or two looking into alternatives, e.g., figuring out whether we can avoid holding `Tenant::timelines` inside the `send_modify`

**Review by koivunej — CHANGES_REQUESTED** [review]
All this is required because we want to access timelines while doing the state transition.

Could there be an easier way, for example, to add an intermediatery state for transitioning to activated, then do the activation, then mark as the end state?

**Comment by problame** [comment]
Yeah, that's what I'm looking into

**Comment by problame** [comment]
It's likely that this PR will be obsoleted by https://github.com/neondatabase/neon/pull/4321

**Comment by problame** [comment]
Abandoning this in favor of https://github.com/neondatabase/neon/pull/4321

**Pull request closed without merging**
