### PR TITLE
Maintain collection of last image layers to speed-up get_latest_image method use in LayerMap::search

### PR DESCRIPTION
**Pull request by knizhnik**

### CODE REVIEW

**Comment by knizhnik** [comment]
It will be nie to test it at captest to check if  compaction still uses 100% of CPU.

**Comment by hlinnaka** [comment]
At this point, I think we should revert commit f3073a4db93e2d4e39e2bbef03ed6b742ef3afa0. The old linear search wasn't fast, but I don't have much confidence in the new code. We need to do our homework properly, and add unit tests and benchmarks for all the operations.

**Comment by hlinnaka** [comment]
cc @yeputons

**Comment by knizhnik** [comment]
Frankly speaking I do not think that it it good idea to revert back R-Tree and replace it back with linear search.
`rstar` seems to be quite stable package and R-Tree - well known and widely used data structure.
Using i256 type for representing our 144 bit key may be considered as overkill and expensive, but this operation are not visible in profile. So I am against replacing R-Tree with dummy liner search. Even for free tier with 10Gb limit, number of image layers c an be up to 400. And taken i account one week history we can easily get several thousands layers where liner search will be very inefficient.

Even now we see problems  with 100% CPU usage in compaction at staging and captest. I am not sure that just adding latest age image map will solve this problem (I can check but do not see much sense i it).

I have performed some benchmarking using my `test_layer_map.py` test (slightly modified).
I just measure time of inserting data, vacuuming and traversing it.
Also I measured time of several last compaction iterations (which actually does nothing but consuming CPU).

Results are below:

```
latest_image_map:
test_layer_map.insert: 130.927 s
test_layer_map.vacuum: 105.797 s
test_layer_map.select: 432.148 s
total: 800.49s
compaction: min=1, max=834, avg=203.26

main:
test_layer_map.insert: 183.649 s
test_layer_map.vacuum: 114.857 s
test_layer_map.select: 530.850 s
total: 961.11s
Compaction: min=2.23147, max=3100.94, avg=775.338

main w/out R-Tree (reverted https://github.com/neondatabase/neon/commit/f3073a4db93e2d4e39e2bbef03ed6b742ef3afa0):
test_layer_map.insert: 169.829 s
test_layer_map.vacuum: 865.514 s
test_layer_map.select: 5,157.619 s
total: 6321.52s
Compaction: min=1, max=169255, avg=42535.8

```

So, you can see that this PR has not so much influence on insert/search speed, but allows to reduce compaction time about 3 times (actually it is not compaction itself, but preparation for compaction).
And implementation without R-Tree is extreeeeemly slow.

I do not want to say that R-Tree is most optimal data structure for this task. If @yeputons implementation of segment tree will be faster and simpler, then we should definitely use it. But just to be able to compare it with R-Tree we need to preserve current implementation.

**Comment by knizhnik** [comment]
So, looks like (thanks to @yeputons investigation) consumption of CPU at captest is not cause by LayerMap inefficiency.
And noticeable benefits of R-Tree in performance are obtained with several thousands layers.
For example, my results above were obtained with number of layers = ~50000. With size of layer 256Mb, it means database size ~10Tb. Nit sure that we are ready to handle such for such volume right ow. ut no doubt that in future we will have to deal with it.

The question is whether R-Tree can cause some slowdown for small number of layers, with our default setting and typeicall database size. In this case linear search is definitely faster than any other lookup method.

I have changed my test_ayer_ap example to use smaller database size  and default parameters. So there is just one layer.
Results:

```
latest_image_map:
test_layer_map.insert: 1.108 s
test_layer_map.vacuum: 0.613 s
test_layer_map.select: 1.791 s

main w/out R-Tree:
test_layer_map.insert: 1.081 s
test_layer_map.vacuum: 0.639 s
test_layer_map.select: 1.912 s
```
So there is almost no difference.
This is why I think there is completely no reasons to revert R-Tree implementation.

**Comment by LizardWizzard** [comment]
As discussed moving to draft

**Pull request closed without merging**
