### PR TITLE
postgres_ffi: add WAL generator for tests/benchmarks

### PR DESCRIPTION
**Pull request by erikgrinaker**
## Problem

We don't have a convenient way to generate WAL records for benchmarks and tests.

Touches #9339.

## Summary of changes

Adds a WAL generator, exposed as an iterator. It currently only generates logical messages (noops), but will be extended to write actual table rows later.

Some existing code for WAL generation has been replaced with this generator, to reduce duplication.

## Checklist before requesting a review

- [x] I have performed a self-review of my code.
- [ ] If it is a core feature, I have added thorough tests.
- [ ] Do we need to implement analytics? if so did you add the relevant metrics to the dashboard?
- [ ] If this PR requires public announcement, mark it with /release-notes label and add several sentences in this section.

## Checklist before merging

- [ ] Do not forget to reformat commit message to not include the above checklist

### CODE REVIEW

**Comment by erikgrinaker** [comment]
@arssher I took the liberty of trimming down and replacing the corresponding simulator code, let me know if you'd prefer to keep it.

**Comment by erikgrinaker** [comment]
> No tests were run or test report is not available

Some simulator tests are erroring out with page corruption. They passed locally, so it's probably a race where we end up clobbering the block store or something -- will investigate.

**Comment by tristan957** [comment]
Removing my review and adding Matthias and Heikki who are either still at PGConf EU or traveling home. Kicked your CI.

**Review by hlinnaka — APPROVED** [review]
Maybe put WalGenerator to a separate source file. Most of the rest of the code in xlog_utils.rs is adapted from Postgres sources, this is a little different.

**Comment by erikgrinaker** [comment]
>Maybe put WalGenerator to a separate source file.

Yep, done. TFTR!

Will merge this for now. If @arssher has comments we can resolve those separately.

**Comment by erikgrinaker** [comment]
Looks like I'll need a storage review as well to merge. I think @arssher is out sick, perhaps @VladLazar could do the honors.

**Review by arssher — APPROVED** [review]

**Pull request merged**
