### PR TITLE
Speed up rel extend

### PR DESCRIPTION
**Pull request by bojanserafimov**
test results:
- 13% speedup on `test_ingest_real_wal` on i3en.3xlarge
- 11% speedup on `test_pgbench[neon-45-10].init.duration` on i3en.3xlarge

If you want to reproduce my results here's the setup I use https://www.notion.so/neondatabase/How-to-perf-test-in-s3-wrapper-around-chi-s-guide-50cde4ec7bd44b48b7643d01ecc34a57

### CODE REVIEW

**Comment by bojanserafimov** [comment]
Some rust unit tests fail because get_rel_size can return Err if the rel doesn't exist. Odd that pgbench passes. But maybe I should keep the logic as is and do the proper fix - restructure the code so that we acquire locks only once and lookup rel size cache only once.

**Comment by knizhnik** [comment]
> Some rust unit tests fail because get_rel_size can return Err if the rel doesn't exist. Odd that pgbench passes. But maybe I should keep the logic as is and do the proper fix - restructure the code so that we acquire locks only once and lookup rel size cache only once.

This exactly why exists is called prior to get number of blocks.
May be `get_rel_size` should return 0 blocks for non-existed relation - I am not sure. But unless it is changed, it is not possible to swap them in extend relation.

**Comment by bojanserafimov** [comment]
Ok I tried to manually inline [here](https://github.com/neondatabase/neon/compare/speedup-rel-extend...speedup-rel-extend-proper?expand=1) which I expect to be even faster because I also handle the cache updates with no additional overhead.

But it doesn't compile because the cache is behind a `std::sync::RwLock` (not tokio), so the guard is not `Send`, which means I can't `await` while holding the guard. So we need to either use a tokio lock or avoid calling `get` even on cache miss (have the cache always warm and consistent).

Is there a reason we don't use a tokio lock here? cc @arpad-m because you might know about asyncification plans

**Comment by arpad-m** [comment]
For a test you could try to adopt a tokio lock and make the lock Send. All the places that acquire a lock now also have to become async, which probably isn't a big problem.

The issue is however that it has higher danger for dead locks. In the async code you do `Timeline::get` which is a very high level query that does a lot of things internally. Even if you can exclude 100% that this function is never going to be called from `Timeline::get`, there is still the danger that future changes introduce it.

As far as I can remember, my asyncification work has not involved this lock. But note that we did switch in the past in one instance to a sync lock from a tokio lock, see 85cd97af61ffc92f0e4c7ad7ee4992af0e98dce2.

**Comment by bojanserafimov** [comment]
> So we need to either use a tokio lock or avoid calling get even on cache miss (have the cache always warm and consistent).

That all seemed complicated so instead I chose to solve only the cache hit case and ignore the cache miss case. It should be rare anyway. Test results are almost the same.

**Pull request merged**
