### PR TITLE
Fix flaky pageserver restarts in tests

### PR DESCRIPTION
**Pull request by bojanserafimov**
Resolves https://github.com/neondatabase/neon/issues/2247

### CODE REVIEW

**Review by knizhnik — APPROVED** [review]

**Comment by bojanserafimov** [comment]
Not sure why my "wait for pid" solution was failing consistently on the same cases. It passes locally. Since we don't run CI on branches anymore, I'll make a few commits to this PR to test what works in CI and ask for re-review.

**Comment by hlinnaka** [comment]
We have the same pattern to wait for process death at _safekeeper_ shutdown, too. I presume it also needs to be fixed.

**Comment by bojanserafimov** [comment]
> We have the same pattern to wait for process death at _safekeeper_ shutdown, too. I presume it also needs to be fixed.

Sure. But first I need to see why it's consistently timing out. 100 seconds should be enough, but half the tests fail

**Comment by bojanserafimov** [comment]
The issue: Now that I'm properly waiting for pageserver to die, it refuses to die, even 100 seconds after `SIGKILL`. This is strange, because:
1. It only happens on CI
2. Somehow the pageserver dies correctly 99% of the time when we're not waiting for it to die.. How?

My theory: In `handle_pagerequests` we rely on `pgb.read_message()` (which is just `TcpStream::read()` in a trench coat) to occasionally time out and send a `WouldBlock` error, instead of blocking. But the socket is configured with `set_nonblocking(false)`, so it's up to the OS/hardware to decide whether to block or not. The OS/hardware could be different on my laptop, on the old runners, and on the new runners.

If the OS/hardware blocks, then the pageserver would be stuck in kernel space waiting on some network syscall. Since `SIGKILL` basically means "next time u in user mode, pls die", pageserver will hang forever.. Unless, we continue to the next test without waiting for it, and start a new `NeonEnv`, which starts a compute node, which sends some request and unblocks the old pageserver, allowing it to die just in time for the new one to start. Sometimes the timing is not right and we get a timeout on trying to lock the pid file. That would explain why **not** waiting for the pageserver seems to work better.

@LizardWizzard It's an elaborate theory, might be wrong, but I'm out of simple ones. Trying to find a way to check if any of this is in the right direction.

@zoete is there an easy way to test this PR on the old runners, just to see if the issue is OS/platform behavior? Another theory suggested by @LizardWizzard is that we could be hitting a bug like [this](https://stackoverflow.com/questions/34552232/cant-kill-processes-originating-in-a-docker-container), so that's worth checking too

**Comment by knizhnik** [comment]
Blocking system call with slow device (i.e. socket) should be interrupted by signal: EINTR error should be returned by system call in this case.

**Comment by LizardWizzard** [comment]
This is the output from runner machine:

```
sh-4.2$ ps aux | grep pageserver
ec2-user   511  0.0  0.0      0     0 ?        Zs   10:56   0:00 [pageserver] <defunct>
ec2-user   513  0.5  0.0      0     0 ?        Z    10:56   0:02 [pageserver] <defunct>
ec2-user   947  0.0  0.0      0     0 ?        Zs   10:57   0:00 [pageserver] <defunct>
ec2-user   948 26.9  0.0      0     0 ?        Z    10:57   2:12 [pageserver] <defunct>
ec2-user  2511  0.0  0.0      0     0 ?        Zs   10:58   0:00 [pageserver] <defunct>
ec2-user  2512  0.0  0.0      0     0 ?        Z    10:58   0:00 [pageserver] <defunct>
ec2-user  2656  0.0  0.0      0     0 ?        Zs   10:59   0:00 [pageserver] <defunct>
ec2-user  2657  0.2  0.0      0     0 ?        Z    10:59   0:00 [pageserver] <defunct>
ec2-user  2776  0.0  0.0      0     0 ?        Zs   11:00   0:00 [pageserver] <defunct>
ec2-user  2777  0.2  0.0      0     0 ?        Z    11:00   0:00 [pageserver] <defunct>
ec2-user  2970  0.0  0.0      0     0 ?        Zs   11:00   0:00 [pageserver] <defunct>
ec2-user  2971  0.0  0.0      0     0 ?        Z    11:00   0:00 [pageserver] <defunct>
ec2-user  3096  0.0  0.0      0     0 ?        Zs   11:00   0:00 [pageserver] <defunct>
ec2-user  3097  1.6  0.0      0     0 ?        Z    11:00   0:04 [pageserver] <defunct>
ec2-user  3280  0.0  0.0      0     0 ?        Zs   11:01   0:00 [pageserver] <defunct>
ec2-user  3281  0.1  0.0      0     0 ?        Z    11:01   0:00 [pageserver] <defunct>
ec2-user  3409  0.0  0.0      0     0 ?        Zs   11:02   0:00 [pageserver] <defunct>
ec2-user  3410  0.1  0.0      0     0 ?        Z    11:02   0:00 [pageserver] <defunct>
ec2-user  3544  0.0  0.0      0     0 ?        Zs   11:03   0:00 [pageserver] <defunct>
ec2-user  3545  0.1  0.0      0     0 ?        Z    11:03   0:00 [pageserver] <defunct>
ec2-user  3673  0.0  0.1 140664 29200 ?        Sl   11:03   0:00 /tmp/neon/bin/neon_local pageserver stop -m immediate
ec2-user  3681  0.0  0.0      0     0 ?        Zs   11:03   0:00 [pageserver] <defunct>
ec2-user  3682  0.2  0.0      0     0 ?        Z    11:03   0:00 [pageserver] <defunct>
ec2-user  3821  0.0  0.1 140664 28980 ?        Sl   11:03   0:00 /tmp/neon/bin/neon_local pageserver stop -m immediate
ec2-user  3833  0.0  0.1 140664 29160 ?        Sl   11:04   0:00 /tmp/neon/bin/neon_local pageserver stop -m immediate
ec2-user  3847  0.0  0.1 140664 29088 ?        Sl   11:04   0:00 /tmp/neon/bin/neon_local pageserver stop -m immediate
ssm-user  3853  0.0  0.0 121280   992 pts/0    S+   11:05   0:00 grep pageserver
ec2-user 30235  0.0  0.0      0     0 ?        Zs   10:52   0:00 [pageserver] <defunct>
ec2-user 30236  0.0  0.0      0     0 ?        Z    10:52   0:00 [pageserver] <defunct>
ec2-user 30284  0.0  0.0      0     0 ?        Zs   10:52   0:00 [pageserver] <defunct>
ec2-user 30285  1.0  0.0      0     0 ?        Z    10:52   0:08 [pageserver] <defunct>
ec2-user 30344  0.0  0.0      0     0 ?        Zs   10:52   0:00 [pageserver] <defunct>
ec2-user 30345  0.5  0.0      0     0 ?        Z    10:52   0:03 [pageserver] <defunct>
ec2-user 30439  0.0  0.0      0     0 ?        Zs   10:52   0:00 [pageserver] <defunct>
ec2-user 30440  0.5  0.0      0     0 ?        Z    10:52   0:03 [pageserver] <defunct>
ec2-user 30810  0.0  0.0      0     0 ?        Zs   10:54   0:00 [pageserver] <defunct>
ec2-user 30811  0.0  0.0      0     0 ?        Z    10:54   0:00 [pageserver] <defunct>
ec2-user 30918  0.0  0.0      0     0 ?        Zs   10:54   0:00 [pageserver] <defunct>
ec2-user 30919  8.0  0.0      0     0 ?        Z    10:54   0:50 [pageserver] <defunct>
ec2-user 30985  0.0  0.0      0     0 ?        Zs   10:54   0:00 [pageserver] <defunct>
ec2-user 30986  4.8  0.0      0     0 ?        Z    10:54   0:30 [pageserver] <defunct>
ec2-user 31205  0.0  0.0      0     0 ?        Zs   10:54   0:00 [pageserver] <defunct>
ec2-user 31206  2.4  0.0      0     0 ?        Z    10:54   0:15 [pageserver] <defunct>
ec2-user 32087  0.0  0.0      0     0 ?        Zs   10:56   0:00 [pageserver] <defunct>
ec2-user 32088 31.7  0.0      0     0 ?        Z    10:56   2:50 [pageserver] <defunct>
ec2-user 32591  0.0  0.0      0     0 ?        Zs   10:56   0:00 [pageserver] <defunct>
ec2-user 32592  0.7  0.0      0     0 ?        Z    10:56   0:03 [pageserver] <defunct>
```

So it says that pageserver become a zombie process. As tests run the list grows. Continue looking into it

**Comment by LizardWizzard** [comment]
See the same thing for safekeeper and postgres:

```
ec2-user 30416  0.0  0.0      0     0 ?        Zs   10:52   0:00 [postgres] <defunct>
ec2-user 30439  0.0  0.0      0     0 ?        Zs   10:52   0:00 [pageserver] <defunct>
ec2-user 30440  0.1  0.0      0     0 ?        Z    10:52   0:03 [pageserver] <defunct>
ec2-user 30471  0.0  0.0      0     0 ?        Zs   10:52   0:00 [safekeeper] <defunct>
ec2-user 30472  0.0  0.0      0     0 ?        Z    10:52   0:00 [safekeeper] <defunct>
ec2-user 30490  0.0  0.0      0     0 ?        Zs   10:52   0:00 [safekeeper] <defunct>
ec2-user 30491  0.0  0.0      0     0 ?        Z    10:52   0:00 [safekeeper] <defunct>
ec2-user 30509  0.0  0.0      0     0 ?        Zs   10:52   0:00 [safekeeper] <defunct>
ec2-user 30510  0.0  0.0      0     0 ?        Z    10:52   0:00 [safekeeper] <defunct>
```

Process hierarchy for one of the pageserver processes looks like that: 

```
sh-4.2$ pstree -aps 30235
systemd,1 --switched-root --system --deserialize 21
  └─containerd-shim,29203 -namespace moby -id 36c862f3a47133d56665a35f61f110842f466a07d5c4d8a760d408e4ff937c23 -address /run/containerd/containerd.sock
      └─tail,29225 -f /dev/null
          └─(pageserver,30235)

ec2-user 30235  0.0  0.0      0     0 ?        Zs   10:52   0:00 [pageserver] <defunct>
```

Have no idea where this tail -f /dev/null process comes from. May be some hack to keep container running

**Comment by zoete** [comment]
I added gen2 runners today, who no longer use `rustlegacy` image - I will also shuffle the runners. Maybe that will fix this issue

**Comment by LizardWizzard** [comment]
Hmm, I looked at the runner when it run just the build without actual tests and saw zombies for mold and cachepot
<details>
  <summary>Output</summary>

  ```
  lsh-4.2$ ps aux | grep defunct
ec2-user  7406  0.0  0.0      0     0 ?        Z    13:23   0:00 [cachepot] <defunct>
ec2-user  7407  0.0  0.0      0     0 ?        Zs   13:23   0:00 [cachepot] <defunct>
ec2-user  7753  0.2  0.0      0     0 ?        Z    13:23   0:00 [mold] <defunct>
ec2-user  7776  0.1  0.0      0     0 ?        Z    13:23   0:00 [mold] <defunct>
ec2-user  7794  0.4  0.0      0     0 ?        Z    13:23   0:00 [mold] <defunct>
ec2-user  7829  0.1  0.0      0     0 ?        Z    13:23   0:00 [mold] <defunct>
ec2-user  7830  0.1  0.0      0     0 ?        Z    13:23   0:00 [mold] <defunct>
ec2-user  7848  0.1  0.0      0     0 ?        Z    13:23   0:00 [mold] <defunct>
ec2-user  7995  0.2  0.0      0     0 ?        Z    13:23   0:00 [mold] <defunct>
ec2-user  8027  0.1  0.0      0     0 ?        Z    13:23   0:00 [mold] <defunct>
ec2-user  8163  0.1  0.0      0     0 ?        Z    13:23   0:00 [mold] <defunct>
ec2-user  8277  0.1  0.0      0     0 ?        Z    13:23   0:00 [mold] <defunct>
ec2-user  8318  0.1  0.0      0     0 ?        Z    13:23   0:00 [mold] <defunct>
ec2-user  8361  0.1  0.0      0     0 ?        Z    13:23   0:00 [mold] <defunct>
ec2-user  8632  0.1  0.0      0     0 ?        Z    13:23   0:00 [mold] <defunct>
ec2-user  8666  0.1  0.0      0     0 ?        Z    13:23   0:00 [mold] <defunct>
ec2-user  8788  0.2  0.0      0     0 ?        Z    13:23   0:00 [mold] <defunct>
ec2-user  9141  0.1  0.0      0     0 ?        Z    13:23   0:00 [mold] <defunct>
ec2-user  9232  0.1  0.0      0     0 ?        Z    13:23   0:00 [mold] <defunct>
ec2-user  9453  0.1  0.0      0     0 ?        Z    13:23   0:00 [mold] <defunct>
ec2-user  9673  0.4  0.0      0     0 ?        Z    13:23   0:00 [mold] <defunct>
ec2-user 10155  0.1  0.0      0     0 ?        Z    13:23   0:00 [mold] <defunct>
ec2-user 10186  0.1  0.0      0     0 ?        Z    13:23   0:00 [mold] <defunct>
ec2-user 10227  0.1  0.0      0     0 ?        Z    13:23   0:00 [mold] <defunct>
ec2-user 10237  0.2  0.0      0     0 ?        Z    13:23   0:00 [mold] <defunct>
ec2-user 10315  0.2  0.0      0     0 ?        Z    13:23   0:00 [mold] <defunct>
ec2-user 10682  0.2  0.0      0     0 ?        Z    13:23   0:00 [mold] <defunct>
ec2-user 10938  0.4  0.0      0     0 ?        Z    13:23   0:00 [mold] <defunct>
ec2-user 11143  0.2  0.0      0     0 ?        Z    13:23   0:00 [mold] <defunct>
ec2-user 11241  0.3  0.0      0     0 ?        Z    13:23   0:00 [mold] <defunct>
ec2-user 11407  0.6  0.0      0     0 ?        Z    13:23   0:00 [mold] <defunct>
ec2-user 11669  0.3  0.0      0     0 ?        Z    13:23   0:00 [mold] <defunct>
ec2-user 11820  0.2  0.0      0     0 ?        Z    13:23   0:00 [mold] <defunct>
ec2-user 11976  0.2  0.0      0     0 ?        Z    13:24   0:00 [mold] <defunct>
ec2-user 12056  0.5  0.0      0     0 ?        Z    13:24   0:00 [mold] <defunct>
ec2-user 12062  0.2  0.0      0     0 ?        Z    13:24   0:00 [mold] <defunct>
ec2-user 12144  0.2  0.0      0     0 ?        Z    13:24   0:00 [mold] <defunct>
ec2-user 12163  0.3  0.0      0     0 ?        Z    13:24   0:00 [mold] <defunct>
ec2-user 12165  0.2  0.0      0     0 ?        Z    13:24   0:00 [mold] <defunct>
ec2-user 12411  0.4  0.0      0     0 ?        Z    13:24   0:00 [mold] <defunct>
ec2-user 12424  0.6  0.0      0     0 ?        Z    13:24   0:00 [mold] <defunct>
ec2-user 12545  0.4  0.0      0     0 ?        Z    13:24   0:00 [mold] <defunct>
ec2-user 12748  0.4  0.0      0     0 ?        Z    13:24   0:00 [mold] <defunct>
ec2-user 12834  0.4  0.0      0     0 ?        Z    13:24   0:00 [mold] <defunct>
ec2-user 12852  1.8  0.0      0     0 ?        Z    13:24   0:00 [mold] <defunct>
ec2-user 12936  1.1  0.0      0     0 ?        Z    13:24   0:00 [mold] <defunct>
ec2-user 12937  0.4  0.0      0     0 ?        Z    13:24   0:00 [mold] <defunct>
ec2-user 12993  1.0  0.0      0     0 ?        Z    13:24   0:00 [mold] <defunct>
ec2-user 13076  0.5  0.0      0     0 ?        Z    13:24   0:00 [mold] <defunct>
ec2-user 13087  0.4  0.0      0     0 ?        Z    13:24   0:00 [mold] <defunct>
ec2-user 13141  0.4  0.0      0     0 ?        Z    13:24   0:00 [mold] <defunct>
ec2-user 13203  0.3  0.0      0     0 ?        Z    13:24   0:00 [mold] <defunct>
ec2-user 13257  0.5  0.0      0     0 ?        Z    13:24   0:00 [mold] <defunct>
ec2-user 13380  3.8  0.0      0     0 ?        Z    13:24   0:00 [mold] <defunct>
ec2-user 13486  1.7  0.0      0     0 ?        Z    13:24   0:00 [mold] <defunct>
ec2-user 13576  1.8  0.0      0     0 ?        Z    13:24   0:00 [mold] <defunct>
ec2-user 14174  1.2  0.0      0     0 ?        Z    13:24   0:00 [mold] <defunct>
ec2-user 14414  6.3  0.0      0     0 ?        Z    13:24   0:00 [mold] <defunct>
ssm-user 14987  0.0  0.0 121280   976 pts/0    R+   13:24   0:00 grep defunct
  ```
</details>

So I think it has something to do with the runner and how it launches tasks and not with our test suite

Do you have any ideas @zoete? I have little knowledge about runner internals/tasks scheduling. Based on what I've seen I think it runs the image with `tail -f /dev/null` and then uses `docker exec` to run pipeline steps. But it is still unclear how this might lead to zombies

**Comment by LizardWizzard** [comment]
Kudos to @zoete :) It seems that https://github.com/neondatabase/neon/pull/2289 fixed the issue. There was only one zombie proxy at the end of the test run and two moto instances appeared during shutdown compared to more than thousand zombies without the fix. No postgres/safekeepr/pageserver processes among zombies anymore

**Review by LizardWizzard — APPROVED** [review]
LGTM

**Pull request merged**
