### PR TITLE
Tenant::load: fix uninit timeline marker processing

### PR DESCRIPTION
**Pull request by problame**
The Problem
-----------

Before this patch, the following could happen.
* read_dir().next() returns the unint mark entry, we delete the timeline dir and the mark
* read_dir().next() returns the timeline dir entry
  * this is totally normal, a directory iterator is not invalidated by directory modifiction
  * we see that there's no uninit mark
  * so we try to load the timeline
  * but actually, the timeline dir is gone, so we fail the load with an error like

    ```
    2023-06-09T18:43:41.664247Z ERROR load{tenant_id=X}: load failed, setting tenant state to Broken: failed to load metadata

     Caused by:
         0: Failed to read metadata bytes from path .neon/tenants/X/timelines/Y/metadata
         1: No such file or directory (os error 2)
    ```

The Fix
-------

Turn the purging of temp entries into a fix-point iteration that restarts after every purge. Expressive, but less efficient. I'm ok with the inefficiency until it becomes a problem.

After fix-point iteration, do read-only iteration where we expect there to only be dir entries that are valid timeline dirs.

I also took the liberty to drive-by fix two issues that have been bugging me for some time:

1. precise error when extracting TimelineId from uninit mark file refs https://github.com/neondatabase/neon/issues/3488
2. Bail out instead of WARN-logging if there is directory entry in the timelines dir that is not a valid TimelineId. Bailing out means that the tenant will fail to load, i.e., it will be `Broken`. The situation can be fixed by operator using ignore+fix+load. Before this patch, we would just log a warning and continue. In my opinion, being strict about this is the better choice, because, if we somehow miss a timeline's existence, we make incorrect GC decisions.

### CODE REVIEW

**Review by LizardWizzard — COMMENTED** [review]
Note: This doesnt compile yet.

To me this doesnt look simpler than my patch.

Ideally I would change the strategy to be "gather facts then execute". This is way easier to test. 

In this case you walk the entry list first, gather timeline ids and init marks separately. Then for every mark you execute what is needed: 1) remove timeline from the list of loadable ones 2) clean up temporary dir 3) in the future continue deletion if deletion mark exists.

This way you can pass `impl Iterator<Item=&Path>` to the "gather facts" stage which is easily unit testable. Second part can take whatever struct is produced by the first stage and execute needed actions.

What do you think?

**Comment by problame** [comment]
In theory agree. In practice gather_facts approach still requires programmer to keep the in-memory facts in sync with what they did to the on-disk state.
That's exactly what didn't work in the current `main` code; the programmer forgot. 

My PR makes it much harder to screw up there.

**Comment by LizardWizzard** [comment]
> In practice gather_facts approach still requires programmer to keep the in-memory facts in sync with what they did to the on-disk state.

I dont think so. Facts struct is immutable once built. After it is constructed you iterate over entries and execute what they tell you.


Something like that:

```rust
enum Decision {
    Load,
    RemoveTemporary,
    RemoveUninitMark,
}

#[derive(Default)]
struct TenantDirToLoad {
    entries: HashMap<TimelineId, Decision>,
}
```
Then you `impl TryFrom<&Path> for TenantDirToLoad` which takes care of the construction. And then you iterate over entries and blindly execute calculated Decision. Dont see a possibility for confusion you've mentioned. 

Ideally I would love to avoid storing various mark files and timeline directories in the same directory. This way you can list "meta"-directory first, and then filter actual timeline dirs through this sieve. 

To me gather facts approach is way simpler to reason about compared to your patch.

It took me a while to understand that we re evaluate list dir multiple times and each deletion leads to calling read_dir again which is to me completely unnecessary. 

The whole new body of `is_uninit_mark` is also quite confusing to me.

**Comment by LizardWizzard** [comment]
Additionally I'm looking into separation of init logic to separate module(s) to make both tenant and timeline modules thinner.

**Comment by problame** [comment]
Ok, so, it's not a facts cache (cache of filesystem state) but it's actually building an operation plan.

Yeah, I like that. I'm going to close this PR and approve yours.

**Pull request closed without merging**
