### PR TITLE
Fix Sentry Version

### PR DESCRIPTION
**Pull request by vadim2404**
Use `GIT_VERSION` to display it in Sentry instead of package version

Closes: #3438

### CODE REVIEW

**Review by koivunej — APPROVED** [review]
Previous implementation was just `CARGO_PKG_NAME@CARGO_PKG_VERSION` like `pageserver@0.1.0` which would imply that sentry parses the release string, but the field comment on ClientOptions doesn't mention that: https://docs.rs/sentry/latest/sentry/struct.ClientOptions.html#structfield.release

I think we'll see how this works... I don't know how to create a panic on pageserver in staging for testing how will sentry understand this new version string. We could also just forget about it or we could add a http api which would just `drop(catch_unwind(|| panic!("testing sentry"))); Ok(())` or however one returned a 204 response...

Also noting that we have overrun our sentry plan right now so we couldn't test this right away regardless. So perhaps punt the testing part.

**Comment by vadim2404** [comment]
```2023-01-25T10:07:48.520651Z  INFO version: git:2a54941f03d6c934396acee82c8e6bc13ebe42ea-modified failpoints: true, features: []```

It's how the version will be sent to Sentry

**Comment by koivunej** [comment]
Yeah, I was just wondering where will sentry know that this message comes from the `pageserver` binary? Because before this PR, it could had parsed the version string to know that. Does each pageserver have a different project in sentry, and so the SENTRY_DSN pointing to the project is to determine this?

**Comment by vadim2404** [comment]
yes, there are DSNs per each project

**Pull request merged**
