### PR TITLE
JWT improvements

### PR DESCRIPTION
**Pull request by hlinnaka**
1. Accept all RSA-family algorithms, not just RS256.
2. Add a section to docs on the JWT payload

### CODE REVIEW

**Review by LizardWizzard — COMMENTED** [review]
Changes look good to me. Do you have specific use case you need this for?

Would be good to add a unit test that cycles through `ACCEPTED_ALGORITHMS` and calls decode

**Comment by hlinnaka** [comment]
> Changes look good to me. Do you have specific use case you need this for?

No, I just bumped into this while playing with the auth and the console. I created an RS512 token and didn't understand why I got InvalidAlgorithm. I could've used RS256, instead, but instead of documenting that it must be RS256, we might as well accept RS384 and RS512 too.

> Would be good to add a unit test that cycles through `ACCEPTED_ALGORITHMS` and calls decode

Seems a bit pointless to me. It's just an array of constants. I guess unit tests with some example tokens would be good though, to demonstrate the different claims too.

**Comment by hlinnaka** [comment]
Added some unit tests, please take a look!

**Review by LizardWizzard — APPROVED** [review]
Thanks!

**Pull request merged**
