### PR TITLE
Avoid extending relation in the WAL redo process (bump vendor/postgres)

### PR DESCRIPTION
**Pull request by hlinnaka**
See corresponding PR in the postgres repo: https://github.com/neondatabase/postgres/pull/157

### CODE REVIEW

**Comment by lubennikovaav** [comment]
Cool. 
Does it fix any existing problem or you just noticed a place for improvement?

I am a bit surprised that this change didn't cause any problems with FSM and VM redo.

**Review by lubennikovaav — APPROVED** [review]
Huh. My commit bumped into this issue as well

**Comment by bojanserafimov** [comment]
+1 this fixes the `Timed out while waiting for WAL record` issue I got too

**Comment by hlinnaka** [comment]
> Does it fix any existing problem or you just noticed a place for improvement?
> 
> I am a bit surprised that this change didn't cause any problems with FSM and VM redo.

Yeah, this fixes https://github.com/neondatabase/neon/issues/1615.

**Pull request merged**
