### PR TITLE
remove materialized page cache

### PR DESCRIPTION
**Pull request by problame**
part of Epic https://github.com/neondatabase/neon/issues/7386

# Motivation

The materialized page cache adds complexity to the code base, which increases the maintenance burden and risk for subtle and hard to reproduce bugs such as #8050.

Further, the best hit rate that we currently achieve in production is ca 1% of materialized page cache lookups for `task_kind=PageRequestHandler`. Other task kinds have hit rates <0.2%.

Last, caching page images in Pageserver rewards under-sized caches in Computes because reading from Pageserver's materialized page cache over the network is often sufficiently fast (low hundreds of microseconds). Such Computes should upscale their local caches to fit their working set, rather than repeatedly requesting the same page from Pageserver.

Some more discussion and context in internal thread https://neondb.slack.com/archives/C033RQ5SPDH/p1718714037708459

# Changes

This PR removes the materialized page cache code & metrics.

The infrastructure for different key kinds in `PageCache` is left in place, even though the "Immutable" key kind is the only remaining one.
This can be further simplified in a future commit.

Some tests started failing because their total runtime was dependent on high materialized page cache hit rates. This test makes them fixed-runtime or raises pytest timeouts:
* test_local_file_cache_unlink
* test_physical_replication
* test_pg_regress

# Performance

I focussed on ensuring that this PR will not result in a performance regression in prod.

* **getpage** requests: our production metrics have shown the materialized page cache to be irrelevant (low hit rate). Also, Pageserver is the wrong place to cache page images, it should happen in compute.
* **ingest** (`task_kind=WalReceiverConnectionHandler`): prod metrics show 0 percent hit rate, so, removing will not be a regression.
* **get_lsn_by_timestamp**: important API for branch creation, used by control pane. The clog pages that this code uses are not materialize-page-cached because they're not 8k. No risk of introducing a regression here.

We will watch the various nightly benchmarks closely for more results before shipping to prod.

### CODE REVIEW

**Comment by problame** [comment]
The failures are due to timeouts, will push changes that fix the tests to have fixed runtime and/or raise timeouts.

Rationale for that is that these tests are single-tenant tests that were previously fast because they had excellent materialized page cache hit rates. As stated in the PR description, that's something we want to discourage. Real computes should increase their shared_buffers/LFC. For the tests, we'd rather still hit the Pageservers to exercise the code, rather than increase their cache sizes.

**Comment by problame** [comment]
The `pg_regress` failure in release mode is a bit concerning though (see regress.diffs artifact). It's not due to timeout afaict https://neon-github-public-dev.s3.amazonaws.com/reports/pr-8105/9573053274/index.html#suites/158be07438eb5188d40b466b6acfaeb3/bfde9639f5187a1/ 

Note this PR is on top of #8050 and further, the bug fixed by #8050 can't happen with materialized page cache. So, is this a different issue?

**Comment by problame** [comment]
> Let's be thoughtful about when we merge: maybe immediately after next week's release branch is cut, so that we get the full week in staging?

I would rather merge today & do an early deploy to pre-prod so we get multiple prodlike cloudbench run results.

**Comment by jcsp** [comment]
>I would rather merge today & do an early deploy to pre-prod so we get multiple prodlike cloudbench run results. (Reverting by end of week or on the weekend is less disruption than reverting on Monday )

Works for me.

**Comment by problame** [comment]
Trying to repro the pg_regress test failure in
* https://github.com/neondatabase/neon/pull/8114

stacked atop this PR

**Comment by hlinnaka** [comment]
> The `pg_regress` failure in release mode is a bit concerning though (see regress.diffs artifact). It's not due to timeout afaict https://neon-github-public-dev.s3.amazonaws.com/reports/pr-8105/9573053274/index.html#suites/158be07438eb5188d40b466b6acfaeb3/bfde9639f5187a1/

At quick glance, those are caused by differences in result set ordering. If you do something like `SELECT * FROM foo`, with no `ORDER BY`, the order of the results is not well-defined. The Postgres regression test suite contains a lot of queries like that are sensitive to row ordering, and in theory at the whim of implementation details, but are stable in practice and not usually causing any trouble.

The 'portals' test that failed here is more sensitive than most. 
See https://www.postgresql.org/message-id/flat/1246440.1693883808%40sss.pgh.pa.us for upstream discussion on this topic.
 If you run it with a very small shared_buffers setting, the "synchronous scans" feature can kick in and cause the result set ordering to change. I think that's what happened here.

If it's a one-off thing and doesn't repeat, I'd say ignore it. If it happens again, then we can try e.g. set `synchronize_seqscans=off` for the that test.

**Comment by problame** [comment]
So, why are the tests timing out with `pytest.mark.repeat()`?

* we use `pytest-xdist` to [run 16 tests in parallel ](https://github.com/neondatabase/neon/blob/feb359b45924252da4eb4863a6c92d970ab46958/.github/actions/run-python-test-set/action.yml#L133)
* the `pg_regress` test, especially in debug mode where we do the validation, is much more CPU intensive than your typical test
* so when we run only the `pg_regress` test, and 16 of them in parallel, we become CPU-bottlenecked
* this results in longer test runtimes
* that's why we hit the timeout

**Comment by problame** [comment]
I'm merging this, as I am convinced that the pg_regress failure that we observed isn't due to changes in this PR https://github.com/neondatabase/neon/pull/8105#issuecomment-2178342259

I'm going to deploy to pre-prod post-merge so we get 4 benchmark runs before next week's release.

**Comment by problame** [comment]
Post-merge commit failed two `test_runenr.performance` benchmarks ([Allure](https://neon-github-public-dev.s3.amazonaws.com/reports/main/9595406428/index.html#suites/c62b105f3a4f00dd6be4ad88810e0e02/bb9b621b083e380b/))

```
test_heavy_write_workload[neon_off-release-pg14-github-actions-selfhosted-10-5-5]
test_basebackup_with_high_slru_count[release-pg14-github-actions-selfhosted-sequential-10-13-30]
```

However, two commits earlier, these benchmarks also failed ([Allure](https://neon-github-public-dev.s3.amazonaws.com/reports/main/9585688110/index.html#suites/026a52828e77063ffa9cfe9b0b3e7d5e))

So, I'm moving on with the plan to deploy to pre-prod.

**Comment by knizhnik** [comment]
Let's make a bet:)
How long time will be needed to storage team to reincornate materialized page cache.
My guess is one year;)

Why do I think so? Three main arguments:
1. Page reconstruction is still quite expensive operation. Doesn't matter how we will optimise walredo process, may be ever rewrite redo handlers in Rust and throw away walredo process at all. It still be quite expensive operation comparing with taking page from cache. And caching is the most straightforward, natural, simple and efficient way to reduce cost of expensive operations.
2. There is quite a lot of memory on PS. And not so many things which it can be used for (except OS file cache).
3. Alternative of caching materialised pages is enforced generation of image layers. But it cause significant write amplification and may affect overall performance. Partial image layers can be some kind of compromise.

As far as I understand the main arguments against materialised cache were:
1. Small hit rate
2. Troubles with implementation and contention.

First can be explained by too small cache size and it's flushing by other requests (I am not sure if we have now separate cache for materialised page as I suggested long long time ago).
Concerning 2) we should definitely thanks Rust for it. It managed to make simplest things non-trivial.

To be honest, I see several arguments for removing this cache:
1. We assume that compute will keep frequently accessed pages in shared buffer or LFC. But it doesn't work for node restart and RO  replicas.
2. If page is rarely updated, then it may be more efficient to create image layer to materialise it. If page is frequently updated, then materialized cache will be frequently invalidated, so maintaining it will slowdown writes but not speed up reads.
3. Page reconstruction cost can be negligible, comparing with compute<->roundtrip. But it is not true for prefetch.

**Pull request merged**
