### PR TITLE
Release 2022-11-16

### PR DESCRIPTION
**Pull request by petuhovskiy**
## Release 2022-11-16

**NB: this PR must be merged only by 'Create a merge commit'!**

### Checklist when preparing for release
- [x] Read or refresh [the release flow guide](https://github.com/neondatabase/cloud/wiki/Release:-general-flow)
- [x] Ask in the [cloud Slack channel](https://neondb.slack.com/archives/C033A2WE6BZ) that you are going to rollout the release. Any blockers?
- [ ] Does this release contain any db migrations? Destructive ones? What is the rollback plan?

### Checklist after release
- [ ] Based on the merged commits write release notes and open a PR into `website` repo ([example](https://github.com/neondatabase/website/pull/219/files))
- [ ] Check [#dev-production-stream](https://neondb.slack.com/archives/C03F5SM1N02) Slack channel
- [ ] Check [stuck projects page](https://console.neon.tech/admin/projects?sort=last_active&order=desc&stuck=true)
- [ ] Check [recent operation failures](https://console.neon.tech/admin/operations?action=create_timeline%2Cstart_compute%2Cstop_compute%2Csuspend_compute%2Capply_config%2Cdelete_timeline%2Cdelete_tenant%2Ccreate_branch%2Ccheck_availability&sort=updated_at&order=desc&had_retries=some)
- [ ] Check [cloud SLO dashboard](https://observer.zenith.tech/d/_oWcBMJ7k/cloud-slos?orgId=1)
- [ ] Check [compute startup metrics dashboard](https://observer.zenith.tech/d/5OkYJEmVz/compute-startup-time)

### CODE REVIEW

**Review by vadim2404 — APPROVED** [review]

**Comment by SomeoneToIgnore** [comment]
> ERROR test_runner/regress/test_tenant_detach.py::test_tenant_detach_smoke - A...
[21510](https://github.com/neondatabase/neon/actions/runs/3478886460/jobs/5817012289#step:4:21535)

I see that test failing in recent `main` builds, so might it be better to fix all flacky tests before the release? We've just passed a storm of infra-induced CI failures, a few more PRs are worth adding to check the real CI state.

**Comment by SomeoneToIgnore** [comment]
Also seems that new AWS S3 library does misbehave: https://neondb.slack.com/archives/C033RQ5SPDH/p1668603855323639

**Comment by hlinnaka** [comment]
> > ERROR test_runner/regress/test_tenant_detach.py::test_tenant_detach_smoke - A...
> > [21510](https://github.com/neondatabase/neon/actions/runs/3478886460/jobs/5817012289#step:4:21535)
> 
> I see that test failing in recent `main` builds, so might it be better to fix all flacky tests before the release? We've just passed a storm of infra-induced CI failures, a few more PRs are worth adding to check the real CI state.

Opened https://github.com/neondatabase/neon/pull/2835 to silence that one

**Comment by koivunej** [comment]
Like #2835 this failure on aca221a seems to be from log checking, but I don't understand why did it not appear on earlier commits: https://neon-github-public-dev.s3.amazonaws.com/reports/pr-2833/debug/3479514375/index.html#suites/158be07438eb5188d40b466b6acfaeb3/f35e944d274fac0c/ on test_pg_regress:

```
AssertionError: assert not ["2022-11-16T13:17:16.687928Z ERROR query handler for 'pagestream fd89af6f79b8c6fd2c85c11d7fae1556 40ac9dce4d679f3123b4aa9f4d3abb48' failed: unexpected message: Terminate during COPY\n"]
```

**Comment by koivunej** [comment]
Address already in use for the required `regress-tests (release)` even though the other one passed: https://github.com/neondatabase/neon/actions/runs/3479927132/jobs/5819243272#step:4:1291

`regress-tests (debug)` failed on https://github.com/neondatabase/neon/actions/runs/3479927132/jobs/5819243138#step:4:1230 which seems to be #2831.

**Comment by SomeoneToIgnore** [comment]
Reverting the aws s3 merge: https://github.com/neondatabase/neon/pull/2837

**Comment by petuhovskiy** [comment]
Looks like @SomeoneToIgnore just merged the revert. Let's wait until all projects are fixed on staging and try to release after that.

**Comment by andresrsanchez** [comment]
f*** sorry :(
let me check the errors @SomeoneToIgnore

**Pull request merged**
