### PR TITLE
Back off when reenqueueing delete tasks

### PR DESCRIPTION
**Pull request by SomeoneToIgnore**
Closes https://github.com/neondatabase/neon/issues/2183

### CODE REVIEW

**Comment by hlinnaka** [comment]
Thanks, that was quick & simple!

Do we have any tests for S3 upload/download failures and retries?

**Review by hlinnaka — APPROVED** [review]

**Comment by SomeoneToIgnore** [comment]
> Do we have any tests for S3 upload/download failures and retries?

Not those kind of failures, alas, I've also felt odd to submit such small PR without tests.
We should create one, but looks like we have to use fallpoints for that, since nit sure how to get it unit tested properly (one could write a test on the batch processing method, but not sure if it's worth it right now).

**Comment by LizardWizzard** [comment]
There is one failpoint: "remote-storage-download-pre-rename" it is used to trigger collection of temporary download files on pageserver restart. So we can do that in similar fashion. But we dont expose retries info to outside world, so we can try to track retries via metrics, or use some kind of mocking

**Comment by hlinnaka** [comment]
We have the abstraction over remote storage, maybe we could introduce a "chaos" mode there that randomly fails some percentage of requests. :thinking:

**Pull request merged**
