### PR TITLE
Move `control_plane` pageserver/safekeeper deps into `libs/{pageserver,safekeeper}_api`

### PR DESCRIPTION
**Pull request by sharnoff**
Commit header could use some work. Otherwise, mostly what the commit message says:

> Remove control_plane deps on pageserver/safekeeper
>
> Creates new `pageserver_api` and `safekeeper_api` crates to serve as the shared dependencies. Should reduce both recompile times and cold compile times.
>
> Decreases the size of the optimized `neon_local` binary: 380M -> 179M. No significant changes for anything else (mostly as expected).

Anecdotally, I've noticed that recompiling (or waiting for rust-analyzer to catch up) while working on the pageserver can take weirdly long time, with the compiler spending some amount of that recompiling `control_plane`, even though changes haven't been made to the things it uses (which... makes sense, because it lists `pageserver` as a dependecy).

This PR moves the pageserver/safekeeper APIs that `control_plane` was using into separate `libs/*` crates, so that `control_plane` can be compiled in parallel with them, instead of waiting until after they're done.

I was surprised by the amount of change in the size of `neon_local`. Our release profile doesn't use LTO though, so perhaps that's shouldn't be so surprising. (release LTO=fat takes 2.5x longer, and release LTO=thin takes ~1.4x longer; probably too long to be _that_ useful right now.).

Tested recompile times by deleting a comment in pageserver/src/lib.rs: about 4 seconds to recompile `--release` both with and without the change; 27 vs 29 seconds to recompile (debug) with vs without the change, respectively. `rust-analyzer` is a bit different: Eyeballing it with `top` and a stopwatch, it seems like this PR changes the update time for RA (on the same "delete a comment") from ~5s to ~4s. Overall, not much of a difference, but this maybe differences aren't as prominent if you only change a comment.

### CODE REVIEW

**Comment by hlinnaka** [comment]
> I was surprised by the amount of change in the size of `neon_local`. Our release profile doesn't use LTO though, so perhaps that's shouldn't be so surprising. (release LTO=fat takes 2.5x longer, and release LTO=thin takes ~1.4x longer; probably too long to be _that_ useful right now.).

It makes sense: most of the binary size is used by debuginfo. See https://github.com/neondatabase/cloud/issues/1768#issuecomment-1181476480. The linker removes unused code, but it doesn't remove debuginfo of the eliminated code. (That's bonkers, but apparently that's how the linker works currently. I wish that would get fixed in the linker one day..)

**Comment by hlinnaka** [comment]
I did some more googling on the debuginfo and binary size isssue, and found this hack: https://github.com/benesch/materialize/commit/02cc34cb7c7d9f1b775fe95e1697b797d8fa9b6d#diff-d889dd78ffee42be8358a583601a178d01e52cbd7ca774f6c9b759c640977660R166.

That seems very effective, only takes a few seconds,  with no apparent downside. On our debug binaries:
```
/data/tmp$ ls -l debug-orig/
total 2204980
-rwxr-xr-x 1 heikki heikki 110227136 Sep 23 14:17 compute_ctl
-rwxr-xr-x 1 heikki heikki 335055704 Sep 21 10:18 dump_layerfile
-rwxr-xr-x 1 heikki heikki 435575960 Sep 21 10:18 neon_local
-rwxr-xr-x 1 heikki heikki 399233912 Sep 21 10:18 pageserver
-rwxr-xr-x 1 heikki heikki 184511912 Sep 21 10:15 proxy
-rwxr-xr-x 1 heikki heikki 339497136 Sep 21 10:17 safekeeper
-rwxr-xr-x 1 heikki heikki 334394680 Sep 21 10:18 update_metadata
-rwxr-xr-x 1 heikki heikki 119361832 Sep 21 10:15 wal_craft
/data/tmp$ mkdir debug-after
/data/tmp$ cp debug-orig/* debug-after/
/data/tmp$ time find debug-after | xargs -Ifoo objcopy -R .debug_pubnames -R .debug_pubtypes foo
objcopy: Warning: 'debug-after' is a directory

real	0m3.855s
user	0m0.384s
sys	0m2.190s
/data/tmp$ ls -l debug-after/
total 1450988
-rwxr-xr-x 1 heikki heikki  81528768 Sep 24 12:57 compute_ctl
-rwxr-xr-x 1 heikki heikki 214730280 Sep 24 12:57 dump_layerfile
-rwxr-xr-x 1 heikki heikki 276485760 Sep 24 12:57 neon_local
-rwxr-xr-x 1 heikki heikki 257272640 Sep 24 12:57 pageserver
-rwxr-xr-x 1 heikki heikki 133922512 Sep 24 12:57 proxy
-rwxr-xr-x 1 heikki heikki 218035920 Sep 24 12:57 safekeeper
-rwxr-xr-x 1 heikki heikki 214068096 Sep 24 12:57 update_metadata
-rwxr-xr-x 1 heikki heikki  89748808 Sep 24 12:57 wal_craft
/data/tmp$ du -h debug-orig/ debug-after
2.2G	debug-orig/
1.4G	debug-after
```

**Comment by hlinnaka** [comment]
> I did some more googling on the debuginfo and binary size isssue, and found this hack: [benesch/materialize@02cc34c#diff-d889dd78ffee42be8358a583601a178d01e52cbd7ca774f6c9b759c640977660R166](https://github.com/benesch/materialize/commit/02cc34cb7c7d9f1b775fe95e1697b797d8fa9b6d#diff-d889dd78ffee42be8358a583601a178d01e52cbd7ca774f6c9b759c640977660R166).

Opened https://github.com/neondatabase/neon/pull/2514 to do that. But that's orthogonal to the savings from this PR.

**Review by SomeoneToIgnore — APPROVED** [review]
Very nice finding, thank you.

I suspect you've run `cargo hakari` on the things to update the `workspace_hack` dependencies, but adding a reminder just in case.

**Pull request merged**
