### PR TITLE
buildtools: update protoc and mold

### PR DESCRIPTION
**Pull request by arpad-m**
These updates aren't very important but I would like to try out the new process as of #6195

### CODE REVIEW

**Comment by abhigets** [comment]
waiting for all checks to pass 
but Looks good to me

**Review by bayandin — APPROVED** [review]
Nice!

Just a reminder that we still need to make image pinned manually: 
https://github.com/neondatabase/neon/blob/main/CONTRIBUTING.md#how-do-i-add-the-pinned-tag-to-an-buildtools-image

**Comment by arpad-m** [comment]
The CI run for the tagging is here: https://github.com/neondatabase/neon/actions/runs/7291140117

I used `7289718682` for the source tag (found it via [checks](https://github.com/neondatabase/neon/pull/6222/checks) tab -> "Build and Test" -> ["neon-image"](https://github.com/neondatabase/neon/actions/runs/7289718682/job/19864969322?pr=6216) -> "Kaniko build Neon" ->  number next to `BUILD_TAG` ; also part of the URL of the "Build and Test" job). but that apparently gave an error:
```
Run NEXT_DIGEST=$(crane digest ${IMAGE}:${FROM_TAG} || true)
2023/12/21 17:10:06 HEAD request failed, falling back on GET: HEAD https://369495373322.dkr.ecr.eu-central-1.amazonaws.com/v2/build-tools/manifests/7289718682: unexpected status code 404 Not Found (HEAD responses have no body, use GET for details)
Error: GET https://369495373322.dkr.ecr.eu-central-1.amazonaws.com/v2/build-tools/manifests/7289718682: MANIFEST_UNKNOWN: Requested image not found
```

**Comment by bayandin** [comment]
> I used `7289718682` for the source tag (found it via [checks](https://github.com/neondatabase/neon/pull/6222/checks) tab -> "Build and Test" -> ["neon-image"]

It should be `7289833292` from https://github.com/neondatabase/neon/actions/runs/7289833292 (`GITHUB_RUN_ID` of the latest successful job in the PR)

**Comment by arpad-m** [comment]
[that worked](https://github.com/neondatabase/neon/actions/runs/7291271280), it seems I forgot to press `F5`. This is a much smoother process now, thanks @abhigets !

**Pull request merged**
