### PR TITLE
Keep walproposer alive until shutdown checkpoint is safe on safekepeers

### PR DESCRIPTION
**Pull request by hlinnaka**
The walproposer pretends to be a walsender in many ways. It has a WalSnd slot, it claims to be a walsender by calling MarkPostmasterChildWalSender() etc. But one different to real walsenders was that the postmaster still treated it as a bgworker rather than a walsender. The difference is that at shutdown, walsenders are not killed until the very end, after the checkpointer process has written the shutdown checkpoint and exited.

As a result, the walproposer always got killed before the shutdown checkpoint was written, so the shutdown checkpoint never made it to safekeepers. That's fine in principle, we don't require a clean shutdown after all. But it also feels a bit silly not to stream the shutdown checkpoint. It could be useful for initializing hot standby mode in a read replica, for example.

Change postmaster to treat background workers that have called MarkPostmasterChildWalSender() as walsenders. That unfortunately requires another small change in postgres core.

After doing that, walproposers stay alive longer. However, it also means that the checkpointer will wait for the walproposer to switch to WALSNDSTATE_STOPPING state, when the checkpointer sends the PROCSIG_WALSND_INIT_STOPPING signal. We don't have the machinery in walproposer to receive and handle that signal reliably. Instead, we mark walproposer as being in WALSNDSTATE_STOPPING always.

In commit 568f91420a, I assumed that shutdown will wait for all the remaining WAL to be streamed to safekeepers, but before this commit that was not true, and the test became flaky. This should make it stable again.

Closes: https://github.com/neondatabase/neon/issues/559

### CODE REVIEW

**Comment by arssher** [comment]
> I can't check the changes made in the various PG versions due to what seems to be GitHub UI error

Looks like PG change push is missing in the repo.

**Comment by arssher** [comment]
So I can't yet check out the core changes, but I wonder why postmaster treated walproposer as bgw prevously. Looking at SignalSomeChildren/CountChildren it checks only bkend_type, which is set to BACKEND_TYPE_WALSND soon after MarkPostmasterChildWalSender...

**Comment by hlinnaka** [comment]
> Looks like PG change push is missing in the repo.

Created branches for those and pushed, should be visible now.

> So I can't yet check out the core changes, but I wonder why postmaster treated walproposer as bgw prevously. Looking at SignalSomeChildren/CountChildren it checks only bkend_type, which is set to BACKEND_TYPE_WALSND soon after MarkPostmasterChildWalSender...

The postgres changes show that, but in a nutshell, because walproposer is marked as  BACKEND_TYPE_BGWORKER, postmaster never calls IsPostmasterChildWalSender() on it. Postmaster expects that a BACKEND_TYPE_NORMAL process can morph into a walsender, but not a bgworker.

**Comment by arssher** [comment]
There several more things to do:
- Check currently is in wrong place, it won't fire until latch is set.
- We need to wait not only for flush_lsn on the quorum, but commit_lsn -- safekeepers don't advance commit position in the absense of compute.
- Also commit_lsn should be not only recorded, but persisted on safekeepers (otherwise their restart would pull it back); they do that periodically, but we want here that ASAP.
- Add test.

I'll try to finish it.

**Comment by arssher** [comment]
Interesting, locally it already works without any fixes. Checked, this is because after checkpoint is flushed postmaster kills walproposer with SIGUSR2, which sets the latch, and walproposer manages to commit (and send commit_lsn) to safekeeper before this.

**Comment by jcsp** [comment]
In https://github.com/neondatabase/neon/pull/6751 I'm reverting the previous change that appears to have made test_pg_regress less stable -- would probably make sense to revert the revert in this PR, along with the walproposer changes.  Hopefully together they make the test stable.

**Comment by jcsp** [comment]
In case this is useful: a failure on a branch where I had an explicit wait_for_flush_lsn before compute stop and logged the before + after LSNs, where it looks like the safekeeper _has_ seen the post-stop LSN, but the pageserver hasn't https://github.com/neondatabase/neon/pull/6752#issuecomment-1943752039

**Comment by arssher** [comment]
> There several more things to do:

Mostly did them, now need to merge PG PRs and then this one. @hlinnaka please have a look, I can't request your review :)

**Review by knizhnik — APPROVED** [review]

**Pull request merged**
