### PR TITLE
storage_controller: add pageserver remote storage access

### PR DESCRIPTION
**Pull request by erikgrinaker**
## Problem

The storage controller might need access to pageserver remote storage for housekeeping operations. This is motivated by #8308, where tenant deletion must delete remote storage data for past (pre-split) shards that the current shards may still reference.

Initially, this was implemented as a special case in the pageserver delete tenant API. However, pageserver APIs are shard-scoped since a pageserver does not have access to the full set of shards, and adding a special case for tenant-wide operations via a shard-scoped API appeared confusing and error-prone. Giving the storage controller access to pageserver remote storage allows it to perform such tenant-wide operations without the impedance mismatch of using a shard-scoped API.

See discussion in https://github.com/neondatabase/neon/pull/9333#pullrequestreview-2362994293.

## Summary of changes

* Add a `--pageserver-remote-storage` argument taking a TOML config.
* Adapt `neon_local` to pass the pageserver storage to `storage_controller`.

## Checklist before requesting a review

- [ ] I have performed a self-review of my code.
- [ ] If it is a core feature, I have added thorough tests.
- [ ] Do we need to implement analytics? if so did you add the relevant metrics to the dashboard?
- [ ] If this PR requires public announcement, mark it with /release-notes label and add several sentences in this section.

## Checklist before merging

- [ ] Do not forget to reformat commit message to not include the above checklist

### CODE REVIEW

**Comment by erikgrinaker** [comment]
@VladLazar @jcsp This will likely need more plumbing to make sure all tests and infrastructure works, not to mention deployment considerations, but I'd like to get your overall take on this before spending any more time on it.

**Comment by jcsp** [comment]
This feels like a somewhat finely balanced complexity tradeoff -- whether it is more complex to:
A) Extra code in the pageserver that only exists to let the controller get at remote storage (e.g. deletion, `/v1/tenant/:tenant_id/scan_remote_storage`, perhaps running scrubs on-demand)
B) Extra deployment/config bits to give the storage controller direct access to S3.  This probably wouldn't just be the pageserver bucket, if we follow this pattern it'll want the safekeeper bucket too.

A feels simpler in cognitive terms: the S3 bucket is accessed by exactly one service.  B feels simpler in machine terms: we have less extra code for API hops through the pageserver.

Let's take it to slack and talk about what else we might want to use this controller->S3 access for?  That might help motivate it.

**Comment by erikgrinaker** [comment]
For me, what tipped it in favor of lifting it up into storage controller is the division of responsibility between tenants and shards: the pageservers are responsible for individual shards, the storage controller is responsible for orchestrating the entire tenant across shards.

I agree with your points though, and it's not clear that this should be the primary axis of responsibility either. I could be convinced to defer the decision until we have a more compelling case with additional uses, and dispatch to a specialized pageserver API in the meanwhile.

See also [Slack discussion](https://neondb.slack.com/archives/C033RQ5SPDH/p1728993338890879).

**Comment by erikgrinaker** [comment]
Dropping this for now. It may not be ideal to do tenant-wide operations via pageservers, but it's not clear at the moment where it should belong (possibly in a separate service for background tasks and housekeeping). Will revisit.

**Pull request closed without merging**
