### PR TITLE
pgxn: Fix compiler warnings, and enable them

### PR DESCRIPTION
**Pull request by hlinnaka**
Two parts to this PR:

1. Don't override CFLAGS when building neon extension

   If you override CFLAGS, you also override any flags that PostgreSQL configure script had picked. That includes many options that enable extra compiler warnings, like '-Wall', '-Wmissing-prototypes', and so forth. The override was added in commit 171385ac14, but the intention of that was to be *more* strict, by enabling '-Werror', not less strict. The proper way of setting '-Werror', as documented in the docs and mentioned in PR #2405, is to set COPT='-Werror', but leave CFLAGS alone.

   The last commit in the PR does that.

2. All the other commits before the last one are fixing warnings that you get with the standards PostgreSQL compiler options, when you stop overriding CFLAGS.

Fixes https://github.com/neondatabase/neon/issues/9217

### CODE REVIEW

**Review by bayandin — APPROVED** [review]
Thanks!

**Review by knizhnik — APPROVED** [review]

**Comment by tristan957** [comment]
I think it would be good to split this up into separate PRs. It would be a shame to lose the git history after the squash and merge :(

**Comment by hlinnaka** [comment]
> I think it would be good to split this up into separate PRs. It would be a shame to lose the git history after the squash and merge :(

Pushed from command line, so that the commits were preserved

**Comment by tristan957** [comment]
Feels like this is a situation that's perfect for rebase & merge.

**Pull request merged**
