### PR TITLE
Reduce max_replication_write_lag to 10Mb

### PR DESCRIPTION
**Pull request by knizhnik**

### CODE REVIEW

**Comment by petuhovskiy** [comment]
We probably should also update it in the console, I found several references there:
- https://github.com/neondatabase/cloud/blob/3942abd11f046e175dce3a977970671033ac184e/goapp/internal/controllers/publicapiv2/settings.go
- https://github.com/neondatabase/cloud/blob/a6039b88da608c36e9cf8334e015229018f5a834/goapp/internal/model/project.go

**Comment by lubennikovaav** [comment]
@knizhnik , I added small fix to tests and pushed to trigger tests again.

**Comment by hlinnaka** [comment]
Rebased

**Comment by stepashka** [comment]
@knizhnik , any next steps planned for this?
have we merged this?
was it causing any troubles?

**Comment by stepashka** [comment]
we've increased the lag to 15 MBs, maybe we can close this PR?

**Comment by knizhnik** [comment]
> we've increased the lag to 15 MBs, maybe we can close this PR?

We have not changed default value.
There is really IMHO stupid situation that some our default settings, particularly `wal_log_hints` and `max_replication write_lag`, which are different from what are actually used for tests and in staging/production.

**Comment by knizhnik** [comment]
Done

**Review by hlinnaka — APPROVED** [review]
Are these values now the same that we use in production?

**Review by vadim2404 — APPROVED** [review]

**Pull request merged**
