### PR TITLE
Use ready! rustc 1.64 macro

### PR DESCRIPTION
**Pull request by SomeoneToIgnore**
rustc [1.64](https://github.com/rust-lang/rust/blob/master/RELEASES.md#version-1640-2022-09-22) had brought `ready!` macro: https://doc.rust-lang.org/stable/std/task/macro.ready.html

Use it to shorten the code slightly.

### CODE REVIEW

**Review by funbringer — APPROVED** [review]

**Review by ololobus — APPROVED** [review]

**Review by koivunej — APPROVED** [review]
You probably had this ready to go right after :)

**Comment by koivunej** [comment]
I was thinking at first the failure looked like a port already in use, but this seems new for me: https://neon-github-public-dev.s3.amazonaws.com/reports/pr-3315/release/3903582277/index.html#suites/0fbaeb107ef328d03993d44a1fb15690/d7e5d24ebc8f1c75/

pg says:

```
2023-01-12 15:34:55.341 GMT [13873] LOG:  starting with zenith basebackup at LSN 0/AA31D80, prev 0/0
2023-01-12 15:34:55.341 GMT [13873] FATAL:  cannot start in read-write mode from this base backup
```

Haven't seen this one yet.
```

**Comment by ololobus** [comment]
> FATAL:  cannot start in read-write mode from this base backup

We had this issue (or better say the same symptom) before https://github.com/neondatabase/neon/issues/1351. And that time it was a problem with safekeepers

**Comment by koivunej** [comment]
Hmm but the issue is already closed. Looking through the other log files I cannot find anything notable... Maybe I'll just create a new issue and the workflow can be retried?

**Comment by koivunej** [comment]
Ah, should had searched, better one was found quickly: https://github.com/neondatabase/neon/issues/2963

**Pull request merged**
