### PR TITLE
remote_storage: AWS_PROFILE with endpoint overrides in ~/.aws/config (updates AWS SDKs)

### PR DESCRIPTION
**Pull request by problame**
Before this PR, using the AWS SDK profile feature for running against minio didn't work because 
* our SDK versions were too old and didn't include
  https://github.com/awslabs/aws-sdk-rust/issues/1060 and 
* we didn't massage the s3 client config builder correctly.

This PR
* udpates all the AWS SDKs we use to, respectively, the latest version I could find on crates.io (Is there a better process?)
* changes the way remote_storage constructs the S3 client, and
* documents how to run the test suite against real S3 & local minio.

Regarding the changes to `remote_storage`: if one reads the SDK docs, it is clear that the recommended way is to use `aws_config::from_env`, then customize.
What we were doing instead is to use the `aws_sdk_s3` builder directly.

To get the `local-minio` in the added docs working, I needed to update both the SDKs and make the changes to the `remote_storage`. See the commit history in this PR for details.

Refs:
* byproduct: https://github.com/smithy-lang/smithy-rs/pull/3633
* follow-up on deprecation: https://github.com/neondatabase/neon/issues/7665
* follow-up for scrubber S3 setup: https://github.com/neondatabase/neon/issues/7667

### CODE REVIEW

**Review by koivunej — APPROVED** [review]
A bit weird that we now have both http body versions but, maybe that'll go away with your follow-ups?

**Comment by problame** [comment]
> both http body versions

Can you link to what you're referring to here? I'm not following

**Comment by arpad-m** [comment]
Have you checked whether the commands written in #6202 still work with this PR applied?

**Comment by problame** [comment]
Yep, still works.  Extended the docs in this PR.

Verified manually that the tests actually use the env-var-configured bucket / credentials.

Side note: the `s3_time_travel_recovery_works` test doesn't work against minio.

**Comment by arpad-m** [comment]
> Side note: the `s3_time_travel_recovery_works` test doesn't work against minio.

That's probably because the bucket doesn't have versioning enabled. It needs to be enabled explicitly (also in S3 but those buckets are long lived and the configuration lives outside of this repo). For #6533's pytest changes I had to add a `enable_remote_storage_versioning` function to enable versioning for the bucket and then call it.

**Pull request merged**
