### PR TITLE
Enable neon-pool-opt-in

### PR DESCRIPTION
**Pull request by vadim2404**

### CODE REVIEW

**Comment by petuhovskiy** [comment]
You also need to insert `static ALLOW_POOL: HeaderName = HeaderName::from_static("neon-pool-opt-in");` on the line 47.

**Comment by vadim2404** [comment]
Added, but it wasn't in your revert?

**Comment by petuhovskiy** [comment]
What do you mean? Code won't compile without `ALLOW_POOL` declared and we should remove the [diff](https://github.com/neondatabase/neon/compare/main...release) between release and main.

**Review by petuhovskiy — APPROVED** [review]

**Comment by vadim2404** [comment]
@petuhovskiy 

I meant that I just reverted your PR. Why weren't these changes presented in it?

**Comment by petuhovskiy** [comment]
Got it. There were 2 PRs: https://github.com/neondatabase/neon/pull/4996 and https://github.com/neondatabase/neon/pull/4997 because of lint issues. Generally I think we rushed the hotfix too much and release could have been just a normal pr->main->release without these issues.

**Comment by vadim2404** [comment]
Okay, understood.

**Pull request merged**
