### PR TITLE
Add race-free version of remove_dir_all

### PR DESCRIPTION
**Pull request by arpad-m**
## Problem

In #6310 we saw flakily occuring strange errors in CI that would be explained by race conditions in `remove_dir_all` being hit. The `remove_dir_all` function from std::fs is not immune from other operations racing it, even if the racing operation is another removal operation (either `remove_dir_all` for same entire directory, or a subdirectory, or even just a single file/empty directory).

We now add a version of `remove_dir_all` that ignores not found errors and continues with the recursive operation to the best of its ability. Simulating this on top of `remove_dir_all` is bound to fail, because in that instance one would ideally add random time backoffs, to not have two such retried operations step on each other's toes all the time. But we don't really want to wait because we'd have to use blocking waits as we want to run the removal in destructors that can't run async.

### CODE REVIEW

**Comment by arpad-m** [comment]
synchronization is dangerous as it adds dependency: we would depend with tenant deletion on a process that might hang indefinitely.

**Comment by arpad-m** [comment]
But we can absolutely add synchronization. Would that work via the Gate mechanism? IDK.

**Review by problame — COMMENTED** [review]
`cleanup_timeline_dir` could probably also use this, although it needs the idempotency but not the correct handling of parallel removal. So, probably better to leave it as is and not make it ignore race conditions.

---

> In #6310 we saw flakily occuring strange errors in CI that would be explained by race conditions in remove_dir_all being hit. The remove_dir_all function from std::fs is not immune from other operations racing it, even if the racing operation is another removal operation (either remove_dir_all for same entire directory, or a subdirectory, or even just a single file/empty directory).

Such a race shouldn't happen, we should use sync primitives inside pageserver to coordinate access to the filesystem.
Did you ever figure out  what exactly was racing?

**Comment by arpad-m** [comment]
> Did you ever figure out what exactly was racing?

The linked PR added a unit test to reproduce tenant deletion racing with timeline creation. The test, in addition to reliably reproducing the original issue #6310 addressed, also now makes any other race condition way more likely.

The observed error ([first occurence](https://github.com/neondatabase/neon/actions/runs/7472643736/job/20335546168), [second occurence](https://github.com/neondatabase/neon/actions/runs/7505071303/job/20433855862)):

```
Failed to remove temporary initdb directory '...': No such file or directory (os error 2)
```

can only happen when the directory either never existed, or when a deletion has either deleted a file or a directory in parallel. If you look at the [implementation](https://github.com/rust-lang/rust/blob/1.75.0/library/std/src/sys/unix/fs.rs#L2084-L2130). Sadly the error does not state which precise file/directory is involved (it's a widely known issue that Rust's errors don't specify the path).

Say task A runs `remove_dir_all(D)`, and task B runs `rm(D/b)` in parallel. Then the following can happen:

a) task A runs `ls D` -> `D/a`, `D/b`, `D/c`
b) task B runs `rm D/b`
c) task A runs `rm D/a` -> success.
d) task A runs `rm D/b` -> Error. file not found (was deleted earlier by b)

Task A then aborts and does not get to delete `D/c`, leaving it behind. It is a bit strange that deleting files can lead to *more* files being left over, but that's how `remove_dir_all` works.

This PR makes step d) tolerant of `D/b` not existing, so that it is more like:

d) task A runs `rm D/b` -> not found but this is not a  file not found (was deleted earlier by b)
e) task A runs `rm D/c` -> success.
e) task A runs `rmdir D` -> directory `D` is now gone.

I couldn't reproduce this locally, even after I re-ran the test a hundred times in a script. Maybe it's because I have a fast local SSD. This PR is shooting into the dark a bit but it does fit to at least the not found errors.

There is also the second error ([occurence](https://github.com/neondatabase/neon/actions/runs/7505071303/job/20433855572)):

```
Failed to remove temporary initdb directory '...': Directory not empty (os error 39)
```

which, according to the impl of remove_dir_all, only occurs when there is some files being added to the directory while the removal is running. I'd imagine sth like, where task A runs `remove_dir_all(D)`:

a) task A: run `ls D` -> `D/a`, `D/b`.
b) task B: add file `D/foobar`. `D` now has children `D/a`, `D/b`, `D/foobar`.
c) task A: rm `D/a`, rm `D/b`.
d) task A: `rmdir D` -> Error: directory is not empty (it still contains `foobar`)

This PR does nothing about this race condition. It's also weirder because in theory nothing is suppose to write into that directory.

It could be that the culprit for both instances, the mysterious "task B", is initdb not sufficiently being killed during cancellation, and still doing some changes to that directory. Note though it's not enough to still keep the files open (that would just unlink them), it has to actively *create* new ones (but I am sure that initdb both creates new files and deletes old ones).

**Comment by arpad-m** [comment]
So *if* it is initdb still running before we delete the directory, it might be the `kill_on_drop` implementation not 100% working? It might just assert that we have sent the sigkill signal but it might not actually wait for the kill to conclude.

So maybe we just need to implement @problame 's suggestion in https://github.com/neondatabase/neon/pull/5921#pullrequestreview-1750858021 ?

**Comment by arpad-m** [comment]
Closing in favour of #6451

**Pull request closed without merging**
