### PR TITLE
Remove non-gzipped basebackup code path

### PR DESCRIPTION
**Pull request by tristan957**
In July of 2023, Bojan and Chi authored
92aee7e07f347a0cc125462705811963ab5c78e9. Our in production pageservers are most definitely at a version where they all support gzipped basebackups.

### CODE REVIEW

**Review by skyzh — APPROVED** [review]

**Comment by tristan957** [comment]
Looks the test-images job is not happy about this change.

Pageserver version:
```
pageserver-1      | 2024-10-18T16:12:44.303221Z  INFO version: git-env:9c7ade36454b80d57cbeeea780027a13e6c371d9 failpoints: true, features: [] launch_timestamp: 2024-10-18 16:12:44.251508855 UTC build_tag: build_tag-env:11406910539
```

**Comment by arpad-m** [comment]
@tristan957 would it be possible to wait a week with this PR to give #9456 some time to settle? That way, if we use lsn(0) on main (not sure if we do), we can do rollbacks safely.

**Comment by tristan957** [comment]
@arpad-m are we good to merge this?

**Comment by arpad-m** [comment]
@tristan957 yes, I think so

**Review by arpad-m — APPROVED** [review]

**Review by mattpodraza — APPROVED** [review]

**Pull request merged**
