### PR TITLE
pageserver: accelerate tenant activation on HTTP API timeline read requests

### PR DESCRIPTION
**Pull request by jcsp**
## Problem

Callers of the timeline creation API may issue timeline GETs ahead of creation to e.g. check if their intended timeline already exists, or to learn the LSN of a parent timeline.

Although the timeline creation API already triggers activation of a timeline if it's currently waiting to activate, the GET endpoint doesn't, so such callers will encounter 503 responses for several minutes after a pageserver restarts, while tenants are lazily warming up.

The original scope of which APIs will activate a timeline was quite small, but really it makes sense to do it for any API that needs a particular timeline to be active.

## Summary of changes

- In the timeline detail GET handler, use wait_to_become_active, which triggers immediate activation of a tenant if it was currently waiting for the warmup semaphore, then waits up to 5 seconds for the activation to complete.  If it doesn't complete promptly, we return a 503 as before.
- Modify active_timeline_for_active_tenant to also use wait_to_become_active, which indirectly makes several other timeline-scope request handlers fast-activate a tenant when called.  This is important because a timeline creation flow could also use e.g. get_lsn_for_timestamp as a precursor to creating a timeline.
- There is some risk to this change: an excessive number of timeline GET requests could cause too many tenant activations to happen at the same time, leading to excessive queue depth to the S3 client.  However, this was already the case for e.g. many concurrent timeline creations.

## Checklist before requesting a review

- [ ] I have performed a self-review of my code.
- [ ] If it is a core feature, I have added thorough tests.
- [ ] Do we need to implement analytics? if so did you add the relevant metrics to the dashboard?
- [ ] If this PR requires public announcement, mark it with /release-notes label and add several sentences in this section.

## Checklist before merging

- [ ] Do not forget to reformat commit message to not include the above checklist

### CODE REVIEW

**Comment by Bodobolero** [comment]
@bodobolero

**Review by koivunej — APPROVED** [review]
this makes sense to me; I have not gathered which endpoints are often called and enjoy 503's but the benchmark should tell us if something still remains.

**Review by arpad-m — APPROVED** [review]
approving under the assumption that a study was done for request patterns of these APIs, as in, whether we send requests for these APIs for a large number of tenants in a high cadence or right after startup (because then, such acceleration will make the lazy loading mechanism pointless)

**Comment by jcsp** [comment]
Yep, we don't have any spikes in these requests in the wild: the background load is from e2e tests running get_lsn_by_timestamp.
image

**Pull request merged**
