### PR TITLE
pageserver: remove two obsolete/unused per-timeline metrics

### PR DESCRIPTION
**Pull request by problame**
over-compensating the addition of a new per-timeline metric in https://github.com/neondatabase/neon/pull/6834

part of https://github.com/neondatabase/neon/issues/6737

### CODE REVIEW

**Review by koivunej — APPROVED** [review]
the tenant metric test might require removing these as well, but we will soon see the test failure.

**Comment by jcsp** [comment]
Wasn't it quite useful to be able to see which tenant was hitting the disk hard via `PERSISTENT_BYTES_WRITTEN`?  Is the idea that `REMOTE_TIMELINE_CLIENT_BYTES_FINISHED_COUNTER` will serve the same purpose (since everything we write to local disk we also write to local storage)?

Not trying to litigate exactly which counters we keep on this PR, but IIRC when we were talking about removing metrics to keep a "one in, one out" policy we talked about, the histograms were the most tempting targets (some in TimelineMetrics) -- removing one histogram will free up enough prometheus resources for several counters.  If we can get rid of a couple of histograms, then we buy ourselves space to add 10-20 more per-timeline counters without having to worry.

**Comment by koivunej** [comment]
>  Is the idea that REMOTE_TIMELINE_CLIENT_BYTES_FINISHED_COUNTER will serve the same purpose (since everything we write to local disk we also write to local storage)?

The `pageserver_io_operations_bytes_total` which is also a `tenant_id, shard_id, timeline_id` with read and write operations. Compared to what is removed here, it should be updated on ephmeral file accesses as well. But it is not the same as per layer file granularity.

> IIRC when we were talking about removing metrics to keep a "one in, one out" policy we talked about, the histograms were the most tempting targets (some in TimelineMetrics)

Note we have fields named "histo" there, but what they do is have a per-timeline sum and count, but update a single global histogram using `StorageTimeMetrics` type.

**Comment by problame** [comment]
I agree with Joonas. We have other means to identify which parts of the system are hitting hte disk. So, these are safe to go.

I'm happy to review PRs that remove histograms, but, these two metrics here have been on my list for some time.

**Review by jcsp — APPROVED** [review]

**Comment by problame** [comment]
I see you clicked re-run on the e2e tests, thanks.

The k8s-neonvm e2e tests has been failing 4 times in a row. Different tests, though.

**Comment by skyzh** [comment]
these two metrics seem to be used in the benchmark workflow on the main branch 😂

**Comment by skyzh** [comment]
https://github.com/neondatabase/neon/actions/runs/8046448628/job/21974547778

```
AssertionError: expected single sample for pageserver_created_persistent_files_total {'tenant_id': '4e6a659570f81b7895b4281a9e2a0d26', 'timeline_id': '5ed6611f985bb54d7157bc5afb6c4ddf'}, found []
```

**Pull request merged**
