### PR TITLE
remove the duplicate entries in postgresql.conf

### PR DESCRIPTION
**Pull request by Reminiscent**
## Problem
fix https://github.com/neondatabase/neon/issues/5088

## Summary of changes
After check the function `write_postgres_conf`, I only find one entry in `postgresql.conf` has been set twice. Just remove the duplicate entry.

## Checklist before requesting a review

- [ ] I have performed a self-review of my code.
- [ ] If it is a core feature, I have added thorough tests.
- [ ] Do we need to implement analytics? if so did you add the relevant metrics to the dashboard?
- [ ] If this PR requires public announcement, mark it with /release-notes label and add several sentences in this section.

## Checklist before merging

- [ ] Do not forget to reformat commit message to not include the above checklist

### CODE REVIEW

**Comment by Reminiscent** [comment]
I'm considering whether we should incorporate a map to keep track of the entries that have already been configured. This way, before setting any new entries, we can first check the map to determine if they have already been set.

**Comment by Reminiscent** [comment]
@hlinnaka Hi, Can you help me review this PR or @ someone to take a look? Thanks!

**Review by bojanserafimov — APPROVED** [review]
Looks good. It should make this file more readable/debuggable.

> I'm considering whether we should incorporate a map to keep track of the entries that have already been configured. This way, before setting any new entries, we can first check the map to determine if they have already been set.

I personally don't see the need for it yet, and I'm not sure if it would be an improvement in terms of readability of the file. Maybe it's nice to be able to explicitly see what was overwritten? Correctness-wise, postgres should consistently pick the last entry from the duplicate options, so there's nothing to worry about there. Let's skip for now

**Comment by Reminiscent** [comment]
@bojanserafimov Sure. I agree with you. Thanks for your review!

**Review by hlinnaka — APPROVED** [review]
LGTM, thanks!

**Comment by Reminiscent** [comment]
@bojanserafimov Hi, it seems some test checks have not worked. So how to run those test checks? Thanks!

**Pull request merged**
