### PR TITLE
Merge release into main to resolve conflicts

### PR DESCRIPTION
**Pull request by petuhovskiy**
~~Bumps vendor/postgres~~ I reverted update to vendor/postgres because some tests have failed

### CODE REVIEW

**Comment by hlinnaka** [comment]
> To resolve conflicts in #2113 (there are a few commits in `release` that were not cherry-picked back in `main`):
> 
> ```
> Conflicting files
> .circleci/config.yml
> .github/workflows/testing.yml
> vendor/postgres 
> ```

Why does resolving conflicts in that PR require changes in 'main'?

**Comment by petuhovskiy** [comment]
It seems that I triggered CircleCI jobs accidentally and cannot merge this PR anymore. Can someone pick it up or resolve conflicts in some other way?

**Comment by ololobus** [comment]
> It seems that I triggered CircleCI jobs accidentally and cannot merge this PR anymore

Just checked the branch protection rules and I don't see that any Circle are now required for merging, only GH Actions

**Comment by petuhovskiy** [comment]
Superseded by https://github.com/neondatabase/neon/pull/2115

**Pull request closed without merging**
